// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-27 05:08:59 CEST

package bindings

import (
	"unsafe"
)

/*
PFN_vkAllocationFunction is generated from the Khronos Vulkan registry.

[Context]
Application-defined memory allocation function

[Description]
If pfnAllocation is unable to allocate the requested memory, it must
return NULL.
If the allocation was successful, it must return a valid pointer to memory
allocation containing at least size bytes, and with the pointer value
being a multiple of alignment.

Correct Vulkan operation cannot be assumed if the application does not
follow these rules.

For example, pfnAllocation (or pfnReallocation) could cause
termination of running Vulkan instance(s) on a failed allocation for
debugging purposes, either directly or indirectly.
In these circumstances, it cannot be assumed that any part of any affected
VkInstance objects are going to operate correctly (even
vkDestroyInstance), and the application must ensure it cleans up
properly via other means (e.g. process termination).

If pfnAllocation returns NULL, and if the implementation is unable
to continue correct processing of the current command without the requested
allocation, it must treat this as a runtime error, and generate
VK_ERROR_OUT_OF_HOST_MEMORY at the appropriate time for the command in
which the condition was detected, as described in Return Codes.

If the implementation is able to continue correct processing of the current
command without the requested allocation, then it may do so, and must not
generate VK_ERROR_OUT_OF_HOST_MEMORY as a result of this failed
allocation.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkAllocationFunction.html
*/
type PFN_vkAllocationFunction func(pUserData unsafe.Pointer, size uintptr, alignment uintptr, allocationScope VkSystemAllocationScope) unsafe.Pointer

/*
PFN_vkDebugReportCallbackEXT is generated from the Khronos Vulkan registry.

[Context]
Application-defined debug report callback function

[Description]
The callback must not call vkDestroyDebugReportCallbackEXT.

The callback returns a VkBool32, which is interpreted in a
layer-specified manner.
The application should always return VK_FALSE.
The VK_TRUE value is reserved for use in layer development.

object must be a Vulkan object or VK_NULL_HANDLE.
If objectType is not VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT and
object is not VK_NULL_HANDLE, object must be a Vulkan
object of the corresponding type associated with objectType as defined
in VkDebugReportObjectTypeEXT and Vulkan Handle Relationship.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkDebugReportCallbackEXT.html
*/
type PFN_vkDebugReportCallbackEXT func(flags VkDebugReportFlagsEXT, objectType VkDebugReportObjectTypeEXT, object uint64, location uintptr, messageCode int32, pLayerPrefix *byte, pMessage *byte, pUserData unsafe.Pointer) uint32

/*
PFN_vkDebugUtilsMessengerCallbackEXT is generated from the Khronos Vulkan registry.

[Context]
Application-defined debug messenger callback function

[Description]
The callback returns a VkBool32, which is interpreted in a
layer-specified manner.
The application should always return VK_FALSE.
The VK_TRUE value is reserved for use in layer development.

[Valid Usage]

- VUID-PFN_vkDebugUtilsMessengerCallbackEXT-None-04769 The callback must not make calls to any Vulkan commands

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkDebugUtilsMessengerCallbackEXT.html
*/
type PFN_vkDebugUtilsMessengerCallbackEXT func(messageSeverity VkDebugUtilsMessageSeverityFlagsEXT, messageTypes VkDebugUtilsMessageTypeFlagsEXT, pCallbackData *VkDebugUtilsMessengerCallbackDataEXT, pUserData unsafe.Pointer) uint32

/*
PFN_vkDeviceMemoryReportCallbackEXT is generated from the Khronos Vulkan registry.

[Context]
Application-defined device memory report callback function

[Description]
The callback must not make calls to any Vulkan commands.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkDeviceMemoryReportCallbackEXT.html
*/
type PFN_vkDeviceMemoryReportCallbackEXT func(pCallbackData *VkDeviceMemoryReportCallbackDataEXT, pUserData unsafe.Pointer)

/*
PFN_vkFaultCallbackFunction is generated from the Khronos Vulkan registry.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkFaultCallbackFunction.html
*/
type PFN_vkFaultCallbackFunction func(unrecordedFaults uint32, faultCount uint32, pFaults *VkFaultData)

/*
PFN_vkFreeFunction is generated from the Khronos Vulkan registry.

[Context]
Application-defined memory free function

[Description]
pMemory may be NULL, which the callback must handle safely.
If pMemory is non-NULL, it must be a pointer previously allocated
by pfnAllocation or pfnReallocation.
The application should free this memory.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkFreeFunction.html
*/
type PFN_vkFreeFunction func(pUserData unsafe.Pointer, pMemory unsafe.Pointer)

/*
PFN_vkGetInstanceProcAddrLUNARG is generated from the Khronos Vulkan registry.

[Context]
Type definition for vkGetInstanceProcAddr

[Description]
This type is compatible with the type of a pointer to the
vkGetInstanceProcAddr command, but is used only to specify device
driver addresses in
VkDirectDriverLoadingInfoLUNARG::pfnGetInstanceProcAddr.

This type exists only because of limitations in the XML schema and
processing scripts, and its name may change in the future.
Ideally we would use the PFN_vkGetInstanceProcAddr type generated in
the vulkan_core.h header.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkGetInstanceProcAddrLUNARG.html
*/
type PFN_vkGetInstanceProcAddrLUNARG func(instance VkInstance, pName *byte) PFN_vkVoidFunction

/*
PFN_vkInternalAllocationNotification is generated from the Khronos Vulkan registry.

[Context]
Application-defined memory allocation notification function

[Description]
This is a purely informational callback.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkInternalAllocationNotification.html
*/
type PFN_vkInternalAllocationNotification func(pUserData unsafe.Pointer, size uintptr, allocationType VkInternalAllocationType, allocationScope VkSystemAllocationScope)

/*
PFN_vkInternalFreeNotification is generated from the Khronos Vulkan registry.

[Context]
Application-defined memory free notification function

[Description]
described xref:spec::chapters/memory.adoc#memory-host-allocation-scope[here].

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkInternalFreeNotification.html
*/
type PFN_vkInternalFreeNotification func(pUserData unsafe.Pointer, size uintptr, allocationType VkInternalAllocationType, allocationScope VkSystemAllocationScope)

/*
PFN_vkReallocationFunction is generated from the Khronos Vulkan registry.

[Context]
Application-defined memory reallocation function

[Description]
If the reallocation was successful, pfnReallocation must return an
allocation with enough space for size bytes, and the contents of the
original allocation from bytes zero to min(original size, new size) -
1 must be preserved in the returned allocation.
If size is larger than the old size, the contents of the additional
space are undefined.
If satisfying these requirements involves creating a new allocation, then
the old allocation should be freed.

If pOriginal is NULL, then pfnReallocation must behave
equivalently to a call to PFN_vkAllocationFunction with the same
parameter values (without pOriginal).

If size is zero, then pfnReallocation must behave equivalently
to a call to PFN_vkFreeFunction with the same pUserData
parameter value, and pMemory equal to pOriginal.

If pOriginal is non-NULL, the implementation must ensure that
alignment is equal to the alignment used to originally allocate
pOriginal.

If this function fails and pOriginal is non-NULL the application
must not free the old allocation.

pfnReallocation must follow the same
rules for return values as PFN_vkAllocationFunction.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkReallocationFunction.html
*/
type PFN_vkReallocationFunction func(pUserData unsafe.Pointer, pOriginal unsafe.Pointer, size uintptr, alignment uintptr, allocationScope VkSystemAllocationScope) unsafe.Pointer

/*
PFN_vkVoidFunction is generated from the Khronos Vulkan registry.

[Context]
Placeholder function pointer type returned by queries

[Description]
This type is returned from command function pointer queries, and must be
cast to an actual command function pointer before use.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkVoidFunction.html
*/
type PFN_vkVoidFunction func()
