// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-25 10:41:37 CEST

package bindings

/*
VkAccelerationStructureKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an acceleration structure object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkAccelerationStructureKHR.html
*/
type VkAccelerationStructureKHR uint64

/*
VkAccelerationStructureNV is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an acceleration structure object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkAccelerationStructureNV.html
*/
type VkAccelerationStructureNV uint64

/*
VkBuffer is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a buffer object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkBuffer.html
*/
type VkBuffer uint64

/*
VkBufferCollectionFUCHSIA is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a buffer collection object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkBufferCollectionFUCHSIA.html
*/
type VkBufferCollectionFUCHSIA uint64

/*
VkBufferView is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a buffer view object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkBufferView.html
*/
type VkBufferView uint64

/*
VkCommandBuffer is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a command buffer object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkCommandBuffer.html
*/
type VkCommandBuffer uintptr

/*
VkCommandPool is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a command pool object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkCommandPool.html
*/
type VkCommandPool uint64

/*
VkCuFunctionNVX is generated from the Khronos Vulkan registry.

[Context]
Stub description of VkCuFunctionNVX

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkCuFunctionNVX.html
*/
type VkCuFunctionNVX uint64

/*
VkCuModuleNVX is generated from the Khronos Vulkan registry.

[Context]
Stub description of VkCuModuleNVX

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkCuModuleNVX.html
*/
type VkCuModuleNVX uint64

/*
VkCudaFunctionNV is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a CUDA function object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkCudaFunctionNV.html
*/
type VkCudaFunctionNV uint64

/*
VkCudaModuleNV is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a CUDA module object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkCudaModuleNV.html
*/
type VkCudaModuleNV uint64

/*
VkDataGraphPipelineSessionARM is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a data graph pipeline session object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDataGraphPipelineSessionARM.html
*/
type VkDataGraphPipelineSessionARM uint64

/*
VkDebugReportCallbackEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a debug report callback object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugReportCallbackEXT.html
*/
type VkDebugReportCallbackEXT uint64

/*
VkDebugUtilsMessengerEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a debug messenger object

[Description]
The debug messenger will provide detailed feedback on the application’s use
of Vulkan when events of interest occur.
When an event of interest does occur, the debug messenger will submit a
debug message to the debug callback that was provided during its creation.
Additionally, the debug messenger is responsible with filtering out debug
messages that the callback is not interested in and will only provide
desired debug messages.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsMessengerEXT.html
*/
type VkDebugUtilsMessengerEXT uint64

/*
VkDeferredOperationKHR is generated from the Khronos Vulkan registry.

[Context]
A deferred operation

[Description]
This handle refers to a tracking structure which manages the execution state
for a deferred command.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeferredOperationKHR.html
*/
type VkDeferredOperationKHR uint64

/*
VkDescriptorPool is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a descriptor pool object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorPool.html
*/
type VkDescriptorPool uint64

/*
VkDescriptorSet is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a descriptor set object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorSet.html
*/
type VkDescriptorSet uint64

/*
VkDescriptorSetLayout is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a descriptor set layout object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorSetLayout.html
*/
type VkDescriptorSetLayout uint64

/*
VkDescriptorUpdateTemplate is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a descriptor update template

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorUpdateTemplate.html
*/
type VkDescriptorUpdateTemplate uint64

/*
VkDevice is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a device object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDevice.html
*/
type VkDevice uintptr

/*
VkDeviceMemory is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a device memory object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceMemory.html
*/
type VkDeviceMemory uint64

/*
VkDisplayKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a display object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDisplayKHR.html
*/
type VkDisplayKHR uint64

/*
VkDisplayModeKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a display mode object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDisplayModeKHR.html
*/
type VkDisplayModeKHR uint64

/*
VkEvent is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an event object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkEvent.html
*/
type VkEvent uint64

/*
VkExternalComputeQueueNV is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an external compute queue

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkExternalComputeQueueNV.html
*/
type VkExternalComputeQueueNV uintptr

/*
VkFence is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a fence object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkFence.html
*/
type VkFence uint64

/*
VkFramebuffer is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a framebuffer object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkFramebuffer.html
*/
type VkFramebuffer uint64

/*
VkGpaSessionAMD is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a GPU Performance API object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkGpaSessionAMD.html
*/
type VkGpaSessionAMD uint64

/*
VkImage is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an image object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkImage.html
*/
type VkImage uint64

/*
VkImageView is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an image view object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageView.html
*/
type VkImageView uint64

/*
VkIndirectCommandsLayoutEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an indirect commands layout object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkIndirectCommandsLayoutEXT.html
*/
type VkIndirectCommandsLayoutEXT uint64

/*
VkIndirectCommandsLayoutNV is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an indirect commands layout object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkIndirectCommandsLayoutNV.html
*/
type VkIndirectCommandsLayoutNV uint64

/*
VkIndirectExecutionSetEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an indirect execution set object

[Description]
Indirect Execution Sets allow the device to bind different shaders and
pipeline states using Device-Generated Commands.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkIndirectExecutionSetEXT.html
*/
type VkIndirectExecutionSetEXT uint64

/*
VkInstance is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an instance object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkInstance.html
*/
type VkInstance uintptr

/*
VkMicromapEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a micromap object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkMicromapEXT.html
*/
type VkMicromapEXT uint64

/*
VkOpticalFlowSessionNV is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an optical flow session object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkOpticalFlowSessionNV.html
*/
type VkOpticalFlowSessionNV uint64

/*
VkPerformanceConfigurationINTEL is generated from the Khronos Vulkan registry.

[Context]
Device configuration for performance queries

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPerformanceConfigurationINTEL.html
*/
type VkPerformanceConfigurationINTEL uint64

/*
VkPhysicalDevice is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a physical device object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDevice.html
*/
type VkPhysicalDevice uintptr

/*
VkPipeline is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a pipeline object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipeline.html
*/
type VkPipeline uint64

/*
VkPipelineBinaryKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a pipeline binary object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineBinaryKHR.html
*/
type VkPipelineBinaryKHR uint64

/*
VkPipelineCache is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a pipeline cache object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineCache.html
*/
type VkPipelineCache uint64

/*
VkPipelineLayout is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a pipeline layout object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineLayout.html
*/
type VkPipelineLayout uint64

/*
VkPrivateDataSlot is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a private data slot object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPrivateDataSlot.html
*/
type VkPrivateDataSlot uint64

/*
VkQueryPool is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a query pool object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkQueryPool.html
*/
type VkQueryPool uint64

/*
VkQueue is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a queue object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkQueue.html
*/
type VkQueue uintptr

/*
VkRenderPass is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a render pass object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkRenderPass.html
*/
type VkRenderPass uint64

/*
VkSampler is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a sampler object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSampler.html
*/
type VkSampler uint64

/*
VkSamplerYcbcrConversion is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a device-specific sampler Y′CBCR conversion description

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSamplerYcbcrConversion.html
*/
type VkSamplerYcbcrConversion uint64

/*
VkSemaphore is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a semaphore object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSemaphore.html
*/
type VkSemaphore uint64

/*
VkSemaphoreSciSyncPoolNV is generated from the Khronos Vulkan registry.

[Context]
is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SEMAPHORE_SCI_SYNC_POOL_NV.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSemaphoreSciSyncPoolNV.html
*/
type VkSemaphoreSciSyncPoolNV uint64

/*
VkShaderEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a shader object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkShaderEXT.html
*/
type VkShaderEXT uint64

/*
VkShaderInstrumentationARM is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a shader instrumentation object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkShaderInstrumentationARM.html
*/
type VkShaderInstrumentationARM uint64

/*
VkShaderModule is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a shader module object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkShaderModule.html
*/
type VkShaderModule uint64

/*
VkSurfaceKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a surface object

[Description]
The VK_KHR_surface extension declares the VkSurfaceKHR
object, and provides a function for destroying VkSurfaceKHR objects.
Separate platform-specific extensions each provide a function for creating a
VkSurfaceKHR object for the respective platform.
From the application’s perspective this is an opaque handle, just like the
handles of other Vulkan objects.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSurfaceKHR.html
*/
type VkSurfaceKHR uint64

/*
VkSwapchainKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a swapchain object

[Description]
A swapchain is an abstraction for an array of presentable images that are
associated with a surface.
The presentable images are represented by VkImage objects created by
the platform.
One image (which can be an array image for multiview/stereoscopic-3D
surfaces) is displayed at a time, but multiple images can be queued for
presentation.
An application renders to the image, and then queues the image for
presentation to the surface.

A native window cannot be associated with more than one non-retired
swapchain at a time.
Further, swapchains cannot be created for native windows that have a
non-Vulkan graphics API surface associated with them.

The presentation engine is an abstraction for the platform’s compositor or
display engine.

The presentation engine may be synchronous or asynchronous with respect to
the application and/or logical device.

Some implementations may use the device’s graphics queue or dedicated
presentation hardware to perform presentation.

The presentable images of a swapchain are owned by the presentation engine.
An application can acquire use of a presentable image from the presentation
engine.
Use of a presentable image must occur only after the image is returned by
vkAcquireNextImageKHR, and before it is released by
vkQueuePresentKHR.
This includes transitioning the image layout and rendering commands.

An application can acquire use of a presentable image with
vkAcquireNextImageKHR.
After acquiring a presentable image and before modifying it, the application
must use a synchronization primitive to ensure that the presentation engine
has finished reading from the image.
The application can then transition the image’s layout, queue rendering
commands to it, etc.
Finally, the application presents the image with vkQueuePresentKHR,
which releases the acquisition of the image.
The application can also release the acquisition of the image through
vkReleaseSwapchainImagesKHR, if the image is not in use by the device,
and skip the present operation.

The presentation engine controls the order in which presentable images are
acquired for use by the application.

This allows the platform to handle situations which require out-of-order
return of images after presentation.
At the same time, it allows the application to generate command buffers
referencing all of the images in the swapchain at initialization time,
rather than in its main loop.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSwapchainKHR.html
*/
type VkSwapchainKHR uint64

/*
VkTensorARM is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a tensor object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkTensorARM.html
*/
type VkTensorARM uint64

/*
VkTensorViewARM is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to an tensor view object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkTensorViewARM.html
*/
type VkTensorViewARM uint64

/*
VkValidationCacheEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a validation cache object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkValidationCacheEXT.html
*/
type VkValidationCacheEXT uint64

/*
VkVideoSessionKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a video session object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkVideoSessionKHR.html
*/
type VkVideoSessionKHR uint64

/*
VkVideoSessionParametersKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a video session parameters object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkVideoSessionParametersKHR.html
*/
type VkVideoSessionParametersKHR uint64

/*
VkSamplerYcbcrConversionKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a device-specific sampler Y′CBCR conversion description

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSamplerYcbcrConversionKHR.html
*/
type VkSamplerYcbcrConversionKHR = VkSamplerYcbcrConversion

/*
VkDescriptorUpdateTemplateKHR is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a descriptor update template

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorUpdateTemplateKHR.html
*/
type VkDescriptorUpdateTemplateKHR = VkDescriptorUpdateTemplate

/*
VkPrivateDataSlotEXT is generated from the Khronos Vulkan registry.

[Context]
Opaque handle to a private data slot object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkPrivateDataSlotEXT.html
*/
type VkPrivateDataSlotEXT = VkPrivateDataSlot
