// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-22 20:42:46 CEST

package bindings

type VkBool32 = uint32
type VkDeviceAddress = uint64
type VkDeviceSize = uint64
type VkFlags = uint32
type VkFlags64 = uint64
type VkSampleMask = uint32
