// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-22 19:38:37 CEST

package bindings

type VkAccelerationStructureCreateFlagBitsKHRFlags VkFlags

const (
	VK_ACCELERATION_STRUCTURE_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR VkAccelerationStructureCreateFlagBitsKHRFlags = 1 << 0
)

type VkAccessFlags VkFlags

const (
	/*
		VK_ACCESS_INDIRECT_COMMAND_READ_BIT Controls coherency of indirect command reads
	*/
	VK_ACCESS_INDIRECT_COMMAND_READ_BIT VkAccessFlags = 1 << 0

	/*
		VK_ACCESS_INDEX_READ_BIT Controls coherency of index reads
	*/
	VK_ACCESS_INDEX_READ_BIT VkAccessFlags = 1 << 1

	/*
		VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT Controls coherency of vertex attribute reads
	*/
	VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT VkAccessFlags = 1 << 2

	/*
		VK_ACCESS_UNIFORM_READ_BIT Controls coherency of uniform buffer reads
	*/
	VK_ACCESS_UNIFORM_READ_BIT VkAccessFlags = 1 << 3

	/*
		VK_ACCESS_INPUT_ATTACHMENT_READ_BIT Controls coherency of input attachment reads
	*/
	VK_ACCESS_INPUT_ATTACHMENT_READ_BIT VkAccessFlags = 1 << 4

	/*
		VK_ACCESS_SHADER_READ_BIT Controls coherency of shader reads
	*/
	VK_ACCESS_SHADER_READ_BIT VkAccessFlags = 1 << 5

	/*
		VK_ACCESS_SHADER_WRITE_BIT Controls coherency of shader writes
	*/
	VK_ACCESS_SHADER_WRITE_BIT VkAccessFlags = 1 << 6

	/*
		VK_ACCESS_COLOR_ATTACHMENT_READ_BIT Controls coherency of color attachment reads
	*/
	VK_ACCESS_COLOR_ATTACHMENT_READ_BIT VkAccessFlags = 1 << 7

	/*
		VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT Controls coherency of color attachment writes
	*/
	VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT VkAccessFlags = 1 << 8

	/*
		VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT Controls coherency of depth/stencil attachment reads
	*/
	VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT VkAccessFlags = 1 << 9

	/*
		VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT Controls coherency of depth/stencil attachment writes
	*/
	VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT VkAccessFlags = 1 << 10

	/*
		VK_ACCESS_TRANSFER_READ_BIT Controls coherency of transfer reads
	*/
	VK_ACCESS_TRANSFER_READ_BIT VkAccessFlags = 1 << 11

	/*
		VK_ACCESS_TRANSFER_WRITE_BIT Controls coherency of transfer writes
	*/
	VK_ACCESS_TRANSFER_WRITE_BIT VkAccessFlags = 1 << 12

	/*
		VK_ACCESS_HOST_READ_BIT Controls coherency of host reads
	*/
	VK_ACCESS_HOST_READ_BIT VkAccessFlags = 1 << 13

	/*
		VK_ACCESS_HOST_WRITE_BIT Controls coherency of host writes
	*/
	VK_ACCESS_HOST_WRITE_BIT VkAccessFlags = 1 << 14

	/*
		VK_ACCESS_MEMORY_READ_BIT Controls coherency of memory reads
	*/
	VK_ACCESS_MEMORY_READ_BIT VkAccessFlags = 1 << 15

	/*
		VK_ACCESS_MEMORY_WRITE_BIT Controls coherency of memory writes
	*/
	VK_ACCESS_MEMORY_WRITE_BIT VkAccessFlags = 1 << 16
)

type VkAccessFlags2 VkFlags64

const (
	VK_ACCESS_2_NONE                               VkAccessFlags2 = 0
	VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT          VkAccessFlags2 = 1 << 0
	VK_ACCESS_2_INDEX_READ_BIT                     VkAccessFlags2 = 1 << 1
	VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT          VkAccessFlags2 = 1 << 2
	VK_ACCESS_2_UNIFORM_READ_BIT                   VkAccessFlags2 = 1 << 3
	VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT          VkAccessFlags2 = 1 << 4
	VK_ACCESS_2_SHADER_READ_BIT                    VkAccessFlags2 = 1 << 5
	VK_ACCESS_2_SHADER_WRITE_BIT                   VkAccessFlags2 = 1 << 6
	VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT          VkAccessFlags2 = 1 << 7
	VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT         VkAccessFlags2 = 1 << 8
	VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT  VkAccessFlags2 = 1 << 9
	VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT VkAccessFlags2 = 1 << 10
	VK_ACCESS_2_TRANSFER_READ_BIT                  VkAccessFlags2 = 1 << 11
	VK_ACCESS_2_TRANSFER_WRITE_BIT                 VkAccessFlags2 = 1 << 12
	VK_ACCESS_2_HOST_READ_BIT                      VkAccessFlags2 = 1 << 13
	VK_ACCESS_2_HOST_WRITE_BIT                     VkAccessFlags2 = 1 << 14
	VK_ACCESS_2_MEMORY_READ_BIT                    VkAccessFlags2 = 1 << 15
	VK_ACCESS_2_MEMORY_WRITE_BIT                   VkAccessFlags2 = 1 << 16

	/*
		VK_ACCESS_2_SHADER_SAMPLED_READ_BIT bitpos 17-31 are specified by extensions to the original VkAccessFlagBits enum
	*/
	VK_ACCESS_2_SHADER_SAMPLED_READ_BIT VkAccessFlags2 = 1 << 32

	/*
		VK_ACCESS_2_SHADER_STORAGE_READ_BIT bitpos 17-31 are specified by extensions to the original VkAccessFlagBits enum
	*/
	VK_ACCESS_2_SHADER_STORAGE_READ_BIT VkAccessFlags2 = 1 << 33

	/*
		VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT bitpos 17-31 are specified by extensions to the original VkAccessFlagBits enum
	*/
	VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT VkAccessFlags2 = 1 << 34
)

type VkAccessFlagBits3KHRFlags VkFlags64

const (
	VK_ACCESS_3_NONE_KHR VkAccessFlagBits3KHRFlags = 0
)

type VkAcquireProfilingLockFlagBitsKHRFlags VkFlags

type VkAddressCommandFlagBitsKHRFlags VkFlags

const (
	VK_ADDRESS_COMMAND_PROTECTED_BIT_KHR                    VkAddressCommandFlagBitsKHRFlags = 1 << 0
	VK_ADDRESS_COMMAND_FULLY_BOUND_BIT_KHR                  VkAddressCommandFlagBitsKHRFlags = 1 << 1
	VK_ADDRESS_COMMAND_STORAGE_BUFFER_USAGE_BIT_KHR         VkAddressCommandFlagBitsKHRFlags = 1 << 2
	VK_ADDRESS_COMMAND_UNKNOWN_STORAGE_BUFFER_USAGE_BIT_KHR VkAddressCommandFlagBitsKHRFlags = 1 << 3
)

type VkAddressCopyFlagBitsKHRFlags VkFlags

const (
	VK_ADDRESS_COPY_DEVICE_LOCAL_BIT_KHR VkAddressCopyFlagBitsKHRFlags = 1 << 0
	VK_ADDRESS_COPY_SPARSE_BIT_KHR       VkAddressCopyFlagBitsKHRFlags = 1 << 1
	VK_ADDRESS_COPY_PROTECTED_BIT_KHR    VkAddressCopyFlagBitsKHRFlags = 1 << 2
)

type VkAttachmentDescriptionFlags VkFlags

const (
	/*
		VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT The attachment may alias physical memory of another attachment in the same render pass
	*/
	VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT VkAttachmentDescriptionFlags = 1 << 0
)

type VkBufferCreateFlags VkFlags

const (
	/*
		VK_BUFFER_CREATE_SPARSE_BINDING_BIT Buffer should support sparse backing
	*/
	VK_BUFFER_CREATE_SPARSE_BINDING_BIT VkBufferCreateFlags = 1 << 0

	/*
		VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT Buffer should support sparse backing with partial residency
	*/
	VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT VkBufferCreateFlags = 1 << 1

	/*
		VK_BUFFER_CREATE_SPARSE_ALIASED_BIT Buffer should support constant data access to physical memory ranges mapped into multiple locations of sparse buffers
	*/
	VK_BUFFER_CREATE_SPARSE_ALIASED_BIT VkBufferCreateFlags = 1 << 2
)

type VkBufferUsageFlags VkFlags

const (
	/*
		VK_BUFFER_USAGE_TRANSFER_SRC_BIT Can be used as a source of transfer operations
	*/
	VK_BUFFER_USAGE_TRANSFER_SRC_BIT VkBufferUsageFlags = 1 << 0

	/*
		VK_BUFFER_USAGE_TRANSFER_DST_BIT Can be used as a destination of transfer operations
	*/
	VK_BUFFER_USAGE_TRANSFER_DST_BIT VkBufferUsageFlags = 1 << 1

	/*
		VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT Can be used as TBO
	*/
	VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT VkBufferUsageFlags = 1 << 2

	/*
		VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT Can be used as IBO
	*/
	VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT VkBufferUsageFlags = 1 << 3

	/*
		VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT Can be used as UBO
	*/
	VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT VkBufferUsageFlags = 1 << 4

	/*
		VK_BUFFER_USAGE_STORAGE_BUFFER_BIT Can be used as SSBO
	*/
	VK_BUFFER_USAGE_STORAGE_BUFFER_BIT VkBufferUsageFlags = 1 << 5

	/*
		VK_BUFFER_USAGE_INDEX_BUFFER_BIT Can be used as source of fixed-function index fetch (index buffer)
	*/
	VK_BUFFER_USAGE_INDEX_BUFFER_BIT VkBufferUsageFlags = 1 << 6

	/*
		VK_BUFFER_USAGE_VERTEX_BUFFER_BIT Can be used as source of fixed-function vertex fetch (VBO)
	*/
	VK_BUFFER_USAGE_VERTEX_BUFFER_BIT VkBufferUsageFlags = 1 << 7

	/*
		VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT Can be the source of indirect parameters (e.g. indirect buffer, parameter buffer)
	*/
	VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT VkBufferUsageFlags = 1 << 8
)

type VkBufferUsageFlags2 VkFlags64

const (
	VK_BUFFER_USAGE_2_TRANSFER_SRC_BIT         VkBufferUsageFlags2 = 1 << 0
	VK_BUFFER_USAGE_2_TRANSFER_DST_BIT         VkBufferUsageFlags2 = 1 << 1
	VK_BUFFER_USAGE_2_UNIFORM_TEXEL_BUFFER_BIT VkBufferUsageFlags2 = 1 << 2
	VK_BUFFER_USAGE_2_STORAGE_TEXEL_BUFFER_BIT VkBufferUsageFlags2 = 1 << 3
	VK_BUFFER_USAGE_2_UNIFORM_BUFFER_BIT       VkBufferUsageFlags2 = 1 << 4
	VK_BUFFER_USAGE_2_STORAGE_BUFFER_BIT       VkBufferUsageFlags2 = 1 << 5
	VK_BUFFER_USAGE_2_INDEX_BUFFER_BIT         VkBufferUsageFlags2 = 1 << 6
	VK_BUFFER_USAGE_2_VERTEX_BUFFER_BIT        VkBufferUsageFlags2 = 1 << 7
	VK_BUFFER_USAGE_2_INDIRECT_BUFFER_BIT      VkBufferUsageFlags2 = 1 << 8
)

type VkBuildAccelerationStructureFlagBitsKHRFlags VkFlags

const (
	VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR      VkBuildAccelerationStructureFlagBitsKHRFlags = 1 << 0
	VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR  VkBuildAccelerationStructureFlagBitsKHRFlags = 1 << 1
	VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR VkBuildAccelerationStructureFlagBitsKHRFlags = 1 << 2
	VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR VkBuildAccelerationStructureFlagBitsKHRFlags = 1 << 3
	VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_KHR        VkBuildAccelerationStructureFlagBitsKHRFlags = 1 << 4
)

type VkBuildMicromapFlagBitsEXTFlags VkFlags

const (
	VK_BUILD_MICROMAP_PREFER_FAST_TRACE_BIT_EXT VkBuildMicromapFlagBitsEXTFlags = 1 << 0
	VK_BUILD_MICROMAP_PREFER_FAST_BUILD_BIT_EXT VkBuildMicromapFlagBitsEXTFlags = 1 << 1
	VK_BUILD_MICROMAP_ALLOW_COMPACTION_BIT_EXT  VkBuildMicromapFlagBitsEXTFlags = 1 << 2
)

type VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags VkFlags

const (
	VK_CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_NONE_NV                             VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags = 0
	VK_CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_IMPLICIT_DATA_BIT_NV VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags = 1 << 0
	VK_CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SCRATCH_DATA_BIT_NV      VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags = 1 << 1
	VK_CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_ADDRESS_ARRAY_BIT_NV VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags = 1 << 2
	VK_CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_DST_SIZES_ARRAY_BIT_NV   VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags = 1 << 3
	VK_CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SRC_INFOS_ARRAY_BIT_NV   VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags = 1 << 4
	VK_CLUSTER_ACCELERATION_STRUCTURE_ADDRESS_RESOLUTION_INDIRECTED_SRC_INFOS_COUNT_BIT_NV   VkClusterAccelerationStructureAddressResolutionFlagBitsNVFlags = 1 << 5
)

type VkClusterAccelerationStructureClusterFlagBitsNVFlags VkFlags

const (
	VK_CLUSTER_ACCELERATION_STRUCTURE_CLUSTER_ALLOW_DISABLE_OPACITY_MICROMAPS_NV VkClusterAccelerationStructureClusterFlagBitsNVFlags = 1 << 0
)

type VkClusterAccelerationStructureGeometryFlagBitsNVFlags VkFlags

const (
	VK_CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_CULL_DISABLE_BIT_NV                   VkClusterAccelerationStructureGeometryFlagBitsNVFlags = 1 << 0
	VK_CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_NO_DUPLICATE_ANYHIT_INVOCATION_BIT_NV VkClusterAccelerationStructureGeometryFlagBitsNVFlags = 1 << 1
	VK_CLUSTER_ACCELERATION_STRUCTURE_GEOMETRY_OPAQUE_BIT_NV                         VkClusterAccelerationStructureGeometryFlagBitsNVFlags = 1 << 2
)

type VkClusterAccelerationStructureIndexFormatFlagBitsNVFlags VkFlags

const (
	VK_CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_8BIT_NV  VkClusterAccelerationStructureIndexFormatFlagBitsNVFlags = 1 << 0
	VK_CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_16BIT_NV VkClusterAccelerationStructureIndexFormatFlagBitsNVFlags = 1 << 1
	VK_CLUSTER_ACCELERATION_STRUCTURE_INDEX_FORMAT_32BIT_NV VkClusterAccelerationStructureIndexFormatFlagBitsNVFlags = 1 << 2
)

type VkColorComponentFlags VkFlags

const (
	VK_COLOR_COMPONENT_R_BIT VkColorComponentFlags = 1 << 0
	VK_COLOR_COMPONENT_G_BIT VkColorComponentFlags = 1 << 1
	VK_COLOR_COMPONENT_B_BIT VkColorComponentFlags = 1 << 2
	VK_COLOR_COMPONENT_A_BIT VkColorComponentFlags = 1 << 3
)

type VkCommandBufferResetFlags VkFlags

const (
	/*
		VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT Release resources owned by the buffer
	*/
	VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT VkCommandBufferResetFlags = 1 << 0
)

type VkCommandBufferUsageFlags VkFlags

const (
	VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT      VkCommandBufferUsageFlags = 1 << 0
	VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT VkCommandBufferUsageFlags = 1 << 1

	/*
		VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT Command buffer may be submitted/executed more than once simultaneously
	*/
	VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT VkCommandBufferUsageFlags = 1 << 2
)

type VkCommandPoolCreateFlags VkFlags

const (
	/*
		VK_COMMAND_POOL_CREATE_TRANSIENT_BIT Command buffers have a short lifetime
	*/
	VK_COMMAND_POOL_CREATE_TRANSIENT_BIT VkCommandPoolCreateFlags = 1 << 0

	/*
		VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT Command buffers may release their memory individually
	*/
	VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT VkCommandPoolCreateFlags = 1 << 1
)

type VkCommandPoolResetFlags VkFlags

const (
	/*
		VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT Release resources owned by the pool
	*/
	VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT VkCommandPoolResetFlags = 1 << 0
)

type VkCompositeAlphaFlagBitsKHRFlags VkFlags

const (
	VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR          VkCompositeAlphaFlagBitsKHRFlags = 1 << 0
	VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR  VkCompositeAlphaFlagBitsKHRFlags = 1 << 1
	VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR VkCompositeAlphaFlagBitsKHRFlags = 1 << 2
	VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR         VkCompositeAlphaFlagBitsKHRFlags = 1 << 3
)

type VkConditionalRenderingFlagBitsEXTFlags VkFlags

const (
	VK_CONDITIONAL_RENDERING_INVERTED_BIT_EXT VkConditionalRenderingFlagBitsEXTFlags = 1 << 0
)

type VkCullModeFlags VkFlags

const (
	VK_CULL_MODE_NONE           VkCullModeFlags = 0
	VK_CULL_MODE_FRONT_BIT      VkCullModeFlags = 1 << 0
	VK_CULL_MODE_BACK_BIT       VkCullModeFlags = 1 << 1
	VK_CULL_MODE_FRONT_AND_BACK VkCullModeFlags = 0x00000003
)

type VkDataGraphOpticalFlowCreateFlagBitsARMFlags VkFlags

const (
	VK_DATA_GRAPH_OPTICAL_FLOW_CREATE_ENABLE_HINT_BIT_ARM VkDataGraphOpticalFlowCreateFlagBitsARMFlags = 1 << 0
	VK_DATA_GRAPH_OPTICAL_FLOW_CREATE_ENABLE_COST_BIT_ARM VkDataGraphOpticalFlowCreateFlagBitsARMFlags = 1 << 1
	VK_DATA_GRAPH_OPTICAL_FLOW_CREATE_RESERVED_30_BIT_ARM VkDataGraphOpticalFlowCreateFlagBitsARMFlags = 1 << 30
)

type VkDataGraphOpticalFlowExecuteFlagBitsARMFlags VkFlags

const (
	VK_DATA_GRAPH_OPTICAL_FLOW_EXECUTE_DISABLE_TEMPORAL_HINTS_BIT_ARM      VkDataGraphOpticalFlowExecuteFlagBitsARMFlags = 1 << 0
	VK_DATA_GRAPH_OPTICAL_FLOW_EXECUTE_INPUT_UNCHANGED_BIT_ARM             VkDataGraphOpticalFlowExecuteFlagBitsARMFlags = 1 << 1
	VK_DATA_GRAPH_OPTICAL_FLOW_EXECUTE_REFERENCE_UNCHANGED_BIT_ARM         VkDataGraphOpticalFlowExecuteFlagBitsARMFlags = 1 << 2
	VK_DATA_GRAPH_OPTICAL_FLOW_EXECUTE_INPUT_IS_PREVIOUS_REFERENCE_BIT_ARM VkDataGraphOpticalFlowExecuteFlagBitsARMFlags = 1 << 3
	VK_DATA_GRAPH_OPTICAL_FLOW_EXECUTE_REFERENCE_IS_PREVIOUS_INPUT_BIT_ARM VkDataGraphOpticalFlowExecuteFlagBitsARMFlags = 1 << 4
)

type VkDataGraphOpticalFlowGridSizeFlagBitsARMFlags VkFlags

const (
	VK_DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_UNKNOWN_ARM VkDataGraphOpticalFlowGridSizeFlagBitsARMFlags = 0
	VK_DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_1X1_BIT_ARM VkDataGraphOpticalFlowGridSizeFlagBitsARMFlags = 1 << 0
	VK_DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_2X2_BIT_ARM VkDataGraphOpticalFlowGridSizeFlagBitsARMFlags = 1 << 1
	VK_DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_4X4_BIT_ARM VkDataGraphOpticalFlowGridSizeFlagBitsARMFlags = 1 << 2
	VK_DATA_GRAPH_OPTICAL_FLOW_GRID_SIZE_8X8_BIT_ARM VkDataGraphOpticalFlowGridSizeFlagBitsARMFlags = 1 << 3
)

type VkDataGraphOpticalFlowImageUsageFlagBitsARMFlags VkFlags

const (
	VK_DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_UNKNOWN_ARM    VkDataGraphOpticalFlowImageUsageFlagBitsARMFlags = 0
	VK_DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_INPUT_BIT_ARM  VkDataGraphOpticalFlowImageUsageFlagBitsARMFlags = 1 << 0
	VK_DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_OUTPUT_BIT_ARM VkDataGraphOpticalFlowImageUsageFlagBitsARMFlags = 1 << 1
	VK_DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_HINT_BIT_ARM   VkDataGraphOpticalFlowImageUsageFlagBitsARMFlags = 1 << 2
	VK_DATA_GRAPH_OPTICAL_FLOW_IMAGE_USAGE_COST_BIT_ARM   VkDataGraphOpticalFlowImageUsageFlagBitsARMFlags = 1 << 3
)

type VkDataGraphPipelineDispatchFlagBitsARMFlags VkFlags64

type VkDataGraphPipelineSessionCreateFlagBitsARMFlags VkFlags64

const (
	VK_DATA_GRAPH_PIPELINE_SESSION_CREATE_PROTECTED_BIT_ARM VkDataGraphPipelineSessionCreateFlagBitsARMFlags = 1 << 0
)

type VkDataGraphTOSAQualityFlagBitsARMFlags VkFlags

const (
	VK_DATA_GRAPH_TOSA_QUALITY_ACCELERATED_ARM  VkDataGraphTOSAQualityFlagBitsARMFlags = 1 << 0
	VK_DATA_GRAPH_TOSA_QUALITY_CONFORMANT_ARM   VkDataGraphTOSAQualityFlagBitsARMFlags = 1 << 1
	VK_DATA_GRAPH_TOSA_QUALITY_EXPERIMENTAL_ARM VkDataGraphTOSAQualityFlagBitsARMFlags = 1 << 2
	VK_DATA_GRAPH_TOSA_QUALITY_DEPRECATED_ARM   VkDataGraphTOSAQualityFlagBitsARMFlags = 1 << 3
)

type VkDebugReportFlagBitsEXTFlags VkFlags

const (
	VK_DEBUG_REPORT_INFORMATION_BIT_EXT         VkDebugReportFlagBitsEXTFlags = 1 << 0
	VK_DEBUG_REPORT_WARNING_BIT_EXT             VkDebugReportFlagBitsEXTFlags = 1 << 1
	VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT VkDebugReportFlagBitsEXTFlags = 1 << 2
	VK_DEBUG_REPORT_ERROR_BIT_EXT               VkDebugReportFlagBitsEXTFlags = 1 << 3
	VK_DEBUG_REPORT_DEBUG_BIT_EXT               VkDebugReportFlagBitsEXTFlags = 1 << 4
)

type VkDebugUtilsMessageSeverityFlagBitsEXTFlags VkFlags

const (
	VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT VkDebugUtilsMessageSeverityFlagBitsEXTFlags = 1 << 0
	VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT    VkDebugUtilsMessageSeverityFlagBitsEXTFlags = 1 << 4
	VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT VkDebugUtilsMessageSeverityFlagBitsEXTFlags = 1 << 8
	VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT   VkDebugUtilsMessageSeverityFlagBitsEXTFlags = 1 << 12
)

type VkDebugUtilsMessageTypeFlagBitsEXTFlags VkFlags

const (
	VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT     VkDebugUtilsMessageTypeFlagBitsEXTFlags = 1 << 0
	VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT  VkDebugUtilsMessageTypeFlagBitsEXTFlags = 1 << 1
	VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT VkDebugUtilsMessageTypeFlagBitsEXTFlags = 1 << 2
)

type VkDependencyFlags VkFlags

const (
	/*
		VK_DEPENDENCY_BY_REGION_BIT Dependency is per pixel region
	*/
	VK_DEPENDENCY_BY_REGION_BIT VkDependencyFlags = 1 << 0
)

type VkDescriptorBindingFlags VkFlags

const (
	VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT           VkDescriptorBindingFlags = 1 << 0
	VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT VkDescriptorBindingFlags = 1 << 1
	VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT             VkDescriptorBindingFlags = 1 << 2
	VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT   VkDescriptorBindingFlags = 1 << 3
)

type VkDescriptorPoolCreateFlags VkFlags

const (
	/*
		VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT Descriptor sets may be freed individually
	*/
	VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT VkDescriptorPoolCreateFlags = 1 << 0
)

type VkDescriptorSetLayoutCreateFlags VkFlags

type VkDeviceAddressBindingFlagBitsEXTFlags VkFlags

const (
	VK_DEVICE_ADDRESS_BINDING_INTERNAL_OBJECT_BIT_EXT VkDeviceAddressBindingFlagBitsEXTFlags = 1 << 0
)

type VkDeviceDiagnosticsConfigFlagBitsNVFlags VkFlags

const (
	VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_SHADER_DEBUG_INFO_BIT_NV      VkDeviceDiagnosticsConfigFlagBitsNVFlags = 1 << 0
	VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_RESOURCE_TRACKING_BIT_NV      VkDeviceDiagnosticsConfigFlagBitsNVFlags = 1 << 1
	VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_AUTOMATIC_CHECKPOINTS_BIT_NV  VkDeviceDiagnosticsConfigFlagBitsNVFlags = 1 << 2
	VK_DEVICE_DIAGNOSTICS_CONFIG_ENABLE_SHADER_ERROR_REPORTING_BIT_NV VkDeviceDiagnosticsConfigFlagBitsNVFlags = 1 << 3
)

type VkDeviceFaultFlagBitsKHRFlags VkFlags

const (
	VK_DEVICE_FAULT_FLAG_DEVICE_LOST_KHR         VkDeviceFaultFlagBitsKHRFlags = 1 << 0
	VK_DEVICE_FAULT_FLAG_MEMORY_ADDRESS_KHR      VkDeviceFaultFlagBitsKHRFlags = 1 << 1
	VK_DEVICE_FAULT_FLAG_INSTRUCTION_ADDRESS_KHR VkDeviceFaultFlagBitsKHRFlags = 1 << 2
	VK_DEVICE_FAULT_FLAG_VENDOR_KHR              VkDeviceFaultFlagBitsKHRFlags = 1 << 3
	VK_DEVICE_FAULT_FLAG_WATCHDOG_TIMEOUT_KHR    VkDeviceFaultFlagBitsKHRFlags = 1 << 4
	VK_DEVICE_FAULT_FLAG_OVERFLOW_KHR            VkDeviceFaultFlagBitsKHRFlags = 1 << 5
)

type VkDeviceGroupPresentModeFlagBitsKHRFlags VkFlags

const (
	/*
		VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR Present from local memory
	*/
	VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR VkDeviceGroupPresentModeFlagBitsKHRFlags = 1 << 0

	/*
		VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR Present from remote memory
	*/
	VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR VkDeviceGroupPresentModeFlagBitsKHRFlags = 1 << 1

	/*
		VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR Present sum of local and/or remote memory
	*/
	VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR VkDeviceGroupPresentModeFlagBitsKHRFlags = 1 << 2

	/*
		VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR Each physical device presents from local memory
	*/
	VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR VkDeviceGroupPresentModeFlagBitsKHRFlags = 1 << 3
)

type VkDeviceQueueCreateFlags VkFlags

type VkDisplayPlaneAlphaFlagBitsKHRFlags VkFlags

const (
	VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR                  VkDisplayPlaneAlphaFlagBitsKHRFlags = 1 << 0
	VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR                  VkDisplayPlaneAlphaFlagBitsKHRFlags = 1 << 1
	VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR               VkDisplayPlaneAlphaFlagBitsKHRFlags = 1 << 2
	VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR VkDisplayPlaneAlphaFlagBitsKHRFlags = 1 << 3
)

type VkEventCreateFlags VkFlags

type VkExportMetalObjectTypeFlagBitsEXTFlags VkFlags

const (
	VK_EXPORT_METAL_OBJECT_TYPE_METAL_DEVICE_BIT_EXT        VkExportMetalObjectTypeFlagBitsEXTFlags = 1 << 0
	VK_EXPORT_METAL_OBJECT_TYPE_METAL_COMMAND_QUEUE_BIT_EXT VkExportMetalObjectTypeFlagBitsEXTFlags = 1 << 1
	VK_EXPORT_METAL_OBJECT_TYPE_METAL_BUFFER_BIT_EXT        VkExportMetalObjectTypeFlagBitsEXTFlags = 1 << 2
	VK_EXPORT_METAL_OBJECT_TYPE_METAL_TEXTURE_BIT_EXT       VkExportMetalObjectTypeFlagBitsEXTFlags = 1 << 3
	VK_EXPORT_METAL_OBJECT_TYPE_METAL_IOSURFACE_BIT_EXT     VkExportMetalObjectTypeFlagBitsEXTFlags = 1 << 4
	VK_EXPORT_METAL_OBJECT_TYPE_METAL_SHARED_EVENT_BIT_EXT  VkExportMetalObjectTypeFlagBitsEXTFlags = 1 << 5
)

type VkExternalFenceFeatureFlags VkFlags

const (
	VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT VkExternalFenceFeatureFlags = 1 << 0
	VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT VkExternalFenceFeatureFlags = 1 << 1
)

type VkExternalFenceHandleTypeFlags VkFlags

const (
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT        VkExternalFenceHandleTypeFlags = 1 << 0
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT     VkExternalFenceHandleTypeFlags = 1 << 1
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT VkExternalFenceHandleTypeFlags = 1 << 2
	VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT          VkExternalFenceHandleTypeFlags = 1 << 3
)

type VkExternalMemoryFeatureFlags VkFlags

const (
	VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT VkExternalMemoryFeatureFlags = 1 << 0
	VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT     VkExternalMemoryFeatureFlags = 1 << 1
	VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT     VkExternalMemoryFeatureFlags = 1 << 2
)

type VkExternalMemoryFeatureFlagBitsNVFlags VkFlags

const (
	VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_NV VkExternalMemoryFeatureFlagBitsNVFlags = 1 << 0
	VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_NV     VkExternalMemoryFeatureFlagBitsNVFlags = 1 << 1
	VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_NV     VkExternalMemoryFeatureFlagBitsNVFlags = 1 << 2
)

type VkExternalMemoryHandleTypeFlags VkFlags

const (
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT         VkExternalMemoryHandleTypeFlags = 1 << 0
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT      VkExternalMemoryHandleTypeFlags = 1 << 1
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT  VkExternalMemoryHandleTypeFlags = 1 << 2
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT     VkExternalMemoryHandleTypeFlags = 1 << 3
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT VkExternalMemoryHandleTypeFlags = 1 << 4
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT        VkExternalMemoryHandleTypeFlags = 1 << 5
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT    VkExternalMemoryHandleTypeFlags = 1 << 6
)

type VkExternalMemoryHandleTypeFlagBitsNVFlags VkFlags

const (
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_NV     VkExternalMemoryHandleTypeFlagBitsNVFlags = 1 << 0
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_NV VkExternalMemoryHandleTypeFlagBitsNVFlags = 1 << 1
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV      VkExternalMemoryHandleTypeFlagBitsNVFlags = 1 << 2
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_KMT_BIT_NV  VkExternalMemoryHandleTypeFlagBitsNVFlags = 1 << 3
)

type VkExternalSemaphoreFeatureFlags VkFlags

const (
	VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT VkExternalSemaphoreFeatureFlags = 1 << 0
	VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT VkExternalSemaphoreFeatureFlags = 1 << 1
)

type VkExternalSemaphoreHandleTypeFlags VkFlags

const (
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT        VkExternalSemaphoreHandleTypeFlags = 1 << 0
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT     VkExternalSemaphoreHandleTypeFlags = 1 << 1
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT VkExternalSemaphoreHandleTypeFlags = 1 << 2
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT      VkExternalSemaphoreHandleTypeFlags = 1 << 3
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT          VkExternalSemaphoreHandleTypeFlags = 1 << 4
)

type VkFenceCreateFlags VkFlags

const (
	VK_FENCE_CREATE_SIGNALED_BIT VkFenceCreateFlags = 1 << 0
)

type VkFenceImportFlags VkFlags

const (
	VK_FENCE_IMPORT_TEMPORARY_BIT VkFenceImportFlags = 1 << 0
)

type VkFormatFeatureFlags VkFlags

const (
	/*
		VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT Format can be used for sampled images (SAMPLED_IMAGE and COMBINED_IMAGE_SAMPLER descriptor types)
	*/
	VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT VkFormatFeatureFlags = 1 << 0

	/*
		VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT Format can be used for storage images (STORAGE_IMAGE descriptor type)
	*/
	VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT VkFormatFeatureFlags = 1 << 1

	/*
		VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT Format supports atomic operations in case it is used for storage images
	*/
	VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT VkFormatFeatureFlags = 1 << 2

	/*
		VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT Format can be used for uniform texel buffers (TBOs)
	*/
	VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT VkFormatFeatureFlags = 1 << 3

	/*
		VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT Format can be used for storage texel buffers (IBOs)
	*/
	VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT VkFormatFeatureFlags = 1 << 4

	/*
		VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT Format supports atomic operations in case it is used for storage texel buffers
	*/
	VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT VkFormatFeatureFlags = 1 << 5

	/*
		VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT Format can be used for vertex buffers (VBOs)
	*/
	VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT VkFormatFeatureFlags = 1 << 6

	/*
		VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT Format can be used for color attachment images
	*/
	VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT VkFormatFeatureFlags = 1 << 7

	/*
		VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT Format supports blending in case it is used for color attachment images
	*/
	VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT VkFormatFeatureFlags = 1 << 8

	/*
		VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT Format can be used for depth/stencil attachment images
	*/
	VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT VkFormatFeatureFlags = 1 << 9

	/*
		VK_FORMAT_FEATURE_BLIT_SRC_BIT Format can be used as the source image of blits with vkCmdBlitImage
	*/
	VK_FORMAT_FEATURE_BLIT_SRC_BIT VkFormatFeatureFlags = 1 << 10

	/*
		VK_FORMAT_FEATURE_BLIT_DST_BIT Format can be used as the destination image of blits with vkCmdBlitImage
	*/
	VK_FORMAT_FEATURE_BLIT_DST_BIT VkFormatFeatureFlags = 1 << 11

	/*
		VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT Format can be filtered with VK_FILTER_LINEAR when being sampled
	*/
	VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT VkFormatFeatureFlags = 1 << 12
)

type VkFormatFeatureFlags2 VkFlags64

const (
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT               VkFormatFeatureFlags2 = 1 << 0
	VK_FORMAT_FEATURE_2_STORAGE_IMAGE_BIT               VkFormatFeatureFlags2 = 1 << 1
	VK_FORMAT_FEATURE_2_STORAGE_IMAGE_ATOMIC_BIT        VkFormatFeatureFlags2 = 1 << 2
	VK_FORMAT_FEATURE_2_UNIFORM_TEXEL_BUFFER_BIT        VkFormatFeatureFlags2 = 1 << 3
	VK_FORMAT_FEATURE_2_STORAGE_TEXEL_BUFFER_BIT        VkFormatFeatureFlags2 = 1 << 4
	VK_FORMAT_FEATURE_2_STORAGE_TEXEL_BUFFER_ATOMIC_BIT VkFormatFeatureFlags2 = 1 << 5
	VK_FORMAT_FEATURE_2_VERTEX_BUFFER_BIT               VkFormatFeatureFlags2 = 1 << 6
	VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT            VkFormatFeatureFlags2 = 1 << 7
	VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BLEND_BIT      VkFormatFeatureFlags2 = 1 << 8
	VK_FORMAT_FEATURE_2_DEPTH_STENCIL_ATTACHMENT_BIT    VkFormatFeatureFlags2 = 1 << 9
	VK_FORMAT_FEATURE_2_BLIT_SRC_BIT                    VkFormatFeatureFlags2 = 1 << 10
	VK_FORMAT_FEATURE_2_BLIT_DST_BIT                    VkFormatFeatureFlags2 = 1 << 11
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_LINEAR_BIT VkFormatFeatureFlags2 = 1 << 12

	/*
		VK_FORMAT_FEATURE_2_TRANSFER_SRC_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_TRANSFER_SRC_BIT VkFormatFeatureFlags2 = 1 << 14

	/*
		VK_FORMAT_FEATURE_2_TRANSFER_DST_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_TRANSFER_DST_BIT VkFormatFeatureFlags2 = 1 << 15

	/*
		VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_MINMAX_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_MINMAX_BIT VkFormatFeatureFlags2 = 1 << 16

	/*
		VK_FORMAT_FEATURE_2_MIDPOINT_CHROMA_SAMPLES_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_MIDPOINT_CHROMA_SAMPLES_BIT VkFormatFeatureFlags2 = 1 << 17

	/*
		VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT VkFormatFeatureFlags2 = 1 << 18

	/*
		VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT VkFormatFeatureFlags2 = 1 << 19

	/*
		VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT VkFormatFeatureFlags2 = 1 << 20

	/*
		VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT VkFormatFeatureFlags2 = 1 << 21

	/*
		VK_FORMAT_FEATURE_2_DISJOINT_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_DISJOINT_BIT VkFormatFeatureFlags2 = 1 << 22

	/*
		VK_FORMAT_FEATURE_2_COSITED_CHROMA_SAMPLES_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_COSITED_CHROMA_SAMPLES_BIT VkFormatFeatureFlags2 = 1 << 23

	/*
		VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT VkFormatFeatureFlags2 = 1 << 31

	/*
		VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT VkFormatFeatureFlags2 = 1 << 32

	/*
		VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT bitpos 13 is an extension interaction with VK_EXT_filter_cubic
	*/
	VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT VkFormatFeatureFlags2 = 1 << 33
)

type VkFrameBoundaryFlagBitsEXTFlags VkFlags

const (
	VK_FRAME_BOUNDARY_FRAME_END_BIT_EXT VkFrameBoundaryFlagBitsEXTFlags = 1 << 0
)

type VkFramebufferCreateFlags VkFlags

type VkGeometryFlagBitsKHRFlags VkFlags

const (
	VK_GEOMETRY_OPAQUE_BIT_KHR                          VkGeometryFlagBitsKHRFlags = 1 << 0
	VK_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_KHR VkGeometryFlagBitsKHRFlags = 1 << 1
)

type VkGeometryInstanceFlagBitsKHRFlags VkFlags

const (
	VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR VkGeometryInstanceFlagBitsKHRFlags = 1 << 0
	VK_GEOMETRY_INSTANCE_TRIANGLE_FLIP_FACING_BIT_KHR         VkGeometryInstanceFlagBitsKHRFlags = 1 << 1
	VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_KHR                 VkGeometryInstanceFlagBitsKHRFlags = 1 << 2
	VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_KHR              VkGeometryInstanceFlagBitsKHRFlags = 1 << 3
)

type VkGpaSqShaderStageFlagBitsAMDFlags VkFlags

const (
	VK_GPA_SQ_SHADER_STAGE_PS_BIT_AMD VkGpaSqShaderStageFlagBitsAMDFlags = 1 << 0
	VK_GPA_SQ_SHADER_STAGE_VS_BIT_AMD VkGpaSqShaderStageFlagBitsAMDFlags = 1 << 1
	VK_GPA_SQ_SHADER_STAGE_GS_BIT_AMD VkGpaSqShaderStageFlagBitsAMDFlags = 1 << 2
	VK_GPA_SQ_SHADER_STAGE_ES_BIT_AMD VkGpaSqShaderStageFlagBitsAMDFlags = 1 << 3
	VK_GPA_SQ_SHADER_STAGE_HS_BIT_AMD VkGpaSqShaderStageFlagBitsAMDFlags = 1 << 4
	VK_GPA_SQ_SHADER_STAGE_LS_BIT_AMD VkGpaSqShaderStageFlagBitsAMDFlags = 1 << 5
	VK_GPA_SQ_SHADER_STAGE_CS_BIT_AMD VkGpaSqShaderStageFlagBitsAMDFlags = 1 << 6
)

type VkGraphicsPipelineLibraryFlagBitsEXTFlags VkFlags

const (
	VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT    VkGraphicsPipelineLibraryFlagBitsEXTFlags = 1 << 0
	VK_GRAPHICS_PIPELINE_LIBRARY_PRE_RASTERIZATION_SHADERS_BIT_EXT VkGraphicsPipelineLibraryFlagBitsEXTFlags = 1 << 1
	VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_SHADER_BIT_EXT           VkGraphicsPipelineLibraryFlagBitsEXTFlags = 1 << 2
	VK_GRAPHICS_PIPELINE_LIBRARY_FRAGMENT_OUTPUT_INTERFACE_BIT_EXT VkGraphicsPipelineLibraryFlagBitsEXTFlags = 1 << 3
)

type VkHostImageCopyFlags VkFlags

const (
	VK_HOST_IMAGE_COPY_MEMCPY_BIT VkHostImageCopyFlags = 1 << 0
)

type VkImageAspectFlags VkFlags

const (
	VK_IMAGE_ASPECT_COLOR_BIT    VkImageAspectFlags = 1 << 0
	VK_IMAGE_ASPECT_DEPTH_BIT    VkImageAspectFlags = 1 << 1
	VK_IMAGE_ASPECT_STENCIL_BIT  VkImageAspectFlags = 1 << 2
	VK_IMAGE_ASPECT_METADATA_BIT VkImageAspectFlags = 1 << 3
)

type VkImageCompressionFixedRateFlagBitsEXTFlags VkFlags

const (
	VK_IMAGE_COMPRESSION_FIXED_RATE_NONE_EXT      VkImageCompressionFixedRateFlagBitsEXTFlags = 0
	VK_IMAGE_COMPRESSION_FIXED_RATE_1BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 0
	VK_IMAGE_COMPRESSION_FIXED_RATE_2BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 1
	VK_IMAGE_COMPRESSION_FIXED_RATE_3BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 2
	VK_IMAGE_COMPRESSION_FIXED_RATE_4BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 3
	VK_IMAGE_COMPRESSION_FIXED_RATE_5BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 4
	VK_IMAGE_COMPRESSION_FIXED_RATE_6BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 5
	VK_IMAGE_COMPRESSION_FIXED_RATE_7BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 6
	VK_IMAGE_COMPRESSION_FIXED_RATE_8BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 7
	VK_IMAGE_COMPRESSION_FIXED_RATE_9BPC_BIT_EXT  VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 8
	VK_IMAGE_COMPRESSION_FIXED_RATE_10BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 9
	VK_IMAGE_COMPRESSION_FIXED_RATE_11BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 10
	VK_IMAGE_COMPRESSION_FIXED_RATE_12BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 11
	VK_IMAGE_COMPRESSION_FIXED_RATE_13BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 12
	VK_IMAGE_COMPRESSION_FIXED_RATE_14BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 13
	VK_IMAGE_COMPRESSION_FIXED_RATE_15BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 14
	VK_IMAGE_COMPRESSION_FIXED_RATE_16BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 15
	VK_IMAGE_COMPRESSION_FIXED_RATE_17BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 16
	VK_IMAGE_COMPRESSION_FIXED_RATE_18BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 17
	VK_IMAGE_COMPRESSION_FIXED_RATE_19BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 18
	VK_IMAGE_COMPRESSION_FIXED_RATE_20BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 19
	VK_IMAGE_COMPRESSION_FIXED_RATE_21BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 20
	VK_IMAGE_COMPRESSION_FIXED_RATE_22BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 21
	VK_IMAGE_COMPRESSION_FIXED_RATE_23BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 22
	VK_IMAGE_COMPRESSION_FIXED_RATE_24BPC_BIT_EXT VkImageCompressionFixedRateFlagBitsEXTFlags = 1 << 23
)

type VkImageCompressionFlagBitsEXTFlags VkFlags

const (
	VK_IMAGE_COMPRESSION_DEFAULT_EXT             VkImageCompressionFlagBitsEXTFlags = 0
	VK_IMAGE_COMPRESSION_FIXED_RATE_DEFAULT_EXT  VkImageCompressionFlagBitsEXTFlags = 1 << 0
	VK_IMAGE_COMPRESSION_FIXED_RATE_EXPLICIT_EXT VkImageCompressionFlagBitsEXTFlags = 1 << 1
	VK_IMAGE_COMPRESSION_DISABLED_EXT            VkImageCompressionFlagBitsEXTFlags = 1 << 2
)

type VkImageConstraintsInfoFlagBitsFUCHSIAFlags VkFlags

const (
	VK_IMAGE_CONSTRAINTS_INFO_CPU_READ_RARELY_FUCHSIA    VkImageConstraintsInfoFlagBitsFUCHSIAFlags = 1 << 0
	VK_IMAGE_CONSTRAINTS_INFO_CPU_READ_OFTEN_FUCHSIA     VkImageConstraintsInfoFlagBitsFUCHSIAFlags = 1 << 1
	VK_IMAGE_CONSTRAINTS_INFO_CPU_WRITE_RARELY_FUCHSIA   VkImageConstraintsInfoFlagBitsFUCHSIAFlags = 1 << 2
	VK_IMAGE_CONSTRAINTS_INFO_CPU_WRITE_OFTEN_FUCHSIA    VkImageConstraintsInfoFlagBitsFUCHSIAFlags = 1 << 3
	VK_IMAGE_CONSTRAINTS_INFO_PROTECTED_OPTIONAL_FUCHSIA VkImageConstraintsInfoFlagBitsFUCHSIAFlags = 1 << 4
)

type VkImageCreateFlags VkFlags

const (
	/*
		VK_IMAGE_CREATE_SPARSE_BINDING_BIT Image should support sparse backing
	*/
	VK_IMAGE_CREATE_SPARSE_BINDING_BIT VkImageCreateFlags = 1 << 0

	/*
		VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT Image should support sparse backing with partial residency
	*/
	VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT VkImageCreateFlags = 1 << 1

	/*
		VK_IMAGE_CREATE_SPARSE_ALIASED_BIT Image should support constant data access to physical memory ranges mapped into multiple locations of sparse images
	*/
	VK_IMAGE_CREATE_SPARSE_ALIASED_BIT VkImageCreateFlags = 1 << 2

	/*
		VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT Allows image views to have different format than the base image
	*/
	VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT VkImageCreateFlags = 1 << 3

	/*
		VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT Allows creating image views with cube type from the created image
	*/
	VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT VkImageCreateFlags = 1 << 4
)

type VkImageFormatConstraintsFlagBitsFUCHSIAFlags VkFlags

type VkImageUsageFlags VkFlags

const (
	/*
		VK_IMAGE_USAGE_TRANSFER_SRC_BIT Can be used as a source of transfer operations
	*/
	VK_IMAGE_USAGE_TRANSFER_SRC_BIT VkImageUsageFlags = 1 << 0

	/*
		VK_IMAGE_USAGE_TRANSFER_DST_BIT Can be used as a destination of transfer operations
	*/
	VK_IMAGE_USAGE_TRANSFER_DST_BIT VkImageUsageFlags = 1 << 1

	/*
		VK_IMAGE_USAGE_SAMPLED_BIT Can be sampled from (SAMPLED_IMAGE and COMBINED_IMAGE_SAMPLER descriptor types)
	*/
	VK_IMAGE_USAGE_SAMPLED_BIT VkImageUsageFlags = 1 << 2

	/*
		VK_IMAGE_USAGE_STORAGE_BIT Can be used as storage image (STORAGE_IMAGE descriptor type)
	*/
	VK_IMAGE_USAGE_STORAGE_BIT VkImageUsageFlags = 1 << 3

	/*
		VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT Can be used as framebuffer color attachment
	*/
	VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT VkImageUsageFlags = 1 << 4

	/*
		VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT Can be used as framebuffer depth/stencil attachment
	*/
	VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT VkImageUsageFlags = 1 << 5

	/*
		VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT Image data not needed outside of rendering
	*/
	VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT VkImageUsageFlags = 1 << 6

	/*
		VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT Can be used as framebuffer input attachment
	*/
	VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT VkImageUsageFlags = 1 << 7
)

type VkImageViewCreateFlags VkFlags

type VkIndirectCommandsInputModeFlagBitsEXTFlags VkFlags

const (
	VK_INDIRECT_COMMANDS_INPUT_MODE_VULKAN_INDEX_BUFFER_EXT VkIndirectCommandsInputModeFlagBitsEXTFlags = 1 << 0
	VK_INDIRECT_COMMANDS_INPUT_MODE_DXGI_INDEX_BUFFER_EXT   VkIndirectCommandsInputModeFlagBitsEXTFlags = 1 << 1
)

type VkIndirectCommandsLayoutUsageFlagBitsEXTFlags VkFlags

const (
	VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_EXT VkIndirectCommandsLayoutUsageFlagBitsEXTFlags = 1 << 0
	VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_EXT VkIndirectCommandsLayoutUsageFlagBitsEXTFlags = 1 << 1
)

type VkIndirectCommandsLayoutUsageFlagBitsNVFlags VkFlags

const (
	VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_NV VkIndirectCommandsLayoutUsageFlagBitsNVFlags = 1 << 0
	VK_INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NV   VkIndirectCommandsLayoutUsageFlagBitsNVFlags = 1 << 1
	VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NV VkIndirectCommandsLayoutUsageFlagBitsNVFlags = 1 << 2
)

type VkIndirectStateFlagBitsNVFlags VkFlags

const (
	VK_INDIRECT_STATE_FLAG_FRONTFACE_BIT_NV VkIndirectStateFlagBitsNVFlags = 1 << 0
)

type VkInstanceCreateFlags VkFlags

type VkMemoryAllocateFlags VkFlags

const (
	/*
		VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT Force allocation on specific devices
	*/
	VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT VkMemoryAllocateFlags = 1 << 0
)

type VkMemoryDecompressionMethodFlagBitsEXTFlags VkFlags64

const (
	VK_MEMORY_DECOMPRESSION_METHOD_GDEFLATE_1_0_BIT_EXT VkMemoryDecompressionMethodFlagBitsEXTFlags = 1 << 0
)

type VkMemoryHeapFlags VkFlags

const (
	/*
		VK_MEMORY_HEAP_DEVICE_LOCAL_BIT If set, heap represents device memory
	*/
	VK_MEMORY_HEAP_DEVICE_LOCAL_BIT VkMemoryHeapFlags = 1 << 0
)

type VkMemoryMapFlags VkFlags

type VkMemoryPropertyFlags VkFlags

const (
	/*
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT If otherwise stated, then allocate memory on device
	*/
	VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT VkMemoryPropertyFlags = 1 << 0

	/*
		VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT Memory is mappable by host
	*/
	VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT VkMemoryPropertyFlags = 1 << 1

	/*
		VK_MEMORY_PROPERTY_HOST_COHERENT_BIT Memory will have i/o coherency. If not set, application may need to use vkFlushMappedMemoryRanges and vkInvalidateMappedMemoryRanges to flush/invalidate host cache
	*/
	VK_MEMORY_PROPERTY_HOST_COHERENT_BIT VkMemoryPropertyFlags = 1 << 2

	/*
		VK_MEMORY_PROPERTY_HOST_CACHED_BIT Memory will be cached by the host
	*/
	VK_MEMORY_PROPERTY_HOST_CACHED_BIT VkMemoryPropertyFlags = 1 << 3

	/*
		VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT Memory may be allocated by the driver when it is required
	*/
	VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT VkMemoryPropertyFlags = 1 << 4
)

type VkMemoryUnmapFlags VkFlags

type VkMicromapCreateFlagBitsEXTFlags VkFlags

const (
	VK_MICROMAP_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT VkMicromapCreateFlagBitsEXTFlags = 1 << 0
)

type VkOpticalFlowExecuteFlagBitsNVFlags VkFlags

const (
	VK_OPTICAL_FLOW_EXECUTE_DISABLE_TEMPORAL_HINTS_BIT_NV VkOpticalFlowExecuteFlagBitsNVFlags = 1 << 0
)

type VkOpticalFlowGridSizeFlagBitsNVFlags VkFlags

const (
	VK_OPTICAL_FLOW_GRID_SIZE_UNKNOWN_NV VkOpticalFlowGridSizeFlagBitsNVFlags = 0
	VK_OPTICAL_FLOW_GRID_SIZE_1X1_BIT_NV VkOpticalFlowGridSizeFlagBitsNVFlags = 1 << 0
	VK_OPTICAL_FLOW_GRID_SIZE_2X2_BIT_NV VkOpticalFlowGridSizeFlagBitsNVFlags = 1 << 1
	VK_OPTICAL_FLOW_GRID_SIZE_4X4_BIT_NV VkOpticalFlowGridSizeFlagBitsNVFlags = 1 << 2
	VK_OPTICAL_FLOW_GRID_SIZE_8X8_BIT_NV VkOpticalFlowGridSizeFlagBitsNVFlags = 1 << 3
)

type VkOpticalFlowSessionCreateFlagBitsNVFlags VkFlags

const (
	VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_HINT_BIT_NV        VkOpticalFlowSessionCreateFlagBitsNVFlags = 1 << 0
	VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_COST_BIT_NV        VkOpticalFlowSessionCreateFlagBitsNVFlags = 1 << 1
	VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_GLOBAL_FLOW_BIT_NV VkOpticalFlowSessionCreateFlagBitsNVFlags = 1 << 2
	VK_OPTICAL_FLOW_SESSION_CREATE_ALLOW_REGIONS_BIT_NV      VkOpticalFlowSessionCreateFlagBitsNVFlags = 1 << 3
	VK_OPTICAL_FLOW_SESSION_CREATE_BOTH_DIRECTIONS_BIT_NV    VkOpticalFlowSessionCreateFlagBitsNVFlags = 1 << 4
)

type VkOpticalFlowUsageFlagBitsNVFlags VkFlags

const (
	VK_OPTICAL_FLOW_USAGE_UNKNOWN_NV         VkOpticalFlowUsageFlagBitsNVFlags = 0
	VK_OPTICAL_FLOW_USAGE_INPUT_BIT_NV       VkOpticalFlowUsageFlagBitsNVFlags = 1 << 0
	VK_OPTICAL_FLOW_USAGE_OUTPUT_BIT_NV      VkOpticalFlowUsageFlagBitsNVFlags = 1 << 1
	VK_OPTICAL_FLOW_USAGE_HINT_BIT_NV        VkOpticalFlowUsageFlagBitsNVFlags = 1 << 2
	VK_OPTICAL_FLOW_USAGE_COST_BIT_NV        VkOpticalFlowUsageFlagBitsNVFlags = 1 << 3
	VK_OPTICAL_FLOW_USAGE_GLOBAL_FLOW_BIT_NV VkOpticalFlowUsageFlagBitsNVFlags = 1 << 4
)

type VkPartitionedAccelerationStructureInstanceFlagBitsNVFlags VkFlags

const (
	VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FACING_CULL_DISABLE_BIT_NV VkPartitionedAccelerationStructureInstanceFlagBitsNVFlags = 1 << 0
	VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FLIP_FACING_BIT_NV         VkPartitionedAccelerationStructureInstanceFlagBitsNVFlags = 1 << 1
	VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_OPAQUE_BIT_NV                 VkPartitionedAccelerationStructureInstanceFlagBitsNVFlags = 1 << 2
	VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_NO_OPAQUE_BIT_NV              VkPartitionedAccelerationStructureInstanceFlagBitsNVFlags = 1 << 3
	VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_ENABLE_EXPLICIT_BOUNDING_BOX_NV     VkPartitionedAccelerationStructureInstanceFlagBitsNVFlags = 1 << 4
)

type VkPastPresentationTimingFlagBitsEXTFlags VkFlags

const (
	VK_PAST_PRESENTATION_TIMING_ALLOW_PARTIAL_RESULTS_BIT_EXT      VkPastPresentationTimingFlagBitsEXTFlags = 1 << 0
	VK_PAST_PRESENTATION_TIMING_ALLOW_OUT_OF_ORDER_RESULTS_BIT_EXT VkPastPresentationTimingFlagBitsEXTFlags = 1 << 1
)

type VkPeerMemoryFeatureFlags VkFlags

const (
	/*
		VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT Can read with vkCmdCopy commands
	*/
	VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT VkPeerMemoryFeatureFlags = 1 << 0

	/*
		VK_PEER_MEMORY_FEATURE_COPY_DST_BIT Can write with vkCmdCopy commands
	*/
	VK_PEER_MEMORY_FEATURE_COPY_DST_BIT VkPeerMemoryFeatureFlags = 1 << 1

	/*
		VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT Can read with any access type/command
	*/
	VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT VkPeerMemoryFeatureFlags = 1 << 2

	/*
		VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT Can write with and access type/command
	*/
	VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT VkPeerMemoryFeatureFlags = 1 << 3
)

type VkPerformanceCounterDescriptionFlagBitsKHRFlags VkFlags

const (
	VK_PERFORMANCE_COUNTER_DESCRIPTION_PERFORMANCE_IMPACTING_BIT_KHR VkPerformanceCounterDescriptionFlagBitsKHRFlags = 1 << 0
	VK_PERFORMANCE_COUNTER_DESCRIPTION_CONCURRENTLY_IMPACTED_BIT_KHR VkPerformanceCounterDescriptionFlagBitsKHRFlags = 1 << 1
)

type VkPhysicalDeviceSchedulingControlsFlagBitsARMFlags VkFlags64

const (
	VK_PHYSICAL_DEVICE_SCHEDULING_CONTROLS_SHADER_CORE_COUNT_ARM   VkPhysicalDeviceSchedulingControlsFlagBitsARMFlags = 1 << 0
	VK_PHYSICAL_DEVICE_SCHEDULING_CONTROLS_DISPATCH_PARAMETERS_ARM VkPhysicalDeviceSchedulingControlsFlagBitsARMFlags = 1 << 1
)

type VkPipelineCacheCreateFlags VkFlags

type VkPipelineColorBlendStateCreateFlags VkFlags

type VkPipelineCompilerControlFlagBitsAMDFlags VkFlags

type VkPipelineCreateFlags VkFlags

const (
	VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT VkPipelineCreateFlags = 1 << 0
	VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT    VkPipelineCreateFlags = 1 << 1
	VK_PIPELINE_CREATE_DERIVATIVE_BIT           VkPipelineCreateFlags = 1 << 2
)

type VkPipelineCreateFlags2 VkFlags64

const (
	VK_PIPELINE_CREATE_2_DISABLE_OPTIMIZATION_BIT              VkPipelineCreateFlags2 = 1 << 0
	VK_PIPELINE_CREATE_2_ALLOW_DERIVATIVES_BIT                 VkPipelineCreateFlags2 = 1 << 1
	VK_PIPELINE_CREATE_2_DERIVATIVE_BIT                        VkPipelineCreateFlags2 = 1 << 2
	VK_PIPELINE_CREATE_2_VIEW_INDEX_FROM_DEVICE_INDEX_BIT      VkPipelineCreateFlags2 = 1 << 3
	VK_PIPELINE_CREATE_2_DISPATCH_BASE_BIT                     VkPipelineCreateFlags2 = 1 << 4
	VK_PIPELINE_CREATE_2_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT VkPipelineCreateFlags2 = 1 << 8
	VK_PIPELINE_CREATE_2_EARLY_RETURN_ON_FAILURE_BIT           VkPipelineCreateFlags2 = 1 << 9
	VK_PIPELINE_CREATE_2_NO_PROTECTED_ACCESS_BIT               VkPipelineCreateFlags2 = 1 << 27
	VK_PIPELINE_CREATE_2_PROTECTED_ACCESS_ONLY_BIT             VkPipelineCreateFlags2 = 1 << 30
)

type VkPipelineCreationFeedbackFlags VkFlags

const (
	VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT                          VkPipelineCreationFeedbackFlags = 1 << 0
	VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT VkPipelineCreationFeedbackFlags = 1 << 1
	VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT     VkPipelineCreationFeedbackFlags = 1 << 2
)

type VkPipelineDepthStencilStateCreateFlags VkFlags

type VkPipelineLayoutCreateFlags VkFlags

type VkPipelineShaderStageCreateFlags VkFlags

type VkPipelineStageFlags VkFlags

const (
	/*
		VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT Before subsequent commands are processed
	*/
	VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT VkPipelineStageFlags = 1 << 0

	/*
		VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT Draw/DispatchIndirect command fetch
	*/
	VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT VkPipelineStageFlags = 1 << 1

	/*
		VK_PIPELINE_STAGE_VERTEX_INPUT_BIT Vertex/index fetch
	*/
	VK_PIPELINE_STAGE_VERTEX_INPUT_BIT VkPipelineStageFlags = 1 << 2

	/*
		VK_PIPELINE_STAGE_VERTEX_SHADER_BIT Vertex shading
	*/
	VK_PIPELINE_STAGE_VERTEX_SHADER_BIT VkPipelineStageFlags = 1 << 3

	/*
		VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT Tessellation control shading
	*/
	VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT VkPipelineStageFlags = 1 << 4

	/*
		VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT Tessellation evaluation shading
	*/
	VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT VkPipelineStageFlags = 1 << 5

	/*
		VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT Geometry shading
	*/
	VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT VkPipelineStageFlags = 1 << 6

	/*
		VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT Fragment shading
	*/
	VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT VkPipelineStageFlags = 1 << 7

	/*
		VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT Early fragment (depth and stencil) tests
	*/
	VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT VkPipelineStageFlags = 1 << 8

	/*
		VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT Late fragment (depth and stencil) tests
	*/
	VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT VkPipelineStageFlags = 1 << 9

	/*
		VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT Color attachment writes
	*/
	VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT VkPipelineStageFlags = 1 << 10

	/*
		VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT Compute shading
	*/
	VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT VkPipelineStageFlags = 1 << 11

	/*
		VK_PIPELINE_STAGE_TRANSFER_BIT Transfer/copy operations
	*/
	VK_PIPELINE_STAGE_TRANSFER_BIT VkPipelineStageFlags = 1 << 12

	/*
		VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT After previous commands have completed
	*/
	VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT VkPipelineStageFlags = 1 << 13

	/*
		VK_PIPELINE_STAGE_HOST_BIT Indicates host (CPU) is a source/sink of the dependency
	*/
	VK_PIPELINE_STAGE_HOST_BIT VkPipelineStageFlags = 1 << 14

	/*
		VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT All stages of the graphics pipeline
	*/
	VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT VkPipelineStageFlags = 1 << 15

	/*
		VK_PIPELINE_STAGE_ALL_COMMANDS_BIT All stages supported on the queue
	*/
	VK_PIPELINE_STAGE_ALL_COMMANDS_BIT VkPipelineStageFlags = 1 << 16
)

type VkPipelineStageFlags2 VkFlags64

const (
	VK_PIPELINE_STAGE_2_NONE                               VkPipelineStageFlags2 = 0
	VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT                    VkPipelineStageFlags2 = 1 << 0
	VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT                  VkPipelineStageFlags2 = 1 << 1
	VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT                   VkPipelineStageFlags2 = 1 << 2
	VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT                  VkPipelineStageFlags2 = 1 << 3
	VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT    VkPipelineStageFlags2 = 1 << 4
	VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT VkPipelineStageFlags2 = 1 << 5
	VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT                VkPipelineStageFlags2 = 1 << 6
	VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT                VkPipelineStageFlags2 = 1 << 7
	VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT           VkPipelineStageFlags2 = 1 << 8
	VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT            VkPipelineStageFlags2 = 1 << 9
	VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT        VkPipelineStageFlags2 = 1 << 10
	VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT                 VkPipelineStageFlags2 = 1 << 11
	VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT                   VkPipelineStageFlags2 = 1 << 12
	VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT                 VkPipelineStageFlags2 = 1 << 13
	VK_PIPELINE_STAGE_2_HOST_BIT                           VkPipelineStageFlags2 = 1 << 14
	VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT                   VkPipelineStageFlags2 = 1 << 15
	VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT                   VkPipelineStageFlags2 = 1 << 16

	/*
		VK_PIPELINE_STAGE_2_COPY_BIT bitpos 17-31 are specified by extensions to the original VkPipelineStageFlagBits enum
	*/
	VK_PIPELINE_STAGE_2_COPY_BIT VkPipelineStageFlags2 = 1 << 32

	/*
		VK_PIPELINE_STAGE_2_RESOLVE_BIT bitpos 17-31 are specified by extensions to the original VkPipelineStageFlagBits enum
	*/
	VK_PIPELINE_STAGE_2_RESOLVE_BIT VkPipelineStageFlags2 = 1 << 33

	/*
		VK_PIPELINE_STAGE_2_BLIT_BIT bitpos 17-31 are specified by extensions to the original VkPipelineStageFlagBits enum
	*/
	VK_PIPELINE_STAGE_2_BLIT_BIT VkPipelineStageFlags2 = 1 << 34

	/*
		VK_PIPELINE_STAGE_2_CLEAR_BIT bitpos 17-31 are specified by extensions to the original VkPipelineStageFlagBits enum
	*/
	VK_PIPELINE_STAGE_2_CLEAR_BIT VkPipelineStageFlags2 = 1 << 35

	/*
		VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT bitpos 17-31 are specified by extensions to the original VkPipelineStageFlagBits enum
	*/
	VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT VkPipelineStageFlags2 = 1 << 36

	/*
		VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT bitpos 17-31 are specified by extensions to the original VkPipelineStageFlagBits enum
	*/
	VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT VkPipelineStageFlags2 = 1 << 37

	/*
		VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT bitpos 17-31 are specified by extensions to the original VkPipelineStageFlagBits enum
	*/
	VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT VkPipelineStageFlags2 = 1 << 38
)

type VkPresentGravityFlagBitsKHRFlags VkFlags

const (
	VK_PRESENT_GRAVITY_MIN_BIT_KHR      VkPresentGravityFlagBitsKHRFlags = 1 << 0
	VK_PRESENT_GRAVITY_MAX_BIT_KHR      VkPresentGravityFlagBitsKHRFlags = 1 << 1
	VK_PRESENT_GRAVITY_CENTERED_BIT_KHR VkPresentGravityFlagBitsKHRFlags = 1 << 2
)

type VkPresentScalingFlagBitsKHRFlags VkFlags

const (
	VK_PRESENT_SCALING_ONE_TO_ONE_BIT_KHR           VkPresentScalingFlagBitsKHRFlags = 1 << 0
	VK_PRESENT_SCALING_ASPECT_RATIO_STRETCH_BIT_KHR VkPresentScalingFlagBitsKHRFlags = 1 << 1
	VK_PRESENT_SCALING_STRETCH_BIT_KHR              VkPresentScalingFlagBitsKHRFlags = 1 << 2
)

type VkPresentStageFlagBitsEXTFlags VkFlags

const (
	VK_PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT      VkPresentStageFlagBitsEXTFlags = 1 << 0
	VK_PRESENT_STAGE_REQUEST_DEQUEUED_BIT_EXT          VkPresentStageFlagBitsEXTFlags = 1 << 1
	VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_OUT_BIT_EXT     VkPresentStageFlagBitsEXTFlags = 1 << 2
	VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT VkPresentStageFlagBitsEXTFlags = 1 << 3
)

type VkPresentTimingInfoFlagBitsEXTFlags VkFlags

const (
	VK_PRESENT_TIMING_INFO_PRESENT_AT_RELATIVE_TIME_BIT_EXT         VkPresentTimingInfoFlagBitsEXTFlags = 1 << 0
	VK_PRESENT_TIMING_INFO_PRESENT_AT_NEAREST_REFRESH_CYCLE_BIT_EXT VkPresentTimingInfoFlagBitsEXTFlags = 1 << 1
)

type VkPrivateDataSlotCreateFlags VkFlags

type VkQueryControlFlags VkFlags

const (
	/*
		VK_QUERY_CONTROL_PRECISE_BIT Require precise results to be collected by the query
	*/
	VK_QUERY_CONTROL_PRECISE_BIT VkQueryControlFlags = 1 << 0
)

type VkQueryPipelineStatisticFlags VkFlags

const (
	/*
		VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT VkQueryPipelineStatisticFlags = 1 << 0

	/*
		VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT VkQueryPipelineStatisticFlags = 1 << 1

	/*
		VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT VkQueryPipelineStatisticFlags = 1 << 2

	/*
		VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT VkQueryPipelineStatisticFlags = 1 << 3

	/*
		VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT VkQueryPipelineStatisticFlags = 1 << 4

	/*
		VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT VkQueryPipelineStatisticFlags = 1 << 5

	/*
		VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT VkQueryPipelineStatisticFlags = 1 << 6

	/*
		VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT VkQueryPipelineStatisticFlags = 1 << 7

	/*
		VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT VkQueryPipelineStatisticFlags = 1 << 8

	/*
		VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT VkQueryPipelineStatisticFlags = 1 << 9

	/*
		VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT Optional
	*/
	VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT VkQueryPipelineStatisticFlags = 1 << 10
)

type VkQueryPoolCreateFlags VkFlags

type VkQueryResultFlags VkFlags

const (
	/*
		VK_QUERY_RESULT_64_BIT Results of the queries are written to the destination buffer as 64-bit values
	*/
	VK_QUERY_RESULT_64_BIT VkQueryResultFlags = 1 << 0

	/*
		VK_QUERY_RESULT_WAIT_BIT Results of the queries are waited on before proceeding with the result copy
	*/
	VK_QUERY_RESULT_WAIT_BIT VkQueryResultFlags = 1 << 1

	/*
		VK_QUERY_RESULT_WITH_AVAILABILITY_BIT Besides the results of the query, the availability of the results is also written
	*/
	VK_QUERY_RESULT_WITH_AVAILABILITY_BIT VkQueryResultFlags = 1 << 2

	/*
		VK_QUERY_RESULT_PARTIAL_BIT Copy the partial results of the query even if the final results are not available
	*/
	VK_QUERY_RESULT_PARTIAL_BIT VkQueryResultFlags = 1 << 3
)

type VkQueueFlags VkFlags

const (
	/*
		VK_QUEUE_GRAPHICS_BIT Queue supports graphics operations
	*/
	VK_QUEUE_GRAPHICS_BIT VkQueueFlags = 1 << 0

	/*
		VK_QUEUE_COMPUTE_BIT Queue supports compute operations
	*/
	VK_QUEUE_COMPUTE_BIT VkQueueFlags = 1 << 1

	/*
		VK_QUEUE_TRANSFER_BIT Queue supports transfer operations
	*/
	VK_QUEUE_TRANSFER_BIT VkQueueFlags = 1 << 2

	/*
		VK_QUEUE_SPARSE_BINDING_BIT Queue supports sparse resource memory management operations
	*/
	VK_QUEUE_SPARSE_BINDING_BIT VkQueueFlags = 1 << 3
)

type VkRefreshObjectFlagBitsKHRFlags VkFlags

type VkRenderPassCreateFlags VkFlags

type VkRenderingAttachmentFlagBitsKHRFlags VkFlags

type VkRenderingFlags VkFlags

const (
	VK_RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT VkRenderingFlags = 1 << 0
	VK_RENDERING_SUSPENDING_BIT                         VkRenderingFlags = 1 << 1
	VK_RENDERING_RESUMING_BIT                           VkRenderingFlags = 1 << 2
)

type VkResolveImageFlagBitsKHRFlags VkFlags

type VkResolveModeFlags VkFlags

const (
	VK_RESOLVE_MODE_NONE            VkResolveModeFlags = 0
	VK_RESOLVE_MODE_SAMPLE_ZERO_BIT VkResolveModeFlags = 1 << 0
	VK_RESOLVE_MODE_AVERAGE_BIT     VkResolveModeFlags = 1 << 1
	VK_RESOLVE_MODE_MIN_BIT         VkResolveModeFlags = 1 << 2
	VK_RESOLVE_MODE_MAX_BIT         VkResolveModeFlags = 1 << 3
)

type VkSampleCountFlags VkFlags

const (
	/*
		VK_SAMPLE_COUNT_1_BIT Sample count 1 supported
	*/
	VK_SAMPLE_COUNT_1_BIT VkSampleCountFlags = 1 << 0

	/*
		VK_SAMPLE_COUNT_2_BIT Sample count 2 supported
	*/
	VK_SAMPLE_COUNT_2_BIT VkSampleCountFlags = 1 << 1

	/*
		VK_SAMPLE_COUNT_4_BIT Sample count 4 supported
	*/
	VK_SAMPLE_COUNT_4_BIT VkSampleCountFlags = 1 << 2

	/*
		VK_SAMPLE_COUNT_8_BIT Sample count 8 supported
	*/
	VK_SAMPLE_COUNT_8_BIT VkSampleCountFlags = 1 << 3

	/*
		VK_SAMPLE_COUNT_16_BIT Sample count 16 supported
	*/
	VK_SAMPLE_COUNT_16_BIT VkSampleCountFlags = 1 << 4

	/*
		VK_SAMPLE_COUNT_32_BIT Sample count 32 supported
	*/
	VK_SAMPLE_COUNT_32_BIT VkSampleCountFlags = 1 << 5

	/*
		VK_SAMPLE_COUNT_64_BIT Sample count 64 supported
	*/
	VK_SAMPLE_COUNT_64_BIT VkSampleCountFlags = 1 << 6
)

type VkSamplerCreateFlags VkFlags

type VkSemaphoreCreateFlags VkFlags

type VkSemaphoreImportFlags VkFlags

const (
	VK_SEMAPHORE_IMPORT_TEMPORARY_BIT VkSemaphoreImportFlags = 1 << 0
)

type VkSemaphoreWaitFlags VkFlags

const (
	VK_SEMAPHORE_WAIT_ANY_BIT VkSemaphoreWaitFlags = 1 << 0
)

type VkShaderCorePropertiesFlagBitsAMDFlags VkFlags

type VkShaderCreateFlagBitsEXTFlags VkFlags

const (
	VK_SHADER_CREATE_LINK_STAGE_BIT_EXT VkShaderCreateFlagBitsEXTFlags = 1 << 0
)

type VkShaderModuleCreateFlags VkFlags

type VkShaderStageFlags VkFlags

const (
	VK_SHADER_STAGE_VERTEX_BIT                  VkShaderStageFlags = 1 << 0
	VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT    VkShaderStageFlags = 1 << 1
	VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT VkShaderStageFlags = 1 << 2
	VK_SHADER_STAGE_GEOMETRY_BIT                VkShaderStageFlags = 1 << 3
	VK_SHADER_STAGE_FRAGMENT_BIT                VkShaderStageFlags = 1 << 4
	VK_SHADER_STAGE_COMPUTE_BIT                 VkShaderStageFlags = 1 << 5
	VK_SHADER_STAGE_ALL_GRAPHICS                VkShaderStageFlags = 0x0000001F
	VK_SHADER_STAGE_ALL                         VkShaderStageFlags = 0x7FFFFFFF
)

type VkSparseImageFormatFlags VkFlags

const (
	/*
		VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT Image uses a single mip tail region for all array layers
	*/
	VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT VkSparseImageFormatFlags = 1 << 0

	/*
		VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT Image requires mip level dimensions to be an integer multiple of the sparse image block dimensions for non-tail mip levels.
	*/
	VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT VkSparseImageFormatFlags = 1 << 1

	/*
		VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT Image uses a non-standard sparse image block dimensions
	*/
	VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT VkSparseImageFormatFlags = 1 << 2
)

type VkSparseMemoryBindFlags VkFlags

const (
	/*
		VK_SPARSE_MEMORY_BIND_METADATA_BIT Operation binds resource metadata to memory
	*/
	VK_SPARSE_MEMORY_BIND_METADATA_BIT VkSparseMemoryBindFlags = 1 << 0
)

type VkSpirvResourceTypeFlagBitsEXTFlags VkFlags

const (
	VK_SPIRV_RESOURCE_TYPE_ALL_EXT                           VkSpirvResourceTypeFlagBitsEXTFlags = 0x7FFFFFFF
	VK_SPIRV_RESOURCE_TYPE_SAMPLER_BIT_EXT                   VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 0
	VK_SPIRV_RESOURCE_TYPE_SAMPLED_IMAGE_BIT_EXT             VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 1
	VK_SPIRV_RESOURCE_TYPE_READ_ONLY_IMAGE_BIT_EXT           VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 2
	VK_SPIRV_RESOURCE_TYPE_READ_WRITE_IMAGE_BIT_EXT          VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 3
	VK_SPIRV_RESOURCE_TYPE_COMBINED_SAMPLED_IMAGE_BIT_EXT    VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 4
	VK_SPIRV_RESOURCE_TYPE_UNIFORM_BUFFER_BIT_EXT            VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 5
	VK_SPIRV_RESOURCE_TYPE_READ_ONLY_STORAGE_BUFFER_BIT_EXT  VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 6
	VK_SPIRV_RESOURCE_TYPE_READ_WRITE_STORAGE_BUFFER_BIT_EXT VkSpirvResourceTypeFlagBitsEXTFlags = 1 << 7
)

type VkStencilFaceFlags VkFlags

const (
	/*
		VK_STENCIL_FACE_FRONT_BIT Front face
	*/
	VK_STENCIL_FACE_FRONT_BIT VkStencilFaceFlags = 1 << 0

	/*
		VK_STENCIL_FACE_BACK_BIT Back face
	*/
	VK_STENCIL_FACE_BACK_BIT VkStencilFaceFlags = 1 << 1

	/*
		VK_STENCIL_FACE_FRONT_AND_BACK Front and back faces
	*/
	VK_STENCIL_FACE_FRONT_AND_BACK VkStencilFaceFlags = 0x00000003
)

type VkSubgroupFeatureFlags VkFlags

const (
	/*
		VK_SUBGROUP_FEATURE_BASIC_BIT Basic subgroup operations
	*/
	VK_SUBGROUP_FEATURE_BASIC_BIT VkSubgroupFeatureFlags = 1 << 0

	/*
		VK_SUBGROUP_FEATURE_VOTE_BIT Vote subgroup operations
	*/
	VK_SUBGROUP_FEATURE_VOTE_BIT VkSubgroupFeatureFlags = 1 << 1

	/*
		VK_SUBGROUP_FEATURE_ARITHMETIC_BIT Arithmetic subgroup operations
	*/
	VK_SUBGROUP_FEATURE_ARITHMETIC_BIT VkSubgroupFeatureFlags = 1 << 2

	/*
		VK_SUBGROUP_FEATURE_BALLOT_BIT Ballot subgroup operations
	*/
	VK_SUBGROUP_FEATURE_BALLOT_BIT VkSubgroupFeatureFlags = 1 << 3

	/*
		VK_SUBGROUP_FEATURE_SHUFFLE_BIT Shuffle subgroup operations
	*/
	VK_SUBGROUP_FEATURE_SHUFFLE_BIT VkSubgroupFeatureFlags = 1 << 4

	/*
		VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT Shuffle relative subgroup operations
	*/
	VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT VkSubgroupFeatureFlags = 1 << 5

	/*
		VK_SUBGROUP_FEATURE_CLUSTERED_BIT Clustered subgroup operations
	*/
	VK_SUBGROUP_FEATURE_CLUSTERED_BIT VkSubgroupFeatureFlags = 1 << 6

	/*
		VK_SUBGROUP_FEATURE_QUAD_BIT Quad subgroup operations
	*/
	VK_SUBGROUP_FEATURE_QUAD_BIT VkSubgroupFeatureFlags = 1 << 7
)

type VkSubmitFlags VkFlags

const (
	VK_SUBMIT_PROTECTED_BIT VkSubmitFlags = 1 << 0
)

type VkSubpassDescriptionFlags VkFlags

type VkSurfaceCounterFlagBitsEXTFlags VkFlags

const (
	VK_SURFACE_COUNTER_VBLANK_BIT_EXT VkSurfaceCounterFlagBitsEXTFlags = 1 << 0
)

type VkSurfaceTransformFlagBitsKHRFlags VkFlags

const (
	VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR                     VkSurfaceTransformFlagBitsKHRFlags = 1 << 0
	VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR                    VkSurfaceTransformFlagBitsKHRFlags = 1 << 1
	VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR                   VkSurfaceTransformFlagBitsKHRFlags = 1 << 2
	VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR                   VkSurfaceTransformFlagBitsKHRFlags = 1 << 3
	VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR            VkSurfaceTransformFlagBitsKHRFlags = 1 << 4
	VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR  VkSurfaceTransformFlagBitsKHRFlags = 1 << 5
	VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR VkSurfaceTransformFlagBitsKHRFlags = 1 << 6
	VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR VkSurfaceTransformFlagBitsKHRFlags = 1 << 7
	VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR                      VkSurfaceTransformFlagBitsKHRFlags = 1 << 8
)

type VkSwapchainCreateFlagBitsKHRFlags VkFlags

type VkSwapchainImageUsageFlagBitsANDROIDFlags VkFlags

const (
	VK_SWAPCHAIN_IMAGE_USAGE_SHARED_BIT_ANDROID VkSwapchainImageUsageFlagBitsANDROIDFlags = 1 << 0
)

type VkSwapchainImageUsageFlagBitsOHOSFlags VkFlags

const (
	VK_SWAPCHAIN_IMAGE_USAGE_SHARED_BIT_OHOS VkSwapchainImageUsageFlagBitsOHOSFlags = 1 << 0
)

type VkTensorCreateFlagBitsARMFlags VkFlags64

const (
	VK_TENSOR_CREATE_MUTABLE_FORMAT_BIT_ARM VkTensorCreateFlagBitsARMFlags = 1 << 0
	VK_TENSOR_CREATE_PROTECTED_BIT_ARM      VkTensorCreateFlagBitsARMFlags = 1 << 1
)

type VkTensorUsageFlagBitsARMFlags VkFlags64

const (
	/*
		VK_TENSOR_USAGE_SHADER_BIT_ARM Tensor written/read through shader descriptor
	*/
	VK_TENSOR_USAGE_SHADER_BIT_ARM VkTensorUsageFlagBitsARMFlags = 1 << 1

	/*
		VK_TENSOR_USAGE_TRANSFER_SRC_BIT_ARM Tensor can be src of a transfer operation
	*/
	VK_TENSOR_USAGE_TRANSFER_SRC_BIT_ARM VkTensorUsageFlagBitsARMFlags = 1 << 2

	/*
		VK_TENSOR_USAGE_TRANSFER_DST_BIT_ARM Tensor can be dst of a transfer operation
	*/
	VK_TENSOR_USAGE_TRANSFER_DST_BIT_ARM VkTensorUsageFlagBitsARMFlags = 1 << 3

	/*
		VK_TENSOR_USAGE_IMAGE_ALIASING_BIT_ARM Tensor can be aliased with an image
	*/
	VK_TENSOR_USAGE_IMAGE_ALIASING_BIT_ARM VkTensorUsageFlagBitsARMFlags = 1 << 4
)

type VkTensorViewCreateFlagBitsARMFlags VkFlags64

type VkTileShadingRenderPassFlagBitsQCOMFlags VkFlags

const (
	VK_TILE_SHADING_RENDER_PASS_ENABLE_BIT_QCOM             VkTileShadingRenderPassFlagBitsQCOMFlags = 1 << 0
	VK_TILE_SHADING_RENDER_PASS_PER_TILE_EXECUTION_BIT_QCOM VkTileShadingRenderPassFlagBitsQCOMFlags = 1 << 1
)

type VkToolPurposeFlags VkFlags

const (
	VK_TOOL_PURPOSE_VALIDATION_BIT          VkToolPurposeFlags = 1 << 0
	VK_TOOL_PURPOSE_PROFILING_BIT           VkToolPurposeFlags = 1 << 1
	VK_TOOL_PURPOSE_TRACING_BIT             VkToolPurposeFlags = 1 << 2
	VK_TOOL_PURPOSE_ADDITIONAL_FEATURES_BIT VkToolPurposeFlags = 1 << 3
	VK_TOOL_PURPOSE_MODIFYING_FEATURES_BIT  VkToolPurposeFlags = 1 << 4
)

type VkVideoCapabilityFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_CAPABILITY_PROTECTED_CONTENT_BIT_KHR         VkVideoCapabilityFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_CAPABILITY_SEPARATE_REFERENCE_IMAGES_BIT_KHR VkVideoCapabilityFlagBitsKHRFlags = 1 << 1
)

/*
VkVideoChromaSubsamplingFlagBitsKHRFlags Vulkan video chroma subsampling definitions
*/
type VkVideoChromaSubsamplingFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_CHROMA_SUBSAMPLING_INVALID_KHR        VkVideoChromaSubsamplingFlagBitsKHRFlags = 0
	VK_VIDEO_CHROMA_SUBSAMPLING_MONOCHROME_BIT_KHR VkVideoChromaSubsamplingFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_CHROMA_SUBSAMPLING_420_BIT_KHR        VkVideoChromaSubsamplingFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_CHROMA_SUBSAMPLING_422_BIT_KHR        VkVideoChromaSubsamplingFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_CHROMA_SUBSAMPLING_444_BIT_KHR        VkVideoChromaSubsamplingFlagBitsKHRFlags = 1 << 3
)

type VkVideoCodecOperationFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_CODEC_OPERATION_NONE_KHR VkVideoCodecOperationFlagBitsKHRFlags = 0
)

type VkVideoCodingControlFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_CODING_CONTROL_RESET_BIT_KHR VkVideoCodingControlFlagBitsKHRFlags = 1 << 0
)

/*
VkVideoComponentBitDepthFlagBitsKHRFlags Vulkan video component bit depth definitions
*/
type VkVideoComponentBitDepthFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_COMPONENT_BIT_DEPTH_INVALID_KHR VkVideoComponentBitDepthFlagBitsKHRFlags = 0
	VK_VIDEO_COMPONENT_BIT_DEPTH_8_BIT_KHR   VkVideoComponentBitDepthFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_COMPONENT_BIT_DEPTH_10_BIT_KHR  VkVideoComponentBitDepthFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_COMPONENT_BIT_DEPTH_12_BIT_KHR  VkVideoComponentBitDepthFlagBitsKHRFlags = 1 << 4
)

type VkVideoDecodeCapabilityFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_COINCIDE_BIT_KHR VkVideoDecodeCapabilityFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_DISTINCT_BIT_KHR VkVideoDecodeCapabilityFlagBitsKHRFlags = 1 << 1
)

type VkVideoDecodeH264PictureLayoutFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_DECODE_H264_PICTURE_LAYOUT_PROGRESSIVE_KHR                      VkVideoDecodeH264PictureLayoutFlagBitsKHRFlags = 0
	VK_VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_INTERLEAVED_LINES_BIT_KHR VkVideoDecodeH264PictureLayoutFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_SEPARATE_PLANES_BIT_KHR   VkVideoDecodeH264PictureLayoutFlagBitsKHRFlags = 1 << 1
)

type VkVideoDecodeUsageFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_DECODE_USAGE_DEFAULT_KHR         VkVideoDecodeUsageFlagBitsKHRFlags = 0
	VK_VIDEO_DECODE_USAGE_TRANSCODING_BIT_KHR VkVideoDecodeUsageFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_DECODE_USAGE_OFFLINE_BIT_KHR     VkVideoDecodeUsageFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_DECODE_USAGE_STREAMING_BIT_KHR   VkVideoDecodeUsageFlagBitsKHRFlags = 1 << 2
)

type VkVideoEncodeAV1CapabilityFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_AV1_CAPABILITY_PER_RATE_CONTROL_GROUP_MIN_MAX_Q_INDEX_BIT_KHR VkVideoEncodeAV1CapabilityFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_AV1_CAPABILITY_GENERATE_OBU_EXTENSION_HEADER_BIT_KHR          VkVideoEncodeAV1CapabilityFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_AV1_CAPABILITY_PRIMARY_REFERENCE_CDF_ONLY_BIT_KHR             VkVideoEncodeAV1CapabilityFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_AV1_CAPABILITY_FRAME_SIZE_OVERRIDE_BIT_KHR                    VkVideoEncodeAV1CapabilityFlagBitsKHRFlags = 1 << 3
	VK_VIDEO_ENCODE_AV1_CAPABILITY_MOTION_VECTOR_SCALING_BIT_KHR                  VkVideoEncodeAV1CapabilityFlagBitsKHRFlags = 1 << 4
)

type VkVideoEncodeAV1RateControlFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_AV1_RATE_CONTROL_REGULAR_GOP_BIT_KHR                   VkVideoEncodeAV1RateControlFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_AV1_RATE_CONTROL_TEMPORAL_LAYER_PATTERN_DYADIC_BIT_KHR VkVideoEncodeAV1RateControlFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_AV1_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR        VkVideoEncodeAV1RateControlFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_AV1_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR      VkVideoEncodeAV1RateControlFlagBitsKHRFlags = 1 << 3
)

type VkVideoEncodeAV1StdFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_AV1_STD_UNIFORM_TILE_SPACING_FLAG_SET_BIT_KHR VkVideoEncodeAV1StdFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_AV1_STD_SKIP_MODE_PRESENT_UNSET_BIT_KHR       VkVideoEncodeAV1StdFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_AV1_STD_PRIMARY_REF_FRAME_BIT_KHR             VkVideoEncodeAV1StdFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_AV1_STD_DELTA_Q_BIT_KHR                       VkVideoEncodeAV1StdFlagBitsKHRFlags = 1 << 3
)

type VkVideoEncodeAV1SuperblockSizeFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_AV1_SUPERBLOCK_SIZE_64_BIT_KHR  VkVideoEncodeAV1SuperblockSizeFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_AV1_SUPERBLOCK_SIZE_128_BIT_KHR VkVideoEncodeAV1SuperblockSizeFlagBitsKHRFlags = 1 << 1
)

type VkVideoEncodeCapabilityFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_CAPABILITY_PRECEDING_EXTERNALLY_ENCODED_BYTES_BIT_KHR            VkVideoEncodeCapabilityFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_CAPABILITY_INSUFFICIENT_BITSTREAM_BUFFER_RANGE_DETECTION_BIT_KHR VkVideoEncodeCapabilityFlagBitsKHRFlags = 1 << 1
)

type VkVideoEncodeContentFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_CONTENT_DEFAULT_KHR      VkVideoEncodeContentFlagBitsKHRFlags = 0
	VK_VIDEO_ENCODE_CONTENT_CAMERA_BIT_KHR   VkVideoEncodeContentFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_CONTENT_DESKTOP_BIT_KHR  VkVideoEncodeContentFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_CONTENT_RENDERED_BIT_KHR VkVideoEncodeContentFlagBitsKHRFlags = 1 << 2
)

type VkVideoEncodeFeedbackFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_FEEDBACK_BITSTREAM_BUFFER_OFFSET_BIT_KHR VkVideoEncodeFeedbackFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_FEEDBACK_BITSTREAM_BYTES_WRITTEN_BIT_KHR VkVideoEncodeFeedbackFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_FEEDBACK_BITSTREAM_HAS_OVERRIDES_BIT_KHR VkVideoEncodeFeedbackFlagBitsKHRFlags = 1 << 2
)

type VkVideoEncodeFlagBitsKHRFlags VkFlags

type VkVideoEncodeH264CapabilityFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H264_CAPABILITY_HRD_COMPLIANCE_BIT_KHR                    VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H264_CAPABILITY_PREDICTION_WEIGHT_TABLE_GENERATED_BIT_KHR VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H264_CAPABILITY_ROW_UNALIGNED_SLICE_BIT_KHR               VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_H264_CAPABILITY_DIFFERENT_SLICE_TYPE_BIT_KHR              VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 3
	VK_VIDEO_ENCODE_H264_CAPABILITY_B_FRAME_IN_L0_LIST_BIT_KHR                VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 4
	VK_VIDEO_ENCODE_H264_CAPABILITY_B_FRAME_IN_L1_LIST_BIT_KHR                VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 5
	VK_VIDEO_ENCODE_H264_CAPABILITY_PER_PICTURE_TYPE_MIN_MAX_QP_BIT_KHR       VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 6
	VK_VIDEO_ENCODE_H264_CAPABILITY_PER_SLICE_CONSTANT_QP_BIT_KHR             VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 7
	VK_VIDEO_ENCODE_H264_CAPABILITY_GENERATE_PREFIX_NALU_BIT_KHR              VkVideoEncodeH264CapabilityFlagBitsKHRFlags = 1 << 8
)

type VkVideoEncodeH264RateControlFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H264_RATE_CONTROL_ATTEMPT_HRD_COMPLIANCE_BIT_KHR        VkVideoEncodeH264RateControlFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H264_RATE_CONTROL_REGULAR_GOP_BIT_KHR                   VkVideoEncodeH264RateControlFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H264_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR        VkVideoEncodeH264RateControlFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_H264_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR      VkVideoEncodeH264RateControlFlagBitsKHRFlags = 1 << 3
	VK_VIDEO_ENCODE_H264_RATE_CONTROL_TEMPORAL_LAYER_PATTERN_DYADIC_BIT_KHR VkVideoEncodeH264RateControlFlagBitsKHRFlags = 1 << 4
)

type VkVideoEncodeH264StdFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H264_STD_SEPARATE_COLOR_PLANE_FLAG_SET_BIT_KHR            VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H264_STD_QPPRIME_Y_ZERO_TRANSFORM_BYPASS_FLAG_SET_BIT_KHR VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H264_STD_SCALING_MATRIX_PRESENT_FLAG_SET_BIT_KHR          VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_H264_STD_CHROMA_QP_INDEX_OFFSET_BIT_KHR                   VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 3
	VK_VIDEO_ENCODE_H264_STD_SECOND_CHROMA_QP_INDEX_OFFSET_BIT_KHR            VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 4
	VK_VIDEO_ENCODE_H264_STD_PIC_INIT_QP_MINUS26_BIT_KHR                      VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 5
	VK_VIDEO_ENCODE_H264_STD_WEIGHTED_PRED_FLAG_SET_BIT_KHR                   VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 6
	VK_VIDEO_ENCODE_H264_STD_WEIGHTED_BIPRED_IDC_EXPLICIT_BIT_KHR             VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 7
	VK_VIDEO_ENCODE_H264_STD_WEIGHTED_BIPRED_IDC_IMPLICIT_BIT_KHR             VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 8
	VK_VIDEO_ENCODE_H264_STD_TRANSFORM_8X8_MODE_FLAG_SET_BIT_KHR              VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 9
	VK_VIDEO_ENCODE_H264_STD_DIRECT_SPATIAL_MV_PRED_FLAG_UNSET_BIT_KHR        VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 10
	VK_VIDEO_ENCODE_H264_STD_ENTROPY_CODING_MODE_FLAG_UNSET_BIT_KHR           VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 11
	VK_VIDEO_ENCODE_H264_STD_ENTROPY_CODING_MODE_FLAG_SET_BIT_KHR             VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 12
	VK_VIDEO_ENCODE_H264_STD_DIRECT_8X8_INFERENCE_FLAG_UNSET_BIT_KHR          VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 13
	VK_VIDEO_ENCODE_H264_STD_CONSTRAINED_INTRA_PRED_FLAG_SET_BIT_KHR          VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 14
	VK_VIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_DISABLED_BIT_KHR               VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 15
	VK_VIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_ENABLED_BIT_KHR                VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 16
	VK_VIDEO_ENCODE_H264_STD_DEBLOCKING_FILTER_PARTIAL_BIT_KHR                VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 17
	VK_VIDEO_ENCODE_H264_STD_SLICE_QP_DELTA_BIT_KHR                           VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 19
	VK_VIDEO_ENCODE_H264_STD_DIFFERENT_SLICE_QP_DELTA_BIT_KHR                 VkVideoEncodeH264StdFlagBitsKHRFlags = 1 << 20
)

type VkVideoEncodeH265CapabilityFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H265_CAPABILITY_HRD_COMPLIANCE_BIT_KHR                    VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H265_CAPABILITY_PREDICTION_WEIGHT_TABLE_GENERATED_BIT_KHR VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H265_CAPABILITY_ROW_UNALIGNED_SLICE_SEGMENT_BIT_KHR       VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_H265_CAPABILITY_DIFFERENT_SLICE_SEGMENT_TYPE_BIT_KHR      VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 3
	VK_VIDEO_ENCODE_H265_CAPABILITY_B_FRAME_IN_L0_LIST_BIT_KHR                VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 4
	VK_VIDEO_ENCODE_H265_CAPABILITY_B_FRAME_IN_L1_LIST_BIT_KHR                VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 5
	VK_VIDEO_ENCODE_H265_CAPABILITY_PER_PICTURE_TYPE_MIN_MAX_QP_BIT_KHR       VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 6
	VK_VIDEO_ENCODE_H265_CAPABILITY_PER_SLICE_SEGMENT_CONSTANT_QP_BIT_KHR     VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 7
	VK_VIDEO_ENCODE_H265_CAPABILITY_MULTIPLE_TILES_PER_SLICE_SEGMENT_BIT_KHR  VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 8
	VK_VIDEO_ENCODE_H265_CAPABILITY_MULTIPLE_SLICE_SEGMENTS_PER_TILE_BIT_KHR  VkVideoEncodeH265CapabilityFlagBitsKHRFlags = 1 << 9
)

type VkVideoEncodeH265CtbSizeFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H265_CTB_SIZE_16_BIT_KHR VkVideoEncodeH265CtbSizeFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H265_CTB_SIZE_32_BIT_KHR VkVideoEncodeH265CtbSizeFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H265_CTB_SIZE_64_BIT_KHR VkVideoEncodeH265CtbSizeFlagBitsKHRFlags = 1 << 2
)

type VkVideoEncodeH265RateControlFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H265_RATE_CONTROL_ATTEMPT_HRD_COMPLIANCE_BIT_KHR            VkVideoEncodeH265RateControlFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H265_RATE_CONTROL_REGULAR_GOP_BIT_KHR                       VkVideoEncodeH265RateControlFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H265_RATE_CONTROL_REFERENCE_PATTERN_FLAT_BIT_KHR            VkVideoEncodeH265RateControlFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_H265_RATE_CONTROL_REFERENCE_PATTERN_DYADIC_BIT_KHR          VkVideoEncodeH265RateControlFlagBitsKHRFlags = 1 << 3
	VK_VIDEO_ENCODE_H265_RATE_CONTROL_TEMPORAL_SUB_LAYER_PATTERN_DYADIC_BIT_KHR VkVideoEncodeH265RateControlFlagBitsKHRFlags = 1 << 4
)

type VkVideoEncodeH265StdFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H265_STD_SEPARATE_COLOR_PLANE_FLAG_SET_BIT_KHR                VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H265_STD_SAMPLE_ADAPTIVE_OFFSET_ENABLED_FLAG_SET_BIT_KHR      VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H265_STD_SCALING_LIST_DATA_PRESENT_FLAG_SET_BIT_KHR           VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_H265_STD_PCM_ENABLED_FLAG_SET_BIT_KHR                         VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 3
	VK_VIDEO_ENCODE_H265_STD_SPS_TEMPORAL_MVP_ENABLED_FLAG_SET_BIT_KHR            VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 4
	VK_VIDEO_ENCODE_H265_STD_INIT_QP_MINUS26_BIT_KHR                              VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 5
	VK_VIDEO_ENCODE_H265_STD_WEIGHTED_PRED_FLAG_SET_BIT_KHR                       VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 6
	VK_VIDEO_ENCODE_H265_STD_WEIGHTED_BIPRED_FLAG_SET_BIT_KHR                     VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 7
	VK_VIDEO_ENCODE_H265_STD_LOG2_PARALLEL_MERGE_LEVEL_MINUS2_BIT_KHR             VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 8
	VK_VIDEO_ENCODE_H265_STD_SIGN_DATA_HIDING_ENABLED_FLAG_SET_BIT_KHR            VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 9
	VK_VIDEO_ENCODE_H265_STD_TRANSFORM_SKIP_ENABLED_FLAG_SET_BIT_KHR              VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 10
	VK_VIDEO_ENCODE_H265_STD_TRANSFORM_SKIP_ENABLED_FLAG_UNSET_BIT_KHR            VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 11
	VK_VIDEO_ENCODE_H265_STD_PPS_SLICE_CHROMA_QP_OFFSETS_PRESENT_FLAG_SET_BIT_KHR VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 12
	VK_VIDEO_ENCODE_H265_STD_TRANSQUANT_BYPASS_ENABLED_FLAG_SET_BIT_KHR           VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 13
	VK_VIDEO_ENCODE_H265_STD_CONSTRAINED_INTRA_PRED_FLAG_SET_BIT_KHR              VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 14
	VK_VIDEO_ENCODE_H265_STD_ENTROPY_CODING_SYNC_ENABLED_FLAG_SET_BIT_KHR         VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 15
	VK_VIDEO_ENCODE_H265_STD_DEBLOCKING_FILTER_OVERRIDE_ENABLED_FLAG_SET_BIT_KHR  VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 16
	VK_VIDEO_ENCODE_H265_STD_DEPENDENT_SLICE_SEGMENTS_ENABLED_FLAG_SET_BIT_KHR    VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 17
	VK_VIDEO_ENCODE_H265_STD_DEPENDENT_SLICE_SEGMENT_FLAG_SET_BIT_KHR             VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 18
	VK_VIDEO_ENCODE_H265_STD_SLICE_QP_DELTA_BIT_KHR                               VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 19
	VK_VIDEO_ENCODE_H265_STD_DIFFERENT_SLICE_QP_DELTA_BIT_KHR                     VkVideoEncodeH265StdFlagBitsKHRFlags = 1 << 20
)

type VkVideoEncodeH265TransformBlockSizeFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_4_BIT_KHR  VkVideoEncodeH265TransformBlockSizeFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_8_BIT_KHR  VkVideoEncodeH265TransformBlockSizeFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_16_BIT_KHR VkVideoEncodeH265TransformBlockSizeFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_H265_TRANSFORM_BLOCK_SIZE_32_BIT_KHR VkVideoEncodeH265TransformBlockSizeFlagBitsKHRFlags = 1 << 3
)

type VkVideoEncodeIntraRefreshModeFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_INTRA_REFRESH_MODE_NONE_KHR                      VkVideoEncodeIntraRefreshModeFlagBitsKHRFlags = 0
	VK_VIDEO_ENCODE_INTRA_REFRESH_MODE_PER_PICTURE_PARTITION_BIT_KHR VkVideoEncodeIntraRefreshModeFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_BASED_BIT_KHR           VkVideoEncodeIntraRefreshModeFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_ROW_BASED_BIT_KHR       VkVideoEncodeIntraRefreshModeFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_INTRA_REFRESH_MODE_BLOCK_COLUMN_BASED_BIT_KHR    VkVideoEncodeIntraRefreshModeFlagBitsKHRFlags = 1 << 3
)

type VkVideoEncodeRateControlModeFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_RATE_CONTROL_MODE_DEFAULT_KHR      VkVideoEncodeRateControlModeFlagBitsKHRFlags = 0
	VK_VIDEO_ENCODE_RATE_CONTROL_MODE_DISABLED_BIT_KHR VkVideoEncodeRateControlModeFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR      VkVideoEncodeRateControlModeFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR      VkVideoEncodeRateControlModeFlagBitsKHRFlags = 1 << 2
)

type VkVideoEncodeRgbChromaOffsetFlagBitsVALVEFlags VkFlags

const (
	VK_VIDEO_ENCODE_RGB_CHROMA_OFFSET_COSITED_EVEN_BIT_VALVE VkVideoEncodeRgbChromaOffsetFlagBitsVALVEFlags = 1 << 0
	VK_VIDEO_ENCODE_RGB_CHROMA_OFFSET_MIDPOINT_BIT_VALVE     VkVideoEncodeRgbChromaOffsetFlagBitsVALVEFlags = 1 << 1
)

type VkVideoEncodeRgbModelConversionFlagBitsVALVEFlags VkFlags

const (
	VK_VIDEO_ENCODE_RGB_MODEL_CONVERSION_RGB_IDENTITY_BIT_VALVE   VkVideoEncodeRgbModelConversionFlagBitsVALVEFlags = 1 << 0
	VK_VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_IDENTITY_BIT_VALVE VkVideoEncodeRgbModelConversionFlagBitsVALVEFlags = 1 << 1
	VK_VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_709_BIT_VALVE      VkVideoEncodeRgbModelConversionFlagBitsVALVEFlags = 1 << 2
	VK_VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_601_BIT_VALVE      VkVideoEncodeRgbModelConversionFlagBitsVALVEFlags = 1 << 3
	VK_VIDEO_ENCODE_RGB_MODEL_CONVERSION_YCBCR_2020_BIT_VALVE     VkVideoEncodeRgbModelConversionFlagBitsVALVEFlags = 1 << 4
)

type VkVideoEncodeRgbRangeCompressionFlagBitsVALVEFlags VkFlags

const (
	VK_VIDEO_ENCODE_RGB_RANGE_COMPRESSION_FULL_RANGE_BIT_VALVE   VkVideoEncodeRgbRangeCompressionFlagBitsVALVEFlags = 1 << 0
	VK_VIDEO_ENCODE_RGB_RANGE_COMPRESSION_NARROW_RANGE_BIT_VALVE VkVideoEncodeRgbRangeCompressionFlagBitsVALVEFlags = 1 << 1
)

type VkVideoEncodeUsageFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_ENCODE_USAGE_DEFAULT_KHR          VkVideoEncodeUsageFlagBitsKHRFlags = 0
	VK_VIDEO_ENCODE_USAGE_TRANSCODING_BIT_KHR  VkVideoEncodeUsageFlagBitsKHRFlags = 1 << 0
	VK_VIDEO_ENCODE_USAGE_STREAMING_BIT_KHR    VkVideoEncodeUsageFlagBitsKHRFlags = 1 << 1
	VK_VIDEO_ENCODE_USAGE_RECORDING_BIT_KHR    VkVideoEncodeUsageFlagBitsKHRFlags = 1 << 2
	VK_VIDEO_ENCODE_USAGE_CONFERENCING_BIT_KHR VkVideoEncodeUsageFlagBitsKHRFlags = 1 << 3
)

type VkVideoSessionCreateFlagBitsKHRFlags VkFlags

const (
	VK_VIDEO_SESSION_CREATE_PROTECTED_CONTENT_BIT_KHR VkVideoSessionCreateFlagBitsKHRFlags = 1 << 0
)

type VkVideoSessionParametersCreateFlagBitsKHRFlags VkFlags

type VkWaylandSurfaceCreateFlagBitsKHRFlags VkFlags
