// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-22 19:38:37 CEST

package bindings

/*
VkEnum is the base type for Vulkan enumerated types in the registry.
*/
type VkEnum = int32

type VkAccelerationStructureBuildTypeKHR VkEnum
const (
	VK_ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_KHR VkAccelerationStructureBuildTypeKHR = 0
	VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR VkAccelerationStructureBuildTypeKHR = 1
	VK_ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_OR_DEVICE_KHR VkAccelerationStructureBuildTypeKHR = 2
)

type VkAccelerationStructureCompatibilityKHR VkEnum
const (
	VK_ACCELERATION_STRUCTURE_COMPATIBILITY_COMPATIBLE_KHR VkAccelerationStructureCompatibilityKHR = 0
	VK_ACCELERATION_STRUCTURE_COMPATIBILITY_INCOMPATIBLE_KHR VkAccelerationStructureCompatibilityKHR = 1
)

type VkAccelerationStructureMemoryRequirementsTypeNV VkEnum
const (
	VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_OBJECT_NV VkAccelerationStructureMemoryRequirementsTypeNV = 0
	VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_NV VkAccelerationStructureMemoryRequirementsTypeNV = 1
	VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_UPDATE_SCRATCH_NV VkAccelerationStructureMemoryRequirementsTypeNV = 2
)

type VkAccelerationStructureMotionInstanceTypeNV VkEnum
const (
	VK_ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_STATIC_NV VkAccelerationStructureMotionInstanceTypeNV = 0
	VK_ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_MATRIX_MOTION_NV VkAccelerationStructureMotionInstanceTypeNV = 1
	VK_ACCELERATION_STRUCTURE_MOTION_INSTANCE_TYPE_SRT_MOTION_NV VkAccelerationStructureMotionInstanceTypeNV = 2
)

type VkAccelerationStructureSerializedBlockTypeKHR VkEnum
const (
	VK_ACCELERATION_STRUCTURE_SERIALIZED_BLOCK_TYPE_OPACITY_MICROMAP_KHR VkAccelerationStructureSerializedBlockTypeKHR = 0
)

type VkAccelerationStructureTypeKHR VkEnum
const (
	VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR VkAccelerationStructureTypeKHR = 0
	VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR VkAccelerationStructureTypeKHR = 1
	VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR VkAccelerationStructureTypeKHR = 2
)

type VkAntiLagModeAMD VkEnum
const (
	VK_ANTI_LAG_MODE_DRIVER_CONTROL_AMD VkAntiLagModeAMD = 0
	VK_ANTI_LAG_MODE_ON_AMD VkAntiLagModeAMD = 1
	VK_ANTI_LAG_MODE_OFF_AMD VkAntiLagModeAMD = 2
)

type VkAntiLagStageAMD VkEnum
const (
	VK_ANTI_LAG_STAGE_INPUT_AMD VkAntiLagStageAMD = 0
	VK_ANTI_LAG_STAGE_PRESENT_AMD VkAntiLagStageAMD = 1
)

type VkAttachmentLoadOp VkEnum
const (
	VK_ATTACHMENT_LOAD_OP_LOAD VkAttachmentLoadOp = 0
	VK_ATTACHMENT_LOAD_OP_CLEAR VkAttachmentLoadOp = 1
	VK_ATTACHMENT_LOAD_OP_DONT_CARE VkAttachmentLoadOp = 2
)

type VkAttachmentStoreOp VkEnum
const (
	VK_ATTACHMENT_STORE_OP_STORE VkAttachmentStoreOp = 0
	VK_ATTACHMENT_STORE_OP_DONT_CARE VkAttachmentStoreOp = 1
)

type VkBlendFactor VkEnum
const (
	VK_BLEND_FACTOR_ZERO VkBlendFactor = 0
	VK_BLEND_FACTOR_ONE VkBlendFactor = 1
	VK_BLEND_FACTOR_SRC_COLOR VkBlendFactor = 2
	VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR VkBlendFactor = 3
	VK_BLEND_FACTOR_DST_COLOR VkBlendFactor = 4
	VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR VkBlendFactor = 5
	VK_BLEND_FACTOR_SRC_ALPHA VkBlendFactor = 6
	VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA VkBlendFactor = 7
	VK_BLEND_FACTOR_DST_ALPHA VkBlendFactor = 8
	VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA VkBlendFactor = 9
	VK_BLEND_FACTOR_CONSTANT_COLOR VkBlendFactor = 10
	VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR VkBlendFactor = 11
	VK_BLEND_FACTOR_CONSTANT_ALPHA VkBlendFactor = 12
	VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA VkBlendFactor = 13
	VK_BLEND_FACTOR_SRC_ALPHA_SATURATE VkBlendFactor = 14
	VK_BLEND_FACTOR_SRC1_COLOR VkBlendFactor = 15
	VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR VkBlendFactor = 16
	VK_BLEND_FACTOR_SRC1_ALPHA VkBlendFactor = 17
	VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA VkBlendFactor = 18
)

type VkBlendOp VkEnum
const (
	VK_BLEND_OP_ADD VkBlendOp = 0
	VK_BLEND_OP_SUBTRACT VkBlendOp = 1
	VK_BLEND_OP_REVERSE_SUBTRACT VkBlendOp = 2
	VK_BLEND_OP_MIN VkBlendOp = 3
	VK_BLEND_OP_MAX VkBlendOp = 4
)

type VkBlendOverlapEXT VkEnum
const (
	VK_BLEND_OVERLAP_UNCORRELATED_EXT VkBlendOverlapEXT = 0
	VK_BLEND_OVERLAP_DISJOINT_EXT VkBlendOverlapEXT = 1
	VK_BLEND_OVERLAP_CONJOINT_EXT VkBlendOverlapEXT = 2
)

type VkBlockMatchWindowCompareModeQCOM VkEnum
const (
	VK_BLOCK_MATCH_WINDOW_COMPARE_MODE_MIN_QCOM VkBlockMatchWindowCompareModeQCOM = 0
	VK_BLOCK_MATCH_WINDOW_COMPARE_MODE_MAX_QCOM VkBlockMatchWindowCompareModeQCOM = 1
)

type VkBorderColor VkEnum
const (
	VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK VkBorderColor = 0
	VK_BORDER_COLOR_INT_TRANSPARENT_BLACK VkBorderColor = 1
	VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK VkBorderColor = 2
	VK_BORDER_COLOR_INT_OPAQUE_BLACK VkBorderColor = 3
	VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE VkBorderColor = 4
	VK_BORDER_COLOR_INT_OPAQUE_WHITE VkBorderColor = 5
)

type VkBuildAccelerationStructureModeKHR VkEnum
const (
	VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR VkBuildAccelerationStructureModeKHR = 0
	VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR VkBuildAccelerationStructureModeKHR = 1
)

type VkBuildMicromapModeEXT VkEnum
const (
	VK_BUILD_MICROMAP_MODE_BUILD_EXT VkBuildMicromapModeEXT = 0
)

type VkChromaLocation VkEnum
const (
	VK_CHROMA_LOCATION_COSITED_EVEN VkChromaLocation = 0
	VK_CHROMA_LOCATION_MIDPOINT VkChromaLocation = 1
)

type VkClusterAccelerationStructureOpModeNV VkEnum
const (
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_MODE_IMPLICIT_DESTINATIONS_NV VkClusterAccelerationStructureOpModeNV = 0
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_MODE_EXPLICIT_DESTINATIONS_NV VkClusterAccelerationStructureOpModeNV = 1
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_MODE_COMPUTE_SIZES_NV VkClusterAccelerationStructureOpModeNV = 2
)

type VkClusterAccelerationStructureOpTypeNV VkEnum
const (
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_MOVE_OBJECTS_NV VkClusterAccelerationStructureOpTypeNV = 0
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_CLUSTERS_BOTTOM_LEVEL_NV VkClusterAccelerationStructureOpTypeNV = 1
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_TRIANGLE_CLUSTER_NV VkClusterAccelerationStructureOpTypeNV = 2
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_BUILD_TRIANGLE_CLUSTER_TEMPLATE_NV VkClusterAccelerationStructureOpTypeNV = 3
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_INSTANTIATE_TRIANGLE_CLUSTER_NV VkClusterAccelerationStructureOpTypeNV = 4
	VK_CLUSTER_ACCELERATION_STRUCTURE_OP_TYPE_GET_CLUSTER_TEMPLATE_INDICES_NV VkClusterAccelerationStructureOpTypeNV = 5
)

type VkClusterAccelerationStructureTypeNV VkEnum
const (
	VK_CLUSTER_ACCELERATION_STRUCTURE_TYPE_CLUSTERS_BOTTOM_LEVEL_NV VkClusterAccelerationStructureTypeNV = 0
	VK_CLUSTER_ACCELERATION_STRUCTURE_TYPE_TRIANGLE_CLUSTER_NV VkClusterAccelerationStructureTypeNV = 1
	VK_CLUSTER_ACCELERATION_STRUCTURE_TYPE_TRIANGLE_CLUSTER_TEMPLATE_NV VkClusterAccelerationStructureTypeNV = 2
)

type VkCoarseSampleOrderTypeNV VkEnum
const (
	VK_COARSE_SAMPLE_ORDER_TYPE_DEFAULT_NV VkCoarseSampleOrderTypeNV = 0
	VK_COARSE_SAMPLE_ORDER_TYPE_CUSTOM_NV VkCoarseSampleOrderTypeNV = 1
	VK_COARSE_SAMPLE_ORDER_TYPE_PIXEL_MAJOR_NV VkCoarseSampleOrderTypeNV = 2
	VK_COARSE_SAMPLE_ORDER_TYPE_SAMPLE_MAJOR_NV VkCoarseSampleOrderTypeNV = 3
)

type VkColorSpaceKHR VkEnum
const (
	VK_COLOR_SPACE_SRGB_NONLINEAR_KHR VkColorSpaceKHR = 0
)

type VkCommandBufferLevel VkEnum
const (
	VK_COMMAND_BUFFER_LEVEL_PRIMARY VkCommandBufferLevel = 0
	VK_COMMAND_BUFFER_LEVEL_SECONDARY VkCommandBufferLevel = 1
)

type VkCompareOp VkEnum
const (
	VK_COMPARE_OP_NEVER VkCompareOp = 0
	VK_COMPARE_OP_LESS VkCompareOp = 1
	VK_COMPARE_OP_EQUAL VkCompareOp = 2
	VK_COMPARE_OP_LESS_OR_EQUAL VkCompareOp = 3
	VK_COMPARE_OP_GREATER VkCompareOp = 4
	VK_COMPARE_OP_NOT_EQUAL VkCompareOp = 5
	VK_COMPARE_OP_GREATER_OR_EQUAL VkCompareOp = 6
	VK_COMPARE_OP_ALWAYS VkCompareOp = 7
)

type VkComponentSwizzle VkEnum
const (
	VK_COMPONENT_SWIZZLE_IDENTITY VkComponentSwizzle = 0
	VK_COMPONENT_SWIZZLE_ZERO VkComponentSwizzle = 1
	VK_COMPONENT_SWIZZLE_ONE VkComponentSwizzle = 2
	VK_COMPONENT_SWIZZLE_R VkComponentSwizzle = 3
	VK_COMPONENT_SWIZZLE_G VkComponentSwizzle = 4
	VK_COMPONENT_SWIZZLE_B VkComponentSwizzle = 5
	VK_COMPONENT_SWIZZLE_A VkComponentSwizzle = 6
)

type VkComponentTypeKHR VkEnum
const (
	VK_COMPONENT_TYPE_FLOAT16_KHR VkComponentTypeKHR = 0
	VK_COMPONENT_TYPE_FLOAT32_KHR VkComponentTypeKHR = 1
	VK_COMPONENT_TYPE_FLOAT64_KHR VkComponentTypeKHR = 2
	VK_COMPONENT_TYPE_SINT8_KHR VkComponentTypeKHR = 3
	VK_COMPONENT_TYPE_SINT16_KHR VkComponentTypeKHR = 4
	VK_COMPONENT_TYPE_SINT32_KHR VkComponentTypeKHR = 5
	VK_COMPONENT_TYPE_SINT64_KHR VkComponentTypeKHR = 6
	VK_COMPONENT_TYPE_UINT8_KHR VkComponentTypeKHR = 7
	VK_COMPONENT_TYPE_UINT16_KHR VkComponentTypeKHR = 8
	VK_COMPONENT_TYPE_UINT32_KHR VkComponentTypeKHR = 9
	VK_COMPONENT_TYPE_UINT64_KHR VkComponentTypeKHR = 10
)

type VkCompressedTriangleFormatAMDX VkEnum
const (
	VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_AMDX VkCompressedTriangleFormatAMDX = 0
)

type VkConservativeRasterizationModeEXT VkEnum
const (
	VK_CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT VkConservativeRasterizationModeEXT = 0
	VK_CONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXT VkConservativeRasterizationModeEXT = 1
	VK_CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT VkConservativeRasterizationModeEXT = 2
)

type VkCooperativeVectorMatrixLayoutNV VkEnum
const (
	VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_ROW_MAJOR_NV VkCooperativeVectorMatrixLayoutNV = 0
	VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_COLUMN_MAJOR_NV VkCooperativeVectorMatrixLayoutNV = 1
	VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_INFERENCING_OPTIMAL_NV VkCooperativeVectorMatrixLayoutNV = 2
	VK_COOPERATIVE_VECTOR_MATRIX_LAYOUT_TRAINING_OPTIMAL_NV VkCooperativeVectorMatrixLayoutNV = 3
)

type VkCopyAccelerationStructureModeKHR VkEnum
const (
	VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR VkCopyAccelerationStructureModeKHR = 0
	VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_KHR VkCopyAccelerationStructureModeKHR = 1
)

type VkCopyMicromapModeEXT VkEnum
const (
	VK_COPY_MICROMAP_MODE_CLONE_EXT VkCopyMicromapModeEXT = 0
	VK_COPY_MICROMAP_MODE_SERIALIZE_EXT VkCopyMicromapModeEXT = 1
	VK_COPY_MICROMAP_MODE_DESERIALIZE_EXT VkCopyMicromapModeEXT = 2
	VK_COPY_MICROMAP_MODE_COMPACT_EXT VkCopyMicromapModeEXT = 3
)

type VkCoverageModulationModeNV VkEnum
const (
	VK_COVERAGE_MODULATION_MODE_NONE_NV VkCoverageModulationModeNV = 0
	VK_COVERAGE_MODULATION_MODE_RGB_NV VkCoverageModulationModeNV = 1
	VK_COVERAGE_MODULATION_MODE_ALPHA_NV VkCoverageModulationModeNV = 2
	VK_COVERAGE_MODULATION_MODE_RGBA_NV VkCoverageModulationModeNV = 3
)

type VkCoverageReductionModeNV VkEnum
const (
	VK_COVERAGE_REDUCTION_MODE_MERGE_NV VkCoverageReductionModeNV = 0
	VK_COVERAGE_REDUCTION_MODE_TRUNCATE_NV VkCoverageReductionModeNV = 1
)

type VkCubicFilterWeightsQCOM VkEnum
const (
	VK_CUBIC_FILTER_WEIGHTS_CATMULL_ROM_QCOM VkCubicFilterWeightsQCOM = 0
	VK_CUBIC_FILTER_WEIGHTS_ZERO_TANGENT_CARDINAL_QCOM VkCubicFilterWeightsQCOM = 1
	VK_CUBIC_FILTER_WEIGHTS_B_SPLINE_QCOM VkCubicFilterWeightsQCOM = 2
	VK_CUBIC_FILTER_WEIGHTS_MITCHELL_NETRAVALI_QCOM VkCubicFilterWeightsQCOM = 3
)

type VkDataGraphModelCacheTypeQCOM VkEnum
const (
	VK_DATA_GRAPH_MODEL_CACHE_TYPE_GENERIC_BINARY_QCOM VkDataGraphModelCacheTypeQCOM = 0
)

type VkDataGraphOpticalFlowPerformanceLevelARM VkEnum
const (
	VK_DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_UNKNOWN_ARM VkDataGraphOpticalFlowPerformanceLevelARM = 0
	VK_DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_SLOW_ARM VkDataGraphOpticalFlowPerformanceLevelARM = 1
	VK_DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_MEDIUM_ARM VkDataGraphOpticalFlowPerformanceLevelARM = 2
	VK_DATA_GRAPH_OPTICAL_FLOW_PERFORMANCE_LEVEL_FAST_ARM VkDataGraphOpticalFlowPerformanceLevelARM = 3
)

type VkDataGraphPipelinePropertyARM VkEnum
const (
	VK_DATA_GRAPH_PIPELINE_PROPERTY_CREATION_LOG_ARM VkDataGraphPipelinePropertyARM = 0
	VK_DATA_GRAPH_PIPELINE_PROPERTY_IDENTIFIER_ARM VkDataGraphPipelinePropertyARM = 1
)

type VkDataGraphPipelineSessionBindPointARM VkEnum
const (
	VK_DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_TRANSIENT_ARM VkDataGraphPipelineSessionBindPointARM = 0
)

type VkDataGraphPipelineSessionBindPointTypeARM VkEnum
const (
	VK_DATA_GRAPH_PIPELINE_SESSION_BIND_POINT_TYPE_MEMORY_ARM VkDataGraphPipelineSessionBindPointTypeARM = 0
)

type VkDataGraphTOSALevelARM VkEnum
const (
	VK_DATA_GRAPH_TOSA_LEVEL_NONE_ARM VkDataGraphTOSALevelARM = 0
	VK_DATA_GRAPH_TOSA_LEVEL_8K_ARM VkDataGraphTOSALevelARM = 1
)

type VkDebugReportObjectTypeEXT VkEnum
const (
	VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT VkDebugReportObjectTypeEXT = 0
	VK_DEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXT VkDebugReportObjectTypeEXT = 1
	VK_DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT VkDebugReportObjectTypeEXT = 2
	VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT VkDebugReportObjectTypeEXT = 3
	VK_DEBUG_REPORT_OBJECT_TYPE_QUEUE_EXT VkDebugReportObjectTypeEXT = 4
	VK_DEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXT VkDebugReportObjectTypeEXT = 5
	VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT VkDebugReportObjectTypeEXT = 6
	VK_DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT VkDebugReportObjectTypeEXT = 7
	VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT VkDebugReportObjectTypeEXT = 8
	VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT VkDebugReportObjectTypeEXT = 9
	VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT VkDebugReportObjectTypeEXT = 10
	VK_DEBUG_REPORT_OBJECT_TYPE_EVENT_EXT VkDebugReportObjectTypeEXT = 11
	VK_DEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXT VkDebugReportObjectTypeEXT = 12
	VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXT VkDebugReportObjectTypeEXT = 13
	VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXT VkDebugReportObjectTypeEXT = 14
	VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT VkDebugReportObjectTypeEXT = 15
	VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXT VkDebugReportObjectTypeEXT = 16
	VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXT VkDebugReportObjectTypeEXT = 17
	VK_DEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXT VkDebugReportObjectTypeEXT = 18
	VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT VkDebugReportObjectTypeEXT = 19
	VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXT VkDebugReportObjectTypeEXT = 20
	VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXT VkDebugReportObjectTypeEXT = 21
	VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXT VkDebugReportObjectTypeEXT = 22
	VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT VkDebugReportObjectTypeEXT = 23
	VK_DEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXT VkDebugReportObjectTypeEXT = 24
	VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT VkDebugReportObjectTypeEXT = 25
	VK_DEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXT VkDebugReportObjectTypeEXT = 26
	VK_DEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXT VkDebugReportObjectTypeEXT = 27
	VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT VkDebugReportObjectTypeEXT = 28
	VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT VkDebugReportObjectTypeEXT = 29
	VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT VkDebugReportObjectTypeEXT = 30

	/*
	VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT NVX_device_generated_commands formerly used these enum values, but that extension has been removed
	                value 31 / name VK_DEBUG_REPORT_OBJECT_TYPE_OBJECT_TABLE_NVX_EXT
	                value 32 / name VK_DEBUG_REPORT_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX_EXT
	*/
	VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT VkDebugReportObjectTypeEXT = 33
)

type VkDefaultVertexAttributeValueKHR VkEnum
const (
	VK_DEFAULT_VERTEX_ATTRIBUTE_VALUE_ZERO_ZERO_ZERO_ZERO_KHR VkDefaultVertexAttributeValueKHR = 0
	VK_DEFAULT_VERTEX_ATTRIBUTE_VALUE_ZERO_ZERO_ZERO_ONE_KHR VkDefaultVertexAttributeValueKHR = 1
)

type VkDepthBiasRepresentationEXT VkEnum
const (
	VK_DEPTH_BIAS_REPRESENTATION_LEAST_REPRESENTABLE_VALUE_FORMAT_EXT VkDepthBiasRepresentationEXT = 0
	VK_DEPTH_BIAS_REPRESENTATION_LEAST_REPRESENTABLE_VALUE_FORCE_UNORM_EXT VkDepthBiasRepresentationEXT = 1
	VK_DEPTH_BIAS_REPRESENTATION_FLOAT_EXT VkDepthBiasRepresentationEXT = 2
)

type VkDepthClampModeEXT VkEnum
const (
	VK_DEPTH_CLAMP_MODE_VIEWPORT_RANGE_EXT VkDepthClampModeEXT = 0
	VK_DEPTH_CLAMP_MODE_USER_DEFINED_RANGE_EXT VkDepthClampModeEXT = 1
)

type VkDescriptorMappingSourceEXT VkEnum
const (
	VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_CONSTANT_OFFSET_EXT VkDescriptorMappingSourceEXT = 0
	VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_PUSH_INDEX_EXT VkDescriptorMappingSourceEXT = 1
	VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_INDIRECT_INDEX_EXT VkDescriptorMappingSourceEXT = 2
	VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_INDIRECT_INDEX_ARRAY_EXT VkDescriptorMappingSourceEXT = 3
	VK_DESCRIPTOR_MAPPING_SOURCE_RESOURCE_HEAP_DATA_EXT VkDescriptorMappingSourceEXT = 4
	VK_DESCRIPTOR_MAPPING_SOURCE_PUSH_DATA_EXT VkDescriptorMappingSourceEXT = 5
	VK_DESCRIPTOR_MAPPING_SOURCE_PUSH_ADDRESS_EXT VkDescriptorMappingSourceEXT = 6
	VK_DESCRIPTOR_MAPPING_SOURCE_INDIRECT_ADDRESS_EXT VkDescriptorMappingSourceEXT = 7
)

type VkDescriptorType VkEnum
const (
	VK_DESCRIPTOR_TYPE_SAMPLER VkDescriptorType = 0
	VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER VkDescriptorType = 1
	VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE VkDescriptorType = 2
	VK_DESCRIPTOR_TYPE_STORAGE_IMAGE VkDescriptorType = 3
	VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER VkDescriptorType = 4
	VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER VkDescriptorType = 5
	VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER VkDescriptorType = 6
	VK_DESCRIPTOR_TYPE_STORAGE_BUFFER VkDescriptorType = 7
	VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC VkDescriptorType = 8
	VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC VkDescriptorType = 9
	VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT VkDescriptorType = 10
)

type VkDescriptorUpdateTemplateType VkEnum
const (
	/*
	VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET Create descriptor update template for descriptor set updates
	*/
	VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET VkDescriptorUpdateTemplateType = 0
)

type VkDeviceAddressBindingTypeEXT VkEnum
const (
	VK_DEVICE_ADDRESS_BINDING_TYPE_BIND_EXT VkDeviceAddressBindingTypeEXT = 0
	VK_DEVICE_ADDRESS_BINDING_TYPE_UNBIND_EXT VkDeviceAddressBindingTypeEXT = 1
)

type VkDeviceEventTypeEXT VkEnum
const (
	VK_DEVICE_EVENT_TYPE_DISPLAY_HOTPLUG_EXT VkDeviceEventTypeEXT = 0
)

type VkDeviceFaultAddressTypeKHR VkEnum
const (
	/*
	VK_DEVICE_FAULT_ADDRESS_TYPE_NONE_KHR Currently unused
	*/
	VK_DEVICE_FAULT_ADDRESS_TYPE_NONE_KHR VkDeviceFaultAddressTypeKHR = 0
	VK_DEVICE_FAULT_ADDRESS_TYPE_READ_INVALID_KHR VkDeviceFaultAddressTypeKHR = 1
	VK_DEVICE_FAULT_ADDRESS_TYPE_WRITE_INVALID_KHR VkDeviceFaultAddressTypeKHR = 2
	VK_DEVICE_FAULT_ADDRESS_TYPE_EXECUTE_INVALID_KHR VkDeviceFaultAddressTypeKHR = 3
	VK_DEVICE_FAULT_ADDRESS_TYPE_INSTRUCTION_POINTER_UNKNOWN_KHR VkDeviceFaultAddressTypeKHR = 4
	VK_DEVICE_FAULT_ADDRESS_TYPE_INSTRUCTION_POINTER_INVALID_KHR VkDeviceFaultAddressTypeKHR = 5
	VK_DEVICE_FAULT_ADDRESS_TYPE_INSTRUCTION_POINTER_FAULT_KHR VkDeviceFaultAddressTypeKHR = 6
)

type VkDeviceFaultVendorBinaryHeaderVersionKHR VkEnum
const (
	VK_DEVICE_FAULT_VENDOR_BINARY_HEADER_VERSION_ONE_KHR VkDeviceFaultVendorBinaryHeaderVersionKHR = 1
)

type VkDeviceMemoryReportEventTypeEXT VkEnum
const (
	VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_ALLOCATE_EXT VkDeviceMemoryReportEventTypeEXT = 0
	VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_FREE_EXT VkDeviceMemoryReportEventTypeEXT = 1
	VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_IMPORT_EXT VkDeviceMemoryReportEventTypeEXT = 2
	VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_UNIMPORT_EXT VkDeviceMemoryReportEventTypeEXT = 3
	VK_DEVICE_MEMORY_REPORT_EVENT_TYPE_ALLOCATION_FAILED_EXT VkDeviceMemoryReportEventTypeEXT = 4
)

type VkDirectDriverLoadingModeLUNARG VkEnum
const (
	VK_DIRECT_DRIVER_LOADING_MODE_EXCLUSIVE_LUNARG VkDirectDriverLoadingModeLUNARG = 0
	VK_DIRECT_DRIVER_LOADING_MODE_INCLUSIVE_LUNARG VkDirectDriverLoadingModeLUNARG = 1
)

type VkDiscardRectangleModeEXT VkEnum
const (
	VK_DISCARD_RECTANGLE_MODE_INCLUSIVE_EXT VkDiscardRectangleModeEXT = 0
	VK_DISCARD_RECTANGLE_MODE_EXCLUSIVE_EXT VkDiscardRectangleModeEXT = 1
)

type VkDisplacementMicromapFormatNV VkEnum
const (
	VK_DISPLACEMENT_MICROMAP_FORMAT_64_TRIANGLES_64_BYTES_NV VkDisplacementMicromapFormatNV = 1
	VK_DISPLACEMENT_MICROMAP_FORMAT_256_TRIANGLES_128_BYTES_NV VkDisplacementMicromapFormatNV = 2
	VK_DISPLACEMENT_MICROMAP_FORMAT_1024_TRIANGLES_128_BYTES_NV VkDisplacementMicromapFormatNV = 3
)

type VkDisplayEventTypeEXT VkEnum
const (
	VK_DISPLAY_EVENT_TYPE_FIRST_PIXEL_OUT_EXT VkDisplayEventTypeEXT = 0
)

type VkDisplayPowerStateEXT VkEnum
const (
	VK_DISPLAY_POWER_STATE_OFF_EXT VkDisplayPowerStateEXT = 0
	VK_DISPLAY_POWER_STATE_SUSPEND_EXT VkDisplayPowerStateEXT = 1
	VK_DISPLAY_POWER_STATE_ON_EXT VkDisplayPowerStateEXT = 2
)

type VkDisplaySurfaceStereoTypeNV VkEnum
const (
	VK_DISPLAY_SURFACE_STEREO_TYPE_NONE_NV VkDisplaySurfaceStereoTypeNV = 0
	VK_DISPLAY_SURFACE_STEREO_TYPE_ONBOARD_DIN_NV VkDisplaySurfaceStereoTypeNV = 1
	VK_DISPLAY_SURFACE_STEREO_TYPE_HDMI_3D_NV VkDisplaySurfaceStereoTypeNV = 2
	VK_DISPLAY_SURFACE_STEREO_TYPE_INBAND_DISPLAYPORT_NV VkDisplaySurfaceStereoTypeNV = 3
)

type VkDriverId VkEnum
const (
	/*
	VK_DRIVER_ID_AMD_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Advanced Micro Devices, Inc.
	*/
	VK_DRIVER_ID_AMD_PROPRIETARY VkDriverId = 1

	/*
	VK_DRIVER_ID_AMD_OPEN_SOURCE Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Advanced Micro Devices, Inc.
	*/
	VK_DRIVER_ID_AMD_OPEN_SOURCE VkDriverId = 2

	/*
	VK_DRIVER_ID_MESA_RADV Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_RADV VkDriverId = 3

	/*
	VK_DRIVER_ID_NVIDIA_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	NVIDIA Corporation
	*/
	VK_DRIVER_ID_NVIDIA_PROPRIETARY VkDriverId = 4

	/*
	VK_DRIVER_ID_INTEL_PROPRIETARY_WINDOWS Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Intel Corporation
	*/
	VK_DRIVER_ID_INTEL_PROPRIETARY_WINDOWS VkDriverId = 5

	/*
	VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Intel Corporation
	*/
	VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA VkDriverId = 6

	/*
	VK_DRIVER_ID_IMAGINATION_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Imagination Technologies
	*/
	VK_DRIVER_ID_IMAGINATION_PROPRIETARY VkDriverId = 7

	/*
	VK_DRIVER_ID_QUALCOMM_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Qualcomm Technologies, Inc.
	*/
	VK_DRIVER_ID_QUALCOMM_PROPRIETARY VkDriverId = 8

	/*
	VK_DRIVER_ID_ARM_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Arm Limited
	*/
	VK_DRIVER_ID_ARM_PROPRIETARY VkDriverId = 9

	/*
	VK_DRIVER_ID_GOOGLE_SWIFTSHADER Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Google LLC
	*/
	VK_DRIVER_ID_GOOGLE_SWIFTSHADER VkDriverId = 10

	/*
	VK_DRIVER_ID_GGP_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Google LLC
	*/
	VK_DRIVER_ID_GGP_PROPRIETARY VkDriverId = 11

	/*
	VK_DRIVER_ID_BROADCOM_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Broadcom Inc.
	*/
	VK_DRIVER_ID_BROADCOM_PROPRIETARY VkDriverId = 12

	/*
	VK_DRIVER_ID_MESA_LLVMPIPE Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa
	*/
	VK_DRIVER_ID_MESA_LLVMPIPE VkDriverId = 13

	/*
	VK_DRIVER_ID_MOLTENVK Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	MoltenVK
	*/
	VK_DRIVER_ID_MOLTENVK VkDriverId = 14

	/*
	VK_DRIVER_ID_COREAVI_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Core Avionics & Industrial Inc.
	*/
	VK_DRIVER_ID_COREAVI_PROPRIETARY VkDriverId = 15

	/*
	VK_DRIVER_ID_JUICE_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Juice Technologies, Inc.
	*/
	VK_DRIVER_ID_JUICE_PROPRIETARY VkDriverId = 16

	/*
	VK_DRIVER_ID_VERISILICON_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Verisilicon, Inc.
	*/
	VK_DRIVER_ID_VERISILICON_PROPRIETARY VkDriverId = 17

	/*
	VK_DRIVER_ID_MESA_TURNIP Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_TURNIP VkDriverId = 18

	/*
	VK_DRIVER_ID_MESA_V3DV Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_V3DV VkDriverId = 19

	/*
	VK_DRIVER_ID_MESA_PANVK Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_PANVK VkDriverId = 20

	/*
	VK_DRIVER_ID_SAMSUNG_PROPRIETARY Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Samsung Electronics Co., Ltd.
	*/
	VK_DRIVER_ID_SAMSUNG_PROPRIETARY VkDriverId = 21

	/*
	VK_DRIVER_ID_MESA_VENUS Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_VENUS VkDriverId = 22

	/*
	VK_DRIVER_ID_MESA_DOZEN Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_DOZEN VkDriverId = 23

	/*
	VK_DRIVER_ID_MESA_NVK Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_NVK VkDriverId = 24

	/*
	VK_DRIVER_ID_IMAGINATION_OPEN_SOURCE_MESA Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Imagination Technologies
	*/
	VK_DRIVER_ID_IMAGINATION_OPEN_SOURCE_MESA VkDriverId = 25

	/*
	VK_DRIVER_ID_MESA_HONEYKRISP Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_HONEYKRISP VkDriverId = 26

	/*
	VK_DRIVER_ID_VULKAN_SC_EMULATION_ON_VULKAN Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Vulkan SC Emulation on Vulkan
	*/
	VK_DRIVER_ID_VULKAN_SC_EMULATION_ON_VULKAN VkDriverId = 27

	/*
	VK_DRIVER_ID_MESA_KOSMICKRISP Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_KOSMICKRISP VkDriverId = 28

	/*
	VK_DRIVER_ID_MESA_GFXSTREAM Driver IDs are now represented as enums instead of the old
	                 <driverids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa open source project
	*/
	VK_DRIVER_ID_MESA_GFXSTREAM VkDriverId = 29
)

type VkDynamicState VkEnum
const (
	VK_DYNAMIC_STATE_VIEWPORT VkDynamicState = 0
	VK_DYNAMIC_STATE_SCISSOR VkDynamicState = 1
	VK_DYNAMIC_STATE_LINE_WIDTH VkDynamicState = 2
	VK_DYNAMIC_STATE_DEPTH_BIAS VkDynamicState = 3
	VK_DYNAMIC_STATE_BLEND_CONSTANTS VkDynamicState = 4
	VK_DYNAMIC_STATE_DEPTH_BOUNDS VkDynamicState = 5
	VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK VkDynamicState = 6
	VK_DYNAMIC_STATE_STENCIL_WRITE_MASK VkDynamicState = 7
	VK_DYNAMIC_STATE_STENCIL_REFERENCE VkDynamicState = 8
)

type VkFaultLevel VkEnum
const (
	VK_FAULT_LEVEL_UNASSIGNED VkFaultLevel = 0
	VK_FAULT_LEVEL_CRITICAL VkFaultLevel = 1
	VK_FAULT_LEVEL_RECOVERABLE VkFaultLevel = 2
	VK_FAULT_LEVEL_WARNING VkFaultLevel = 3
)

type VkFaultQueryBehavior VkEnum
const (
	VK_FAULT_QUERY_BEHAVIOR_GET_AND_CLEAR_ALL_FAULTS VkFaultQueryBehavior = 0
)

type VkFaultType VkEnum
const (
	VK_FAULT_TYPE_INVALID VkFaultType = 0
	VK_FAULT_TYPE_UNASSIGNED VkFaultType = 1
	VK_FAULT_TYPE_IMPLEMENTATION VkFaultType = 2
	VK_FAULT_TYPE_SYSTEM VkFaultType = 3
	VK_FAULT_TYPE_PHYSICAL_DEVICE VkFaultType = 4
	VK_FAULT_TYPE_COMMAND_BUFFER_FULL VkFaultType = 5
	VK_FAULT_TYPE_INVALID_API_USAGE VkFaultType = 6
)

type VkFilter VkEnum
const (
	VK_FILTER_NEAREST VkFilter = 0
	VK_FILTER_LINEAR VkFilter = 1
)

/*
VkFormat Vulkan format definitions
*/
type VkFormat VkEnum
const (
	VK_FORMAT_UNDEFINED VkFormat = 0
	VK_FORMAT_R4G4_UNORM_PACK8 VkFormat = 1
	VK_FORMAT_R4G4B4A4_UNORM_PACK16 VkFormat = 2
	VK_FORMAT_B4G4R4A4_UNORM_PACK16 VkFormat = 3
	VK_FORMAT_R5G6B5_UNORM_PACK16 VkFormat = 4
	VK_FORMAT_B5G6R5_UNORM_PACK16 VkFormat = 5
	VK_FORMAT_R5G5B5A1_UNORM_PACK16 VkFormat = 6
	VK_FORMAT_B5G5R5A1_UNORM_PACK16 VkFormat = 7
	VK_FORMAT_A1R5G5B5_UNORM_PACK16 VkFormat = 8
	VK_FORMAT_R8_UNORM VkFormat = 9
	VK_FORMAT_R8_SNORM VkFormat = 10
	VK_FORMAT_R8_USCALED VkFormat = 11
	VK_FORMAT_R8_SSCALED VkFormat = 12
	VK_FORMAT_R8_UINT VkFormat = 13
	VK_FORMAT_R8_SINT VkFormat = 14
	VK_FORMAT_R8_SRGB VkFormat = 15
	VK_FORMAT_R8G8_UNORM VkFormat = 16
	VK_FORMAT_R8G8_SNORM VkFormat = 17
	VK_FORMAT_R8G8_USCALED VkFormat = 18
	VK_FORMAT_R8G8_SSCALED VkFormat = 19
	VK_FORMAT_R8G8_UINT VkFormat = 20
	VK_FORMAT_R8G8_SINT VkFormat = 21
	VK_FORMAT_R8G8_SRGB VkFormat = 22
	VK_FORMAT_R8G8B8_UNORM VkFormat = 23
	VK_FORMAT_R8G8B8_SNORM VkFormat = 24
	VK_FORMAT_R8G8B8_USCALED VkFormat = 25
	VK_FORMAT_R8G8B8_SSCALED VkFormat = 26
	VK_FORMAT_R8G8B8_UINT VkFormat = 27
	VK_FORMAT_R8G8B8_SINT VkFormat = 28
	VK_FORMAT_R8G8B8_SRGB VkFormat = 29
	VK_FORMAT_B8G8R8_UNORM VkFormat = 30
	VK_FORMAT_B8G8R8_SNORM VkFormat = 31
	VK_FORMAT_B8G8R8_USCALED VkFormat = 32
	VK_FORMAT_B8G8R8_SSCALED VkFormat = 33
	VK_FORMAT_B8G8R8_UINT VkFormat = 34
	VK_FORMAT_B8G8R8_SINT VkFormat = 35
	VK_FORMAT_B8G8R8_SRGB VkFormat = 36
	VK_FORMAT_R8G8B8A8_UNORM VkFormat = 37
	VK_FORMAT_R8G8B8A8_SNORM VkFormat = 38
	VK_FORMAT_R8G8B8A8_USCALED VkFormat = 39
	VK_FORMAT_R8G8B8A8_SSCALED VkFormat = 40
	VK_FORMAT_R8G8B8A8_UINT VkFormat = 41
	VK_FORMAT_R8G8B8A8_SINT VkFormat = 42
	VK_FORMAT_R8G8B8A8_SRGB VkFormat = 43
	VK_FORMAT_B8G8R8A8_UNORM VkFormat = 44
	VK_FORMAT_B8G8R8A8_SNORM VkFormat = 45
	VK_FORMAT_B8G8R8A8_USCALED VkFormat = 46
	VK_FORMAT_B8G8R8A8_SSCALED VkFormat = 47
	VK_FORMAT_B8G8R8A8_UINT VkFormat = 48
	VK_FORMAT_B8G8R8A8_SINT VkFormat = 49
	VK_FORMAT_B8G8R8A8_SRGB VkFormat = 50
	VK_FORMAT_A8B8G8R8_UNORM_PACK32 VkFormat = 51
	VK_FORMAT_A8B8G8R8_SNORM_PACK32 VkFormat = 52
	VK_FORMAT_A8B8G8R8_USCALED_PACK32 VkFormat = 53
	VK_FORMAT_A8B8G8R8_SSCALED_PACK32 VkFormat = 54
	VK_FORMAT_A8B8G8R8_UINT_PACK32 VkFormat = 55
	VK_FORMAT_A8B8G8R8_SINT_PACK32 VkFormat = 56
	VK_FORMAT_A8B8G8R8_SRGB_PACK32 VkFormat = 57
	VK_FORMAT_A2R10G10B10_UNORM_PACK32 VkFormat = 58
	VK_FORMAT_A2R10G10B10_SNORM_PACK32 VkFormat = 59
	VK_FORMAT_A2R10G10B10_USCALED_PACK32 VkFormat = 60
	VK_FORMAT_A2R10G10B10_SSCALED_PACK32 VkFormat = 61
	VK_FORMAT_A2R10G10B10_UINT_PACK32 VkFormat = 62
	VK_FORMAT_A2R10G10B10_SINT_PACK32 VkFormat = 63
	VK_FORMAT_A2B10G10R10_UNORM_PACK32 VkFormat = 64
	VK_FORMAT_A2B10G10R10_SNORM_PACK32 VkFormat = 65
	VK_FORMAT_A2B10G10R10_USCALED_PACK32 VkFormat = 66
	VK_FORMAT_A2B10G10R10_SSCALED_PACK32 VkFormat = 67
	VK_FORMAT_A2B10G10R10_UINT_PACK32 VkFormat = 68
	VK_FORMAT_A2B10G10R10_SINT_PACK32 VkFormat = 69
	VK_FORMAT_R16_UNORM VkFormat = 70
	VK_FORMAT_R16_SNORM VkFormat = 71
	VK_FORMAT_R16_USCALED VkFormat = 72
	VK_FORMAT_R16_SSCALED VkFormat = 73
	VK_FORMAT_R16_UINT VkFormat = 74
	VK_FORMAT_R16_SINT VkFormat = 75
	VK_FORMAT_R16_SFLOAT VkFormat = 76
	VK_FORMAT_R16G16_UNORM VkFormat = 77
	VK_FORMAT_R16G16_SNORM VkFormat = 78
	VK_FORMAT_R16G16_USCALED VkFormat = 79
	VK_FORMAT_R16G16_SSCALED VkFormat = 80
	VK_FORMAT_R16G16_UINT VkFormat = 81
	VK_FORMAT_R16G16_SINT VkFormat = 82
	VK_FORMAT_R16G16_SFLOAT VkFormat = 83
	VK_FORMAT_R16G16B16_UNORM VkFormat = 84
	VK_FORMAT_R16G16B16_SNORM VkFormat = 85
	VK_FORMAT_R16G16B16_USCALED VkFormat = 86
	VK_FORMAT_R16G16B16_SSCALED VkFormat = 87
	VK_FORMAT_R16G16B16_UINT VkFormat = 88
	VK_FORMAT_R16G16B16_SINT VkFormat = 89
	VK_FORMAT_R16G16B16_SFLOAT VkFormat = 90
	VK_FORMAT_R16G16B16A16_UNORM VkFormat = 91
	VK_FORMAT_R16G16B16A16_SNORM VkFormat = 92
	VK_FORMAT_R16G16B16A16_USCALED VkFormat = 93
	VK_FORMAT_R16G16B16A16_SSCALED VkFormat = 94
	VK_FORMAT_R16G16B16A16_UINT VkFormat = 95
	VK_FORMAT_R16G16B16A16_SINT VkFormat = 96
	VK_FORMAT_R16G16B16A16_SFLOAT VkFormat = 97
	VK_FORMAT_R32_UINT VkFormat = 98
	VK_FORMAT_R32_SINT VkFormat = 99
	VK_FORMAT_R32_SFLOAT VkFormat = 100
	VK_FORMAT_R32G32_UINT VkFormat = 101
	VK_FORMAT_R32G32_SINT VkFormat = 102
	VK_FORMAT_R32G32_SFLOAT VkFormat = 103
	VK_FORMAT_R32G32B32_UINT VkFormat = 104
	VK_FORMAT_R32G32B32_SINT VkFormat = 105
	VK_FORMAT_R32G32B32_SFLOAT VkFormat = 106
	VK_FORMAT_R32G32B32A32_UINT VkFormat = 107
	VK_FORMAT_R32G32B32A32_SINT VkFormat = 108
	VK_FORMAT_R32G32B32A32_SFLOAT VkFormat = 109
	VK_FORMAT_R64_UINT VkFormat = 110
	VK_FORMAT_R64_SINT VkFormat = 111
	VK_FORMAT_R64_SFLOAT VkFormat = 112
	VK_FORMAT_R64G64_UINT VkFormat = 113
	VK_FORMAT_R64G64_SINT VkFormat = 114
	VK_FORMAT_R64G64_SFLOAT VkFormat = 115
	VK_FORMAT_R64G64B64_UINT VkFormat = 116
	VK_FORMAT_R64G64B64_SINT VkFormat = 117
	VK_FORMAT_R64G64B64_SFLOAT VkFormat = 118
	VK_FORMAT_R64G64B64A64_UINT VkFormat = 119
	VK_FORMAT_R64G64B64A64_SINT VkFormat = 120
	VK_FORMAT_R64G64B64A64_SFLOAT VkFormat = 121
	VK_FORMAT_B10G11R11_UFLOAT_PACK32 VkFormat = 122
	VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 VkFormat = 123
	VK_FORMAT_D16_UNORM VkFormat = 124
	VK_FORMAT_X8_D24_UNORM_PACK32 VkFormat = 125
	VK_FORMAT_D32_SFLOAT VkFormat = 126
	VK_FORMAT_S8_UINT VkFormat = 127
	VK_FORMAT_D16_UNORM_S8_UINT VkFormat = 128
	VK_FORMAT_D24_UNORM_S8_UINT VkFormat = 129
	VK_FORMAT_D32_SFLOAT_S8_UINT VkFormat = 130
	VK_FORMAT_BC1_RGB_UNORM_BLOCK VkFormat = 131
	VK_FORMAT_BC1_RGB_SRGB_BLOCK VkFormat = 132
	VK_FORMAT_BC1_RGBA_UNORM_BLOCK VkFormat = 133
	VK_FORMAT_BC1_RGBA_SRGB_BLOCK VkFormat = 134
	VK_FORMAT_BC2_UNORM_BLOCK VkFormat = 135
	VK_FORMAT_BC2_SRGB_BLOCK VkFormat = 136
	VK_FORMAT_BC3_UNORM_BLOCK VkFormat = 137
	VK_FORMAT_BC3_SRGB_BLOCK VkFormat = 138
	VK_FORMAT_BC4_UNORM_BLOCK VkFormat = 139
	VK_FORMAT_BC4_SNORM_BLOCK VkFormat = 140
	VK_FORMAT_BC5_UNORM_BLOCK VkFormat = 141
	VK_FORMAT_BC5_SNORM_BLOCK VkFormat = 142
	VK_FORMAT_BC6H_UFLOAT_BLOCK VkFormat = 143
	VK_FORMAT_BC6H_SFLOAT_BLOCK VkFormat = 144
	VK_FORMAT_BC7_UNORM_BLOCK VkFormat = 145
	VK_FORMAT_BC7_SRGB_BLOCK VkFormat = 146
	VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK VkFormat = 147
	VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK VkFormat = 148
	VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK VkFormat = 149
	VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK VkFormat = 150
	VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK VkFormat = 151
	VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK VkFormat = 152
	VK_FORMAT_EAC_R11_UNORM_BLOCK VkFormat = 153
	VK_FORMAT_EAC_R11_SNORM_BLOCK VkFormat = 154
	VK_FORMAT_EAC_R11G11_UNORM_BLOCK VkFormat = 155
	VK_FORMAT_EAC_R11G11_SNORM_BLOCK VkFormat = 156
	VK_FORMAT_ASTC_4x4_UNORM_BLOCK VkFormat = 157
	VK_FORMAT_ASTC_4x4_SRGB_BLOCK VkFormat = 158
	VK_FORMAT_ASTC_5x4_UNORM_BLOCK VkFormat = 159
	VK_FORMAT_ASTC_5x4_SRGB_BLOCK VkFormat = 160
	VK_FORMAT_ASTC_5x5_UNORM_BLOCK VkFormat = 161
	VK_FORMAT_ASTC_5x5_SRGB_BLOCK VkFormat = 162
	VK_FORMAT_ASTC_6x5_UNORM_BLOCK VkFormat = 163
	VK_FORMAT_ASTC_6x5_SRGB_BLOCK VkFormat = 164
	VK_FORMAT_ASTC_6x6_UNORM_BLOCK VkFormat = 165
	VK_FORMAT_ASTC_6x6_SRGB_BLOCK VkFormat = 166
	VK_FORMAT_ASTC_8x5_UNORM_BLOCK VkFormat = 167
	VK_FORMAT_ASTC_8x5_SRGB_BLOCK VkFormat = 168
	VK_FORMAT_ASTC_8x6_UNORM_BLOCK VkFormat = 169
	VK_FORMAT_ASTC_8x6_SRGB_BLOCK VkFormat = 170
	VK_FORMAT_ASTC_8x8_UNORM_BLOCK VkFormat = 171
	VK_FORMAT_ASTC_8x8_SRGB_BLOCK VkFormat = 172
	VK_FORMAT_ASTC_10x5_UNORM_BLOCK VkFormat = 173
	VK_FORMAT_ASTC_10x5_SRGB_BLOCK VkFormat = 174
	VK_FORMAT_ASTC_10x6_UNORM_BLOCK VkFormat = 175
	VK_FORMAT_ASTC_10x6_SRGB_BLOCK VkFormat = 176
	VK_FORMAT_ASTC_10x8_UNORM_BLOCK VkFormat = 177
	VK_FORMAT_ASTC_10x8_SRGB_BLOCK VkFormat = 178
	VK_FORMAT_ASTC_10x10_UNORM_BLOCK VkFormat = 179
	VK_FORMAT_ASTC_10x10_SRGB_BLOCK VkFormat = 180
	VK_FORMAT_ASTC_12x10_UNORM_BLOCK VkFormat = 181
	VK_FORMAT_ASTC_12x10_SRGB_BLOCK VkFormat = 182
	VK_FORMAT_ASTC_12x12_UNORM_BLOCK VkFormat = 183
	VK_FORMAT_ASTC_12x12_SRGB_BLOCK VkFormat = 184
)

type VkFragmentShadingRateCombinerOpKHR VkEnum
const (
	VK_FRAGMENT_SHADING_RATE_COMBINER_OP_KEEP_KHR VkFragmentShadingRateCombinerOpKHR = 0
	VK_FRAGMENT_SHADING_RATE_COMBINER_OP_REPLACE_KHR VkFragmentShadingRateCombinerOpKHR = 1
	VK_FRAGMENT_SHADING_RATE_COMBINER_OP_MIN_KHR VkFragmentShadingRateCombinerOpKHR = 2
	VK_FRAGMENT_SHADING_RATE_COMBINER_OP_MAX_KHR VkFragmentShadingRateCombinerOpKHR = 3
	VK_FRAGMENT_SHADING_RATE_COMBINER_OP_MUL_KHR VkFragmentShadingRateCombinerOpKHR = 4
)

type VkFragmentShadingRateNV VkEnum
const (
	VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_PIXEL_NV VkFragmentShadingRateNV = 0
	VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_1X2_PIXELS_NV VkFragmentShadingRateNV = 1
	VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_2X1_PIXELS_NV VkFragmentShadingRateNV = 4
	VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_2X2_PIXELS_NV VkFragmentShadingRateNV = 5
	VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_2X4_PIXELS_NV VkFragmentShadingRateNV = 6
	VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_4X2_PIXELS_NV VkFragmentShadingRateNV = 9
	VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_4X4_PIXELS_NV VkFragmentShadingRateNV = 10
	VK_FRAGMENT_SHADING_RATE_2_INVOCATIONS_PER_PIXEL_NV VkFragmentShadingRateNV = 11
	VK_FRAGMENT_SHADING_RATE_4_INVOCATIONS_PER_PIXEL_NV VkFragmentShadingRateNV = 12
	VK_FRAGMENT_SHADING_RATE_8_INVOCATIONS_PER_PIXEL_NV VkFragmentShadingRateNV = 13
	VK_FRAGMENT_SHADING_RATE_16_INVOCATIONS_PER_PIXEL_NV VkFragmentShadingRateNV = 14
	VK_FRAGMENT_SHADING_RATE_NO_INVOCATIONS_NV VkFragmentShadingRateNV = 15
)

type VkFragmentShadingRateTypeNV VkEnum
const (
	VK_FRAGMENT_SHADING_RATE_TYPE_FRAGMENT_SIZE_NV VkFragmentShadingRateTypeNV = 0
	VK_FRAGMENT_SHADING_RATE_TYPE_ENUMS_NV VkFragmentShadingRateTypeNV = 1
)

type VkFrontFace VkEnum
const (
	VK_FRONT_FACE_COUNTER_CLOCKWISE VkFrontFace = 0
	VK_FRONT_FACE_CLOCKWISE VkFrontFace = 1
)

type VkFullScreenExclusiveEXT VkEnum
const (
	VK_FULL_SCREEN_EXCLUSIVE_DEFAULT_EXT VkFullScreenExclusiveEXT = 0
	VK_FULL_SCREEN_EXCLUSIVE_ALLOWED_EXT VkFullScreenExclusiveEXT = 1
	VK_FULL_SCREEN_EXCLUSIVE_DISALLOWED_EXT VkFullScreenExclusiveEXT = 2
	VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT VkFullScreenExclusiveEXT = 3
)

type VkGeometryTypeKHR VkEnum
const (
	VK_GEOMETRY_TYPE_TRIANGLES_KHR VkGeometryTypeKHR = 0
	VK_GEOMETRY_TYPE_AABBS_KHR VkGeometryTypeKHR = 1
	VK_GEOMETRY_TYPE_INSTANCES_KHR VkGeometryTypeKHR = 2
)

type VkGpaDeviceClockModeAMD VkEnum
const (
	VK_GPA_DEVICE_CLOCK_MODE_DEFAULT_AMD VkGpaDeviceClockModeAMD = 0
	VK_GPA_DEVICE_CLOCK_MODE_QUERY_AMD VkGpaDeviceClockModeAMD = 1
	VK_GPA_DEVICE_CLOCK_MODE_PROFILING_AMD VkGpaDeviceClockModeAMD = 2
	VK_GPA_DEVICE_CLOCK_MODE_MIN_MEMORY_AMD VkGpaDeviceClockModeAMD = 3
	VK_GPA_DEVICE_CLOCK_MODE_MIN_ENGINE_AMD VkGpaDeviceClockModeAMD = 4
	VK_GPA_DEVICE_CLOCK_MODE_PEAK_AMD VkGpaDeviceClockModeAMD = 5
)

type VkGpaPerfBlockAMD VkEnum
const (
	VK_GPA_PERF_BLOCK_CPF_AMD VkGpaPerfBlockAMD = 0
	VK_GPA_PERF_BLOCK_IA_AMD VkGpaPerfBlockAMD = 1
	VK_GPA_PERF_BLOCK_VGT_AMD VkGpaPerfBlockAMD = 2
	VK_GPA_PERF_BLOCK_PA_AMD VkGpaPerfBlockAMD = 3
	VK_GPA_PERF_BLOCK_SC_AMD VkGpaPerfBlockAMD = 4
	VK_GPA_PERF_BLOCK_SPI_AMD VkGpaPerfBlockAMD = 5
	VK_GPA_PERF_BLOCK_SQ_AMD VkGpaPerfBlockAMD = 6
	VK_GPA_PERF_BLOCK_SX_AMD VkGpaPerfBlockAMD = 7
	VK_GPA_PERF_BLOCK_TA_AMD VkGpaPerfBlockAMD = 8
	VK_GPA_PERF_BLOCK_TD_AMD VkGpaPerfBlockAMD = 9
	VK_GPA_PERF_BLOCK_TCP_AMD VkGpaPerfBlockAMD = 10
	VK_GPA_PERF_BLOCK_TCC_AMD VkGpaPerfBlockAMD = 11
	VK_GPA_PERF_BLOCK_TCA_AMD VkGpaPerfBlockAMD = 12
	VK_GPA_PERF_BLOCK_DB_AMD VkGpaPerfBlockAMD = 13
	VK_GPA_PERF_BLOCK_CB_AMD VkGpaPerfBlockAMD = 14
	VK_GPA_PERF_BLOCK_GDS_AMD VkGpaPerfBlockAMD = 15
	VK_GPA_PERF_BLOCK_SRBM_AMD VkGpaPerfBlockAMD = 16
	VK_GPA_PERF_BLOCK_GRBM_AMD VkGpaPerfBlockAMD = 17
	VK_GPA_PERF_BLOCK_GRBM_SE_AMD VkGpaPerfBlockAMD = 18
	VK_GPA_PERF_BLOCK_RLC_AMD VkGpaPerfBlockAMD = 19
	VK_GPA_PERF_BLOCK_DMA_AMD VkGpaPerfBlockAMD = 20
	VK_GPA_PERF_BLOCK_MC_AMD VkGpaPerfBlockAMD = 21
	VK_GPA_PERF_BLOCK_CPG_AMD VkGpaPerfBlockAMD = 22
	VK_GPA_PERF_BLOCK_CPC_AMD VkGpaPerfBlockAMD = 23
	VK_GPA_PERF_BLOCK_WD_AMD VkGpaPerfBlockAMD = 24
	VK_GPA_PERF_BLOCK_TCS_AMD VkGpaPerfBlockAMD = 25
	VK_GPA_PERF_BLOCK_ATC_AMD VkGpaPerfBlockAMD = 26
	VK_GPA_PERF_BLOCK_ATC_L2_AMD VkGpaPerfBlockAMD = 27
	VK_GPA_PERF_BLOCK_MC_VM_L2_AMD VkGpaPerfBlockAMD = 28
	VK_GPA_PERF_BLOCK_EA_AMD VkGpaPerfBlockAMD = 29
	VK_GPA_PERF_BLOCK_RPB_AMD VkGpaPerfBlockAMD = 30
	VK_GPA_PERF_BLOCK_RMI_AMD VkGpaPerfBlockAMD = 31
	VK_GPA_PERF_BLOCK_UMCCH_AMD VkGpaPerfBlockAMD = 32
	VK_GPA_PERF_BLOCK_GE_AMD VkGpaPerfBlockAMD = 33
	VK_GPA_PERF_BLOCK_GL1A_AMD VkGpaPerfBlockAMD = 34
	VK_GPA_PERF_BLOCK_GL1C_AMD VkGpaPerfBlockAMD = 35
	VK_GPA_PERF_BLOCK_GL1CG_AMD VkGpaPerfBlockAMD = 36
	VK_GPA_PERF_BLOCK_GL2A_AMD VkGpaPerfBlockAMD = 37
	VK_GPA_PERF_BLOCK_GL2C_AMD VkGpaPerfBlockAMD = 38
	VK_GPA_PERF_BLOCK_CHA_AMD VkGpaPerfBlockAMD = 39
	VK_GPA_PERF_BLOCK_CHC_AMD VkGpaPerfBlockAMD = 40
	VK_GPA_PERF_BLOCK_CHCG_AMD VkGpaPerfBlockAMD = 41
	VK_GPA_PERF_BLOCK_GUS_AMD VkGpaPerfBlockAMD = 42
	VK_GPA_PERF_BLOCK_GCR_AMD VkGpaPerfBlockAMD = 43
	VK_GPA_PERF_BLOCK_PH_AMD VkGpaPerfBlockAMD = 44
	VK_GPA_PERF_BLOCK_UTCL1_AMD VkGpaPerfBlockAMD = 45
	VK_GPA_PERF_BLOCK_GE_DIST_AMD VkGpaPerfBlockAMD = 46
	VK_GPA_PERF_BLOCK_GE_SE_AMD VkGpaPerfBlockAMD = 47
	VK_GPA_PERF_BLOCK_DF_MALL_AMD VkGpaPerfBlockAMD = 48
	VK_GPA_PERF_BLOCK_SQ_WGP_AMD VkGpaPerfBlockAMD = 49
	VK_GPA_PERF_BLOCK_PC_AMD VkGpaPerfBlockAMD = 50
	VK_GPA_PERF_BLOCK_GL1XA_AMD VkGpaPerfBlockAMD = 51
	VK_GPA_PERF_BLOCK_GL1XC_AMD VkGpaPerfBlockAMD = 52
	VK_GPA_PERF_BLOCK_WGS_AMD VkGpaPerfBlockAMD = 53
	VK_GPA_PERF_BLOCK_EACPWD_AMD VkGpaPerfBlockAMD = 54
	VK_GPA_PERF_BLOCK_EASE_AMD VkGpaPerfBlockAMD = 55
	VK_GPA_PERF_BLOCK_RLCUSER_AMD VkGpaPerfBlockAMD = 56
)

type VkGpaSampleTypeAMD VkEnum
const (
	VK_GPA_SAMPLE_TYPE_CUMULATIVE_AMD VkGpaSampleTypeAMD = 0
	VK_GPA_SAMPLE_TYPE_TRACE_AMD VkGpaSampleTypeAMD = 1
	VK_GPA_SAMPLE_TYPE_TIMING_AMD VkGpaSampleTypeAMD = 2
)

type VkImageLayout VkEnum
const (
	/*
	VK_IMAGE_LAYOUT_UNDEFINED Implicit layout an image is when its contents are undefined due to various reasons (e.g. right after creation)
	*/
	VK_IMAGE_LAYOUT_UNDEFINED VkImageLayout = 0

	/*
	VK_IMAGE_LAYOUT_GENERAL General layout when image can be used for any kind of access
	*/
	VK_IMAGE_LAYOUT_GENERAL VkImageLayout = 1

	/*
	VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL Optimal layout when image is only used for color attachment read/write
	*/
	VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL VkImageLayout = 2

	/*
	VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL Optimal layout when image is only used for depth/stencil attachment read/write
	*/
	VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL VkImageLayout = 3

	/*
	VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL Optimal layout when image is used for read only depth/stencil attachment and shader access
	*/
	VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL VkImageLayout = 4

	/*
	VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL Optimal layout when image is used for read only shader access
	*/
	VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL VkImageLayout = 5

	/*
	VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL Optimal layout when image is used only as source of transfer operations
	*/
	VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL VkImageLayout = 6

	/*
	VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL Optimal layout when image is used only as destination of transfer operations
	*/
	VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL VkImageLayout = 7

	/*
	VK_IMAGE_LAYOUT_PREINITIALIZED Initial layout used when the data is populated by the CPU
	*/
	VK_IMAGE_LAYOUT_PREINITIALIZED VkImageLayout = 8
)

type VkImageTiling VkEnum
const (
	VK_IMAGE_TILING_OPTIMAL VkImageTiling = 0
	VK_IMAGE_TILING_LINEAR VkImageTiling = 1
)

type VkImageType VkEnum
const (
	VK_IMAGE_TYPE_1D VkImageType = 0
	VK_IMAGE_TYPE_2D VkImageType = 1
	VK_IMAGE_TYPE_3D VkImageType = 2
)

type VkImageViewType VkEnum
const (
	VK_IMAGE_VIEW_TYPE_1D VkImageViewType = 0
	VK_IMAGE_VIEW_TYPE_2D VkImageViewType = 1
	VK_IMAGE_VIEW_TYPE_3D VkImageViewType = 2
	VK_IMAGE_VIEW_TYPE_CUBE VkImageViewType = 3
	VK_IMAGE_VIEW_TYPE_1D_ARRAY VkImageViewType = 4
	VK_IMAGE_VIEW_TYPE_2D_ARRAY VkImageViewType = 5
	VK_IMAGE_VIEW_TYPE_CUBE_ARRAY VkImageViewType = 6
)

type VkIndexType VkEnum
const (
	VK_INDEX_TYPE_UINT16 VkIndexType = 0
	VK_INDEX_TYPE_UINT32 VkIndexType = 1
)

type VkIndirectCommandsTokenTypeEXT VkEnum
const (
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT VkIndirectCommandsTokenTypeEXT = 0
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXT VkIndirectCommandsTokenTypeEXT = 1
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXT VkIndirectCommandsTokenTypeEXT = 2
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_EXT VkIndirectCommandsTokenTypeEXT = 3
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_EXT VkIndirectCommandsTokenTypeEXT = 4
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_EXT VkIndirectCommandsTokenTypeEXT = 5
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_EXT VkIndirectCommandsTokenTypeEXT = 6
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_COUNT_EXT VkIndirectCommandsTokenTypeEXT = 7
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_COUNT_EXT VkIndirectCommandsTokenTypeEXT = 8
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_EXT VkIndirectCommandsTokenTypeEXT = 9
)

type VkIndirectCommandsTokenTypeNV VkEnum
const (
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NV VkIndirectCommandsTokenTypeNV = 0
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_STATE_FLAGS_NV VkIndirectCommandsTokenTypeNV = 1
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_NV VkIndirectCommandsTokenTypeNV = 2
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_NV VkIndirectCommandsTokenTypeNV = 3
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NV VkIndirectCommandsTokenTypeNV = 4
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_NV VkIndirectCommandsTokenTypeNV = 5
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_NV VkIndirectCommandsTokenTypeNV = 6
	VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_TASKS_NV VkIndirectCommandsTokenTypeNV = 7
)

type VkIndirectExecutionSetInfoTypeEXT VkEnum
const (
	VK_INDIRECT_EXECUTION_SET_INFO_TYPE_PIPELINES_EXT VkIndirectExecutionSetInfoTypeEXT = 0
	VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT VkIndirectExecutionSetInfoTypeEXT = 1
)

type VkInternalAllocationType VkEnum
const (
	VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE VkInternalAllocationType = 0
)

type VkLatencyMarkerNV VkEnum
const (
	VK_LATENCY_MARKER_SIMULATION_START_NV VkLatencyMarkerNV = 0
	VK_LATENCY_MARKER_SIMULATION_END_NV VkLatencyMarkerNV = 1
	VK_LATENCY_MARKER_RENDERSUBMIT_START_NV VkLatencyMarkerNV = 2
	VK_LATENCY_MARKER_RENDERSUBMIT_END_NV VkLatencyMarkerNV = 3
	VK_LATENCY_MARKER_PRESENT_START_NV VkLatencyMarkerNV = 4
	VK_LATENCY_MARKER_PRESENT_END_NV VkLatencyMarkerNV = 5
	VK_LATENCY_MARKER_INPUT_SAMPLE_NV VkLatencyMarkerNV = 6
	VK_LATENCY_MARKER_TRIGGER_FLASH_NV VkLatencyMarkerNV = 7
	VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_START_NV VkLatencyMarkerNV = 8
	VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_END_NV VkLatencyMarkerNV = 9
	VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NV VkLatencyMarkerNV = 10
	VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_END_NV VkLatencyMarkerNV = 11
)

type VkLayerSettingTypeEXT VkEnum
const (
	VK_LAYER_SETTING_TYPE_BOOL32_EXT VkLayerSettingTypeEXT = 0
	VK_LAYER_SETTING_TYPE_INT32_EXT VkLayerSettingTypeEXT = 1
	VK_LAYER_SETTING_TYPE_INT64_EXT VkLayerSettingTypeEXT = 2
	VK_LAYER_SETTING_TYPE_UINT32_EXT VkLayerSettingTypeEXT = 3
	VK_LAYER_SETTING_TYPE_UINT64_EXT VkLayerSettingTypeEXT = 4
	VK_LAYER_SETTING_TYPE_FLOAT32_EXT VkLayerSettingTypeEXT = 5
	VK_LAYER_SETTING_TYPE_FLOAT64_EXT VkLayerSettingTypeEXT = 6
	VK_LAYER_SETTING_TYPE_STRING_EXT VkLayerSettingTypeEXT = 7
)

type VkLayeredDriverUnderlyingApiMSFT VkEnum
const (
	VK_LAYERED_DRIVER_UNDERLYING_API_NONE_MSFT VkLayeredDriverUnderlyingApiMSFT = 0
	VK_LAYERED_DRIVER_UNDERLYING_API_D3D12_MSFT VkLayeredDriverUnderlyingApiMSFT = 1
)

type VkLineRasterizationMode VkEnum
const (
	VK_LINE_RASTERIZATION_MODE_DEFAULT VkLineRasterizationMode = 0
	VK_LINE_RASTERIZATION_MODE_RECTANGULAR VkLineRasterizationMode = 1
	VK_LINE_RASTERIZATION_MODE_BRESENHAM VkLineRasterizationMode = 2
	VK_LINE_RASTERIZATION_MODE_RECTANGULAR_SMOOTH VkLineRasterizationMode = 3
)

type VkLogicOp VkEnum
const (
	VK_LOGIC_OP_CLEAR VkLogicOp = 0
	VK_LOGIC_OP_AND VkLogicOp = 1
	VK_LOGIC_OP_AND_REVERSE VkLogicOp = 2
	VK_LOGIC_OP_COPY VkLogicOp = 3
	VK_LOGIC_OP_AND_INVERTED VkLogicOp = 4
	VK_LOGIC_OP_NO_OP VkLogicOp = 5
	VK_LOGIC_OP_XOR VkLogicOp = 6
	VK_LOGIC_OP_OR VkLogicOp = 7
	VK_LOGIC_OP_NOR VkLogicOp = 8
	VK_LOGIC_OP_EQUIVALENT VkLogicOp = 9
	VK_LOGIC_OP_INVERT VkLogicOp = 10
	VK_LOGIC_OP_OR_REVERSE VkLogicOp = 11
	VK_LOGIC_OP_COPY_INVERTED VkLogicOp = 12
	VK_LOGIC_OP_OR_INVERTED VkLogicOp = 13
	VK_LOGIC_OP_NAND VkLogicOp = 14
	VK_LOGIC_OP_SET VkLogicOp = 15
)

type VkMemoryOverallocationBehaviorAMD VkEnum
const (
	VK_MEMORY_OVERALLOCATION_BEHAVIOR_DEFAULT_AMD VkMemoryOverallocationBehaviorAMD = 0
	VK_MEMORY_OVERALLOCATION_BEHAVIOR_ALLOWED_AMD VkMemoryOverallocationBehaviorAMD = 1
	VK_MEMORY_OVERALLOCATION_BEHAVIOR_DISALLOWED_AMD VkMemoryOverallocationBehaviorAMD = 2
)

type VkMicromapTypeEXT VkEnum
const (
	VK_MICROMAP_TYPE_OPACITY_MICROMAP_EXT VkMicromapTypeEXT = 0
)

type VkNeuralAcceleratorStatisticsModeARM VkEnum
const (
	VK_NEURAL_ACCELERATOR_STATISTICS_MODE_DISABLED_ARM VkNeuralAcceleratorStatisticsModeARM = 0
	VK_NEURAL_ACCELERATOR_STATISTICS_MODE_STATISTICS0_ARM VkNeuralAcceleratorStatisticsModeARM = 1
	VK_NEURAL_ACCELERATOR_STATISTICS_MODE_STATISTICS1_ARM VkNeuralAcceleratorStatisticsModeARM = 2
)

/*
VkObjectType Enums to track objects of various types - also see objtypeenum attributes on type tags
*/
type VkObjectType VkEnum
const (
	VK_OBJECT_TYPE_UNKNOWN VkObjectType = 0
	VK_OBJECT_TYPE_INSTANCE VkObjectType = 1
	VK_OBJECT_TYPE_PHYSICAL_DEVICE VkObjectType = 2
	VK_OBJECT_TYPE_DEVICE VkObjectType = 3
	VK_OBJECT_TYPE_QUEUE VkObjectType = 4
	VK_OBJECT_TYPE_SEMAPHORE VkObjectType = 5
	VK_OBJECT_TYPE_COMMAND_BUFFER VkObjectType = 6
	VK_OBJECT_TYPE_FENCE VkObjectType = 7
	VK_OBJECT_TYPE_DEVICE_MEMORY VkObjectType = 8
	VK_OBJECT_TYPE_BUFFER VkObjectType = 9
	VK_OBJECT_TYPE_IMAGE VkObjectType = 10
	VK_OBJECT_TYPE_EVENT VkObjectType = 11
	VK_OBJECT_TYPE_QUERY_POOL VkObjectType = 12
	VK_OBJECT_TYPE_BUFFER_VIEW VkObjectType = 13
	VK_OBJECT_TYPE_IMAGE_VIEW VkObjectType = 14
	VK_OBJECT_TYPE_SHADER_MODULE VkObjectType = 15
	VK_OBJECT_TYPE_PIPELINE_CACHE VkObjectType = 16
	VK_OBJECT_TYPE_PIPELINE_LAYOUT VkObjectType = 17
	VK_OBJECT_TYPE_RENDER_PASS VkObjectType = 18
	VK_OBJECT_TYPE_PIPELINE VkObjectType = 19
	VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT VkObjectType = 20
	VK_OBJECT_TYPE_SAMPLER VkObjectType = 21
	VK_OBJECT_TYPE_DESCRIPTOR_POOL VkObjectType = 22
	VK_OBJECT_TYPE_DESCRIPTOR_SET VkObjectType = 23
	VK_OBJECT_TYPE_FRAMEBUFFER VkObjectType = 24
	VK_OBJECT_TYPE_COMMAND_POOL VkObjectType = 25
)

type VkOpacityMicromapFormatKHR VkEnum
const (
	VK_OPACITY_MICROMAP_FORMAT_2_STATE_KHR VkOpacityMicromapFormatKHR = 1
	VK_OPACITY_MICROMAP_FORMAT_4_STATE_KHR VkOpacityMicromapFormatKHR = 2
)

type VkOpacityMicromapSpecialIndexKHR VkEnum
const (
	VK_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_TRANSPARENT_KHR VkOpacityMicromapSpecialIndexKHR = -1
	VK_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_OPAQUE_KHR VkOpacityMicromapSpecialIndexKHR = -2
	VK_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_TRANSPARENT_KHR VkOpacityMicromapSpecialIndexKHR = -3
	VK_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_OPAQUE_KHR VkOpacityMicromapSpecialIndexKHR = -4
)

type VkOpticalFlowPerformanceLevelNV VkEnum
const (
	VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_UNKNOWN_NV VkOpticalFlowPerformanceLevelNV = 0
	VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_SLOW_NV VkOpticalFlowPerformanceLevelNV = 1
	VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_MEDIUM_NV VkOpticalFlowPerformanceLevelNV = 2
	VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_FAST_NV VkOpticalFlowPerformanceLevelNV = 3
)

type VkOpticalFlowSessionBindingPointNV VkEnum
const (
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_UNKNOWN_NV VkOpticalFlowSessionBindingPointNV = 0
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NV VkOpticalFlowSessionBindingPointNV = 1
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NV VkOpticalFlowSessionBindingPointNV = 2
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NV VkOpticalFlowSessionBindingPointNV = 3
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NV VkOpticalFlowSessionBindingPointNV = 4
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NV VkOpticalFlowSessionBindingPointNV = 5
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV VkOpticalFlowSessionBindingPointNV = 6
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV VkOpticalFlowSessionBindingPointNV = 7
	VK_OPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV VkOpticalFlowSessionBindingPointNV = 8
)

type VkOutOfBandQueueTypeNV VkEnum
const (
	VK_OUT_OF_BAND_QUEUE_TYPE_RENDER_NV VkOutOfBandQueueTypeNV = 0
	VK_OUT_OF_BAND_QUEUE_TYPE_PRESENT_NV VkOutOfBandQueueTypeNV = 1
)

type VkPartitionedAccelerationStructureOpTypeNV VkEnum
const (
	VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_INSTANCE_NV VkPartitionedAccelerationStructureOpTypeNV = 0
	VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_UPDATE_INSTANCE_NV VkPartitionedAccelerationStructureOpTypeNV = 1
	VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_PARTITION_TRANSLATION_NV VkPartitionedAccelerationStructureOpTypeNV = 2
)

type VkPerfHintTypeQCOM VkEnum
const (
	VK_PERF_HINT_TYPE_DEFAULT_QCOM VkPerfHintTypeQCOM = 0
	VK_PERF_HINT_TYPE_FREQUENCY_MIN_QCOM VkPerfHintTypeQCOM = 1
	VK_PERF_HINT_TYPE_FREQUENCY_MAX_QCOM VkPerfHintTypeQCOM = 2
	VK_PERF_HINT_TYPE_FREQUENCY_SCALED_QCOM VkPerfHintTypeQCOM = 3
)

type VkPerformanceConfigurationTypeINTEL VkEnum
const (
	VK_PERFORMANCE_CONFIGURATION_TYPE_COMMAND_QUEUE_METRICS_DISCOVERY_ACTIVATED_INTEL VkPerformanceConfigurationTypeINTEL = 0
)

type VkPerformanceCounterScopeKHR VkEnum
const (
	VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHR VkPerformanceCounterScopeKHR = 0
	VK_PERFORMANCE_COUNTER_SCOPE_RENDER_PASS_KHR VkPerformanceCounterScopeKHR = 1
	VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_KHR VkPerformanceCounterScopeKHR = 2
)

type VkPerformanceCounterStorageKHR VkEnum
const (
	VK_PERFORMANCE_COUNTER_STORAGE_INT32_KHR VkPerformanceCounterStorageKHR = 0
	VK_PERFORMANCE_COUNTER_STORAGE_INT64_KHR VkPerformanceCounterStorageKHR = 1
	VK_PERFORMANCE_COUNTER_STORAGE_UINT32_KHR VkPerformanceCounterStorageKHR = 2
	VK_PERFORMANCE_COUNTER_STORAGE_UINT64_KHR VkPerformanceCounterStorageKHR = 3
	VK_PERFORMANCE_COUNTER_STORAGE_FLOAT32_KHR VkPerformanceCounterStorageKHR = 4
	VK_PERFORMANCE_COUNTER_STORAGE_FLOAT64_KHR VkPerformanceCounterStorageKHR = 5
)

type VkPerformanceCounterUnitKHR VkEnum
const (
	VK_PERFORMANCE_COUNTER_UNIT_GENERIC_KHR VkPerformanceCounterUnitKHR = 0
	VK_PERFORMANCE_COUNTER_UNIT_PERCENTAGE_KHR VkPerformanceCounterUnitKHR = 1
	VK_PERFORMANCE_COUNTER_UNIT_NANOSECONDS_KHR VkPerformanceCounterUnitKHR = 2
	VK_PERFORMANCE_COUNTER_UNIT_BYTES_KHR VkPerformanceCounterUnitKHR = 3
	VK_PERFORMANCE_COUNTER_UNIT_BYTES_PER_SECOND_KHR VkPerformanceCounterUnitKHR = 4
	VK_PERFORMANCE_COUNTER_UNIT_KELVIN_KHR VkPerformanceCounterUnitKHR = 5
	VK_PERFORMANCE_COUNTER_UNIT_WATTS_KHR VkPerformanceCounterUnitKHR = 6
	VK_PERFORMANCE_COUNTER_UNIT_VOLTS_KHR VkPerformanceCounterUnitKHR = 7
	VK_PERFORMANCE_COUNTER_UNIT_AMPS_KHR VkPerformanceCounterUnitKHR = 8
	VK_PERFORMANCE_COUNTER_UNIT_HERTZ_KHR VkPerformanceCounterUnitKHR = 9
	VK_PERFORMANCE_COUNTER_UNIT_CYCLES_KHR VkPerformanceCounterUnitKHR = 10
)

type VkPerformanceOverrideTypeINTEL VkEnum
const (
	VK_PERFORMANCE_OVERRIDE_TYPE_NULL_HARDWARE_INTEL VkPerformanceOverrideTypeINTEL = 0
	VK_PERFORMANCE_OVERRIDE_TYPE_FLUSH_GPU_CACHES_INTEL VkPerformanceOverrideTypeINTEL = 1
)

type VkPerformanceParameterTypeINTEL VkEnum
const (
	VK_PERFORMANCE_PARAMETER_TYPE_HW_COUNTERS_SUPPORTED_INTEL VkPerformanceParameterTypeINTEL = 0
	VK_PERFORMANCE_PARAMETER_TYPE_STREAM_MARKER_VALID_BITS_INTEL VkPerformanceParameterTypeINTEL = 1
)

type VkPerformanceValueTypeINTEL VkEnum
const (
	VK_PERFORMANCE_VALUE_TYPE_UINT32_INTEL VkPerformanceValueTypeINTEL = 0
	VK_PERFORMANCE_VALUE_TYPE_UINT64_INTEL VkPerformanceValueTypeINTEL = 1
	VK_PERFORMANCE_VALUE_TYPE_FLOAT_INTEL VkPerformanceValueTypeINTEL = 2
	VK_PERFORMANCE_VALUE_TYPE_BOOL_INTEL VkPerformanceValueTypeINTEL = 3
	VK_PERFORMANCE_VALUE_TYPE_STRING_INTEL VkPerformanceValueTypeINTEL = 4
)

type VkPhysicalDeviceDataGraphOperationTypeARM VkEnum
const (
	VK_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_TYPE_SPIRV_EXTENDED_INSTRUCTION_SET_ARM VkPhysicalDeviceDataGraphOperationTypeARM = 0
)

type VkPhysicalDeviceDataGraphProcessingEngineTypeARM VkEnum
const (
	VK_PHYSICAL_DEVICE_DATA_GRAPH_PROCESSING_ENGINE_TYPE_DEFAULT_ARM VkPhysicalDeviceDataGraphProcessingEngineTypeARM = 0
)

type VkPhysicalDeviceLayeredApiKHR VkEnum
const (
	VK_PHYSICAL_DEVICE_LAYERED_API_VULKAN_KHR VkPhysicalDeviceLayeredApiKHR = 0
	VK_PHYSICAL_DEVICE_LAYERED_API_D3D12_KHR VkPhysicalDeviceLayeredApiKHR = 1
	VK_PHYSICAL_DEVICE_LAYERED_API_METAL_KHR VkPhysicalDeviceLayeredApiKHR = 2
	VK_PHYSICAL_DEVICE_LAYERED_API_OPENGL_KHR VkPhysicalDeviceLayeredApiKHR = 3
	VK_PHYSICAL_DEVICE_LAYERED_API_OPENGLES_KHR VkPhysicalDeviceLayeredApiKHR = 4
)

type VkPhysicalDeviceType VkEnum
const (
	VK_PHYSICAL_DEVICE_TYPE_OTHER VkPhysicalDeviceType = 0
	VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU VkPhysicalDeviceType = 1
	VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU VkPhysicalDeviceType = 2
	VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU VkPhysicalDeviceType = 3
	VK_PHYSICAL_DEVICE_TYPE_CPU VkPhysicalDeviceType = 4
)

type VkPipelineBindPoint VkEnum
const (
	VK_PIPELINE_BIND_POINT_GRAPHICS VkPipelineBindPoint = 0
	VK_PIPELINE_BIND_POINT_COMPUTE VkPipelineBindPoint = 1
)

type VkPipelineCacheHeaderVersion VkEnum
const (
	VK_PIPELINE_CACHE_HEADER_VERSION_ONE VkPipelineCacheHeaderVersion = 1
)

type VkPipelineCacheValidationVersion VkEnum
const (
	VK_PIPELINE_CACHE_VALIDATION_VERSION_SAFETY_CRITICAL_ONE VkPipelineCacheValidationVersion = 1
)

type VkPipelineExecutableStatisticFormatKHR VkEnum
const (
	VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_BOOL32_KHR VkPipelineExecutableStatisticFormatKHR = 0
	VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_INT64_KHR VkPipelineExecutableStatisticFormatKHR = 1
	VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_UINT64_KHR VkPipelineExecutableStatisticFormatKHR = 2
	VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_FLOAT64_KHR VkPipelineExecutableStatisticFormatKHR = 3
)

type VkPipelineMatchControl VkEnum
const (
	VK_PIPELINE_MATCH_CONTROL_APPLICATION_UUID_EXACT_MATCH VkPipelineMatchControl = 0
)

type VkPipelineRobustnessBufferBehavior VkEnum
const (
	VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DEVICE_DEFAULT VkPipelineRobustnessBufferBehavior = 0
	VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_DISABLED VkPipelineRobustnessBufferBehavior = 1
	VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS VkPipelineRobustnessBufferBehavior = 2
	VK_PIPELINE_ROBUSTNESS_BUFFER_BEHAVIOR_ROBUST_BUFFER_ACCESS_2 VkPipelineRobustnessBufferBehavior = 3
)

type VkPipelineRobustnessImageBehavior VkEnum
const (
	VK_PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DEVICE_DEFAULT VkPipelineRobustnessImageBehavior = 0
	VK_PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_DISABLED VkPipelineRobustnessImageBehavior = 1
	VK_PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESS VkPipelineRobustnessImageBehavior = 2
	VK_PIPELINE_ROBUSTNESS_IMAGE_BEHAVIOR_ROBUST_IMAGE_ACCESS_2 VkPipelineRobustnessImageBehavior = 3
)

type VkPointClippingBehavior VkEnum
const (
	VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES VkPointClippingBehavior = 0
	VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY VkPointClippingBehavior = 1
)

type VkPolygonMode VkEnum
const (
	VK_POLYGON_MODE_FILL VkPolygonMode = 0
	VK_POLYGON_MODE_LINE VkPolygonMode = 1
	VK_POLYGON_MODE_POINT VkPolygonMode = 2
)

type VkPresentModeKHR VkEnum
const (
	VK_PRESENT_MODE_IMMEDIATE_KHR VkPresentModeKHR = 0
	VK_PRESENT_MODE_MAILBOX_KHR VkPresentModeKHR = 1
	VK_PRESENT_MODE_FIFO_KHR VkPresentModeKHR = 2
	VK_PRESENT_MODE_FIFO_RELAXED_KHR VkPresentModeKHR = 3
)

type VkPrimitiveTopology VkEnum
const (
	VK_PRIMITIVE_TOPOLOGY_POINT_LIST VkPrimitiveTopology = 0
	VK_PRIMITIVE_TOPOLOGY_LINE_LIST VkPrimitiveTopology = 1
	VK_PRIMITIVE_TOPOLOGY_LINE_STRIP VkPrimitiveTopology = 2
	VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST VkPrimitiveTopology = 3
	VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP VkPrimitiveTopology = 4
	VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN VkPrimitiveTopology = 5
	VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY VkPrimitiveTopology = 6
	VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY VkPrimitiveTopology = 7
	VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY VkPrimitiveTopology = 8
	VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY VkPrimitiveTopology = 9
	VK_PRIMITIVE_TOPOLOGY_PATCH_LIST VkPrimitiveTopology = 10
)

type VkProvokingVertexModeEXT VkEnum
const (
	VK_PROVOKING_VERTEX_MODE_FIRST_VERTEX_EXT VkProvokingVertexModeEXT = 0
	VK_PROVOKING_VERTEX_MODE_LAST_VERTEX_EXT VkProvokingVertexModeEXT = 1
)

type VkQueryPoolSamplingModeINTEL VkEnum
const (
	VK_QUERY_POOL_SAMPLING_MODE_MANUAL_INTEL VkQueryPoolSamplingModeINTEL = 0
)

type VkQueryResultStatusKHR VkEnum
const (
	VK_QUERY_RESULT_STATUS_ERROR_KHR VkQueryResultStatusKHR = -1
	VK_QUERY_RESULT_STATUS_NOT_READY_KHR VkQueryResultStatusKHR = 0
	VK_QUERY_RESULT_STATUS_COMPLETE_KHR VkQueryResultStatusKHR = 1
)

type VkQueryType VkEnum
const (
	VK_QUERY_TYPE_OCCLUSION VkQueryType = 0

	/*
	VK_QUERY_TYPE_PIPELINE_STATISTICS Optional
	*/
	VK_QUERY_TYPE_PIPELINE_STATISTICS VkQueryType = 1
	VK_QUERY_TYPE_TIMESTAMP VkQueryType = 2
)

type VkQueueGlobalPriority VkEnum
const (
	VK_QUEUE_GLOBAL_PRIORITY_LOW VkQueueGlobalPriority = 128
	VK_QUEUE_GLOBAL_PRIORITY_MEDIUM VkQueueGlobalPriority = 256
	VK_QUEUE_GLOBAL_PRIORITY_HIGH VkQueueGlobalPriority = 512
	VK_QUEUE_GLOBAL_PRIORITY_REALTIME VkQueueGlobalPriority = 1024
)

type VkRasterizationOrderAMD VkEnum
const (
	VK_RASTERIZATION_ORDER_STRICT_AMD VkRasterizationOrderAMD = 0
	VK_RASTERIZATION_ORDER_RELAXED_AMD VkRasterizationOrderAMD = 1
)

type VkRayTracingInvocationReorderModeEXT VkEnum
const (
	VK_RAY_TRACING_INVOCATION_REORDER_MODE_NONE_EXT VkRayTracingInvocationReorderModeEXT = 0
	VK_RAY_TRACING_INVOCATION_REORDER_MODE_REORDER_EXT VkRayTracingInvocationReorderModeEXT = 1
)

type VkRayTracingLssIndexingModeNV VkEnum
const (
	VK_RAY_TRACING_LSS_INDEXING_MODE_LIST_NV VkRayTracingLssIndexingModeNV = 0
	VK_RAY_TRACING_LSS_INDEXING_MODE_SUCCESSIVE_NV VkRayTracingLssIndexingModeNV = 1
)

type VkRayTracingLssPrimitiveEndCapsModeNV VkEnum
const (
	VK_RAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_NONE_NV VkRayTracingLssPrimitiveEndCapsModeNV = 0
	VK_RAY_TRACING_LSS_PRIMITIVE_END_CAPS_MODE_CHAINED_NV VkRayTracingLssPrimitiveEndCapsModeNV = 1
)

type VkRayTracingShaderGroupTypeKHR VkEnum
const (
	VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR VkRayTracingShaderGroupTypeKHR = 0
	VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_KHR VkRayTracingShaderGroupTypeKHR = 1
	VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR VkRayTracingShaderGroupTypeKHR = 2
)

/*
VkResult API result codes
*/
type VkResult VkEnum
const (
	/*
	VK_SUCCESS Return codes (positive values)
	
	Command completed successfully
	*/
	VK_SUCCESS VkResult = 0

	/*
	VK_NOT_READY Return codes (positive values)
	
	A fence or query has not yet completed
	*/
	VK_NOT_READY VkResult = 1

	/*
	VK_TIMEOUT Return codes (positive values)
	
	A wait operation has not completed in the specified time
	*/
	VK_TIMEOUT VkResult = 2

	/*
	VK_EVENT_SET Return codes (positive values)
	
	An event is signaled
	*/
	VK_EVENT_SET VkResult = 3

	/*
	VK_EVENT_RESET Return codes (positive values)
	
	An event is unsignaled
	*/
	VK_EVENT_RESET VkResult = 4

	/*
	VK_INCOMPLETE Return codes (positive values)
	
	A return array was too small for the result
	*/
	VK_INCOMPLETE VkResult = 5

	/*
	VK_ERROR_OUT_OF_HOST_MEMORY Error codes (negative values)
	
	A host memory allocation has failed
	*/
	VK_ERROR_OUT_OF_HOST_MEMORY VkResult = -1

	/*
	VK_ERROR_OUT_OF_DEVICE_MEMORY Error codes (negative values)
	
	A device memory allocation has failed
	*/
	VK_ERROR_OUT_OF_DEVICE_MEMORY VkResult = -2

	/*
	VK_ERROR_INITIALIZATION_FAILED Error codes (negative values)
	
	Initialization of an object has failed
	*/
	VK_ERROR_INITIALIZATION_FAILED VkResult = -3

	/*
	VK_ERROR_DEVICE_LOST Error codes (negative values)
	
	The logical device has been lost. See <<devsandqueues-lost-device>>
	*/
	VK_ERROR_DEVICE_LOST VkResult = -4

	/*
	VK_ERROR_MEMORY_MAP_FAILED Error codes (negative values)
	
	Mapping of a memory object has failed
	*/
	VK_ERROR_MEMORY_MAP_FAILED VkResult = -5

	/*
	VK_ERROR_LAYER_NOT_PRESENT Error codes (negative values)
	
	Layer specified does not exist
	*/
	VK_ERROR_LAYER_NOT_PRESENT VkResult = -6

	/*
	VK_ERROR_EXTENSION_NOT_PRESENT Error codes (negative values)
	
	Extension specified does not exist
	*/
	VK_ERROR_EXTENSION_NOT_PRESENT VkResult = -7

	/*
	VK_ERROR_FEATURE_NOT_PRESENT Error codes (negative values)
	
	Requested feature is not available on this device
	*/
	VK_ERROR_FEATURE_NOT_PRESENT VkResult = -8

	/*
	VK_ERROR_INCOMPATIBLE_DRIVER Error codes (negative values)
	
	Unable to find a Vulkan driver
	*/
	VK_ERROR_INCOMPATIBLE_DRIVER VkResult = -9

	/*
	VK_ERROR_TOO_MANY_OBJECTS Error codes (negative values)
	
	Too many objects of the type have already been created
	*/
	VK_ERROR_TOO_MANY_OBJECTS VkResult = -10

	/*
	VK_ERROR_FORMAT_NOT_SUPPORTED Error codes (negative values)
	
	Requested format is not supported on this device
	*/
	VK_ERROR_FORMAT_NOT_SUPPORTED VkResult = -11

	/*
	VK_ERROR_FRAGMENTED_POOL Error codes (negative values)
	
	A requested pool allocation has failed due to fragmentation of the pool's memory
	*/
	VK_ERROR_FRAGMENTED_POOL VkResult = -12

	/*
	VK_ERROR_UNKNOWN Error codes (negative values)
	
	An unknown error has occurred, due to an implementation or application bug
	*/
	VK_ERROR_UNKNOWN VkResult = -13
)

type VkSamplerAddressMode VkEnum
const (
	VK_SAMPLER_ADDRESS_MODE_REPEAT VkSamplerAddressMode = 0
	VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT VkSamplerAddressMode = 1
	VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE VkSamplerAddressMode = 2
	VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER VkSamplerAddressMode = 3
)

type VkSamplerMipmapMode VkEnum
const (
	/*
	VK_SAMPLER_MIPMAP_MODE_NEAREST Choose nearest mip level
	*/
	VK_SAMPLER_MIPMAP_MODE_NEAREST VkSamplerMipmapMode = 0

	/*
	VK_SAMPLER_MIPMAP_MODE_LINEAR Linear filter between mip levels
	*/
	VK_SAMPLER_MIPMAP_MODE_LINEAR VkSamplerMipmapMode = 1
)

type VkSamplerReductionMode VkEnum
const (
	VK_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE VkSamplerReductionMode = 0
	VK_SAMPLER_REDUCTION_MODE_MIN VkSamplerReductionMode = 1
	VK_SAMPLER_REDUCTION_MODE_MAX VkSamplerReductionMode = 2
)

type VkSamplerYcbcrModelConversion VkEnum
const (
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY VkSamplerYcbcrModelConversion = 0

	/*
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY just range expansion
	*/
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY VkSamplerYcbcrModelConversion = 1

	/*
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709 aka HD YUV
	*/
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709 VkSamplerYcbcrModelConversion = 2

	/*
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601 aka SD YUV
	*/
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601 VkSamplerYcbcrModelConversion = 3

	/*
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020 aka UHD YUV
	*/
	VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020 VkSamplerYcbcrModelConversion = 4
)

type VkSamplerYcbcrRange VkEnum
const (
	/*
	VK_SAMPLER_YCBCR_RANGE_ITU_FULL Luma 0..1 maps to 0..255, chroma -0.5..0.5 to 1..255 (clamped)
	*/
	VK_SAMPLER_YCBCR_RANGE_ITU_FULL VkSamplerYcbcrRange = 0

	/*
	VK_SAMPLER_YCBCR_RANGE_ITU_NARROW Luma 0..1 maps to 16..235, chroma -0.5..0.5 to 16..240
	*/
	VK_SAMPLER_YCBCR_RANGE_ITU_NARROW VkSamplerYcbcrRange = 1
)

type VkSciSyncClientTypeNV VkEnum
const (
	VK_SCI_SYNC_CLIENT_TYPE_SIGNALER_NV VkSciSyncClientTypeNV = 0
	VK_SCI_SYNC_CLIENT_TYPE_WAITER_NV VkSciSyncClientTypeNV = 1
	VK_SCI_SYNC_CLIENT_TYPE_SIGNALER_WAITER_NV VkSciSyncClientTypeNV = 2
)

type VkSciSyncPrimitiveTypeNV VkEnum
const (
	VK_SCI_SYNC_PRIMITIVE_TYPE_FENCE_NV VkSciSyncPrimitiveTypeNV = 0
	VK_SCI_SYNC_PRIMITIVE_TYPE_SEMAPHORE_NV VkSciSyncPrimitiveTypeNV = 1
)

type VkScopeKHR VkEnum
const (
	VK_SCOPE_DEVICE_KHR VkScopeKHR = 1
	VK_SCOPE_WORKGROUP_KHR VkScopeKHR = 2
	VK_SCOPE_SUBGROUP_KHR VkScopeKHR = 3
	VK_SCOPE_QUEUE_FAMILY_KHR VkScopeKHR = 5
)

type VkSemaphoreType VkEnum
const (
	VK_SEMAPHORE_TYPE_BINARY VkSemaphoreType = 0
	VK_SEMAPHORE_TYPE_TIMELINE VkSemaphoreType = 1
)

type VkShaderCodeTypeEXT VkEnum
const (
	VK_SHADER_CODE_TYPE_BINARY_EXT VkShaderCodeTypeEXT = 0
	VK_SHADER_CODE_TYPE_SPIRV_EXT VkShaderCodeTypeEXT = 1
)

type VkShaderFloatControlsIndependence VkEnum
const (
	VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_32_BIT_ONLY VkShaderFloatControlsIndependence = 0
	VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_ALL VkShaderFloatControlsIndependence = 1
	VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_NONE VkShaderFloatControlsIndependence = 2
)

type VkShaderGroupShaderKHR VkEnum
const (
	VK_SHADER_GROUP_SHADER_GENERAL_KHR VkShaderGroupShaderKHR = 0
	VK_SHADER_GROUP_SHADER_CLOSEST_HIT_KHR VkShaderGroupShaderKHR = 1
	VK_SHADER_GROUP_SHADER_ANY_HIT_KHR VkShaderGroupShaderKHR = 2
	VK_SHADER_GROUP_SHADER_INTERSECTION_KHR VkShaderGroupShaderKHR = 3
)

type VkShaderInfoTypeAMD VkEnum
const (
	VK_SHADER_INFO_TYPE_STATISTICS_AMD VkShaderInfoTypeAMD = 0
	VK_SHADER_INFO_TYPE_BINARY_AMD VkShaderInfoTypeAMD = 1
	VK_SHADER_INFO_TYPE_DISASSEMBLY_AMD VkShaderInfoTypeAMD = 2
)

type VkShadingRatePaletteEntryNV VkEnum
const (
	VK_SHADING_RATE_PALETTE_ENTRY_NO_INVOCATIONS_NV VkShadingRatePaletteEntryNV = 0
	VK_SHADING_RATE_PALETTE_ENTRY_16_INVOCATIONS_PER_PIXEL_NV VkShadingRatePaletteEntryNV = 1
	VK_SHADING_RATE_PALETTE_ENTRY_8_INVOCATIONS_PER_PIXEL_NV VkShadingRatePaletteEntryNV = 2
	VK_SHADING_RATE_PALETTE_ENTRY_4_INVOCATIONS_PER_PIXEL_NV VkShadingRatePaletteEntryNV = 3
	VK_SHADING_RATE_PALETTE_ENTRY_2_INVOCATIONS_PER_PIXEL_NV VkShadingRatePaletteEntryNV = 4
	VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_PIXEL_NV VkShadingRatePaletteEntryNV = 5
	VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_2X1_PIXELS_NV VkShadingRatePaletteEntryNV = 6
	VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_1X2_PIXELS_NV VkShadingRatePaletteEntryNV = 7
	VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_2X2_PIXELS_NV VkShadingRatePaletteEntryNV = 8
	VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_4X2_PIXELS_NV VkShadingRatePaletteEntryNV = 9
	VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_2X4_PIXELS_NV VkShadingRatePaletteEntryNV = 10
	VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_4X4_PIXELS_NV VkShadingRatePaletteEntryNV = 11
)

type VkSharingMode VkEnum
const (
	VK_SHARING_MODE_EXCLUSIVE VkSharingMode = 0
	VK_SHARING_MODE_CONCURRENT VkSharingMode = 1
)

type VkStencilOp VkEnum
const (
	VK_STENCIL_OP_KEEP VkStencilOp = 0
	VK_STENCIL_OP_ZERO VkStencilOp = 1
	VK_STENCIL_OP_REPLACE VkStencilOp = 2
	VK_STENCIL_OP_INCREMENT_AND_CLAMP VkStencilOp = 3
	VK_STENCIL_OP_DECREMENT_AND_CLAMP VkStencilOp = 4
	VK_STENCIL_OP_INVERT VkStencilOp = 5
	VK_STENCIL_OP_INCREMENT_AND_WRAP VkStencilOp = 6
	VK_STENCIL_OP_DECREMENT_AND_WRAP VkStencilOp = 7
)

/*
VkStructureType Structure type enumerant
*/
type VkStructureType VkEnum
const (
	VK_STRUCTURE_TYPE_APPLICATION_INFO VkStructureType = 0
	VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO VkStructureType = 1
	VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO VkStructureType = 2
	VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO VkStructureType = 3
	VK_STRUCTURE_TYPE_SUBMIT_INFO VkStructureType = 4
	VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO VkStructureType = 5
	VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE VkStructureType = 6
	VK_STRUCTURE_TYPE_BIND_SPARSE_INFO VkStructureType = 7
	VK_STRUCTURE_TYPE_FENCE_CREATE_INFO VkStructureType = 8
	VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO VkStructureType = 9
	VK_STRUCTURE_TYPE_EVENT_CREATE_INFO VkStructureType = 10
	VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO VkStructureType = 11
	VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO VkStructureType = 12
	VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO VkStructureType = 13
	VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO VkStructureType = 14
	VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO VkStructureType = 15
	VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO VkStructureType = 16
	VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO VkStructureType = 17
	VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO VkStructureType = 18
	VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO VkStructureType = 19
	VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO VkStructureType = 20
	VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO VkStructureType = 21
	VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO VkStructureType = 22
	VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO VkStructureType = 23
	VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO VkStructureType = 24
	VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO VkStructureType = 25
	VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO VkStructureType = 26
	VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO VkStructureType = 27
	VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO VkStructureType = 28
	VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO VkStructureType = 29
	VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO VkStructureType = 30
	VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO VkStructureType = 31
	VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO VkStructureType = 32
	VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO VkStructureType = 33
	VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO VkStructureType = 34
	VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET VkStructureType = 35
	VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET VkStructureType = 36
	VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO VkStructureType = 37
	VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO VkStructureType = 38
	VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO VkStructureType = 39
	VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO VkStructureType = 40
	VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO VkStructureType = 41
	VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO VkStructureType = 42
	VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO VkStructureType = 43
	VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER VkStructureType = 44
	VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER VkStructureType = 45
	VK_STRUCTURE_TYPE_MEMORY_BARRIER VkStructureType = 46

	/*
	VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO Reserved for internal use by the loader, layers, and ICDs
	*/
	VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO VkStructureType = 47

	/*
	VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO Reserved for internal use by the loader, layers, and ICDs
	*/
	VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO VkStructureType = 48
)

type VkSubpassContents VkEnum
const (
	VK_SUBPASS_CONTENTS_INLINE VkSubpassContents = 0
	VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS VkSubpassContents = 1
)

type VkSubpassMergeStatusEXT VkEnum
const (
	VK_SUBPASS_MERGE_STATUS_MERGED_EXT VkSubpassMergeStatusEXT = 0
	VK_SUBPASS_MERGE_STATUS_DISALLOWED_EXT VkSubpassMergeStatusEXT = 1
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SIDE_EFFECTS_EXT VkSubpassMergeStatusEXT = 2
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SAMPLES_MISMATCH_EXT VkSubpassMergeStatusEXT = 3
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_VIEWS_MISMATCH_EXT VkSubpassMergeStatusEXT = 4
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_ALIASING_EXT VkSubpassMergeStatusEXT = 5
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_DEPENDENCIES_EXT VkSubpassMergeStatusEXT = 6
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_INCOMPATIBLE_INPUT_ATTACHMENT_EXT VkSubpassMergeStatusEXT = 7
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_TOO_MANY_ATTACHMENTS_EXT VkSubpassMergeStatusEXT = 8
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_INSUFFICIENT_STORAGE_EXT VkSubpassMergeStatusEXT = 9
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_DEPTH_STENCIL_COUNT_EXT VkSubpassMergeStatusEXT = 10
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_RESOLVE_ATTACHMENT_REUSE_EXT VkSubpassMergeStatusEXT = 11
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SINGLE_SUBPASS_EXT VkSubpassMergeStatusEXT = 12
	VK_SUBPASS_MERGE_STATUS_NOT_MERGED_UNSPECIFIED_EXT VkSubpassMergeStatusEXT = 13
)

type VkSystemAllocationScope VkEnum
const (
	VK_SYSTEM_ALLOCATION_SCOPE_COMMAND VkSystemAllocationScope = 0
	VK_SYSTEM_ALLOCATION_SCOPE_OBJECT VkSystemAllocationScope = 1
	VK_SYSTEM_ALLOCATION_SCOPE_CACHE VkSystemAllocationScope = 2
	VK_SYSTEM_ALLOCATION_SCOPE_DEVICE VkSystemAllocationScope = 3
	VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE VkSystemAllocationScope = 4
)

type VkTensorTilingARM VkEnum
const (
	VK_TENSOR_TILING_OPTIMAL_ARM VkTensorTilingARM = 0
	VK_TENSOR_TILING_LINEAR_ARM VkTensorTilingARM = 1
)

type VkTessellationDomainOrigin VkEnum
const (
	VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT VkTessellationDomainOrigin = 0
	VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT VkTessellationDomainOrigin = 1
)

type VkThrottleHintTypeSEC VkEnum
const (
	VK_THROTTLE_HINT_TYPE_DEFAULT_SEC VkThrottleHintTypeSEC = 0
	VK_THROTTLE_HINT_TYPE_LOW_SEC VkThrottleHintTypeSEC = 1
	VK_THROTTLE_HINT_TYPE_HIGH_SEC VkThrottleHintTypeSEC = 2
)

type VkTimeDomainKHR VkEnum
const (
	VK_TIME_DOMAIN_DEVICE_KHR VkTimeDomainKHR = 0
	VK_TIME_DOMAIN_CLOCK_MONOTONIC_KHR VkTimeDomainKHR = 1
	VK_TIME_DOMAIN_CLOCK_MONOTONIC_RAW_KHR VkTimeDomainKHR = 2
	VK_TIME_DOMAIN_QUERY_PERFORMANCE_COUNTER_KHR VkTimeDomainKHR = 3
)

type VkValidationCacheHeaderVersionEXT VkEnum
const (
	VK_VALIDATION_CACHE_HEADER_VERSION_ONE_EXT VkValidationCacheHeaderVersionEXT = 1
)

type VkValidationCheckEXT VkEnum
const (
	VK_VALIDATION_CHECK_ALL_EXT VkValidationCheckEXT = 0
	VK_VALIDATION_CHECK_SHADERS_EXT VkValidationCheckEXT = 1
)

type VkValidationFeatureDisableEXT VkEnum
const (
	VK_VALIDATION_FEATURE_DISABLE_ALL_EXT VkValidationFeatureDisableEXT = 0
	VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT VkValidationFeatureDisableEXT = 1
	VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT VkValidationFeatureDisableEXT = 2
	VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT VkValidationFeatureDisableEXT = 3
	VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT VkValidationFeatureDisableEXT = 4
	VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT VkValidationFeatureDisableEXT = 5
	VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT VkValidationFeatureDisableEXT = 6
	VK_VALIDATION_FEATURE_DISABLE_SHADER_VALIDATION_CACHE_EXT VkValidationFeatureDisableEXT = 7
)

type VkValidationFeatureEnableEXT VkEnum
const (
	VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT VkValidationFeatureEnableEXT = 0
	VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT VkValidationFeatureEnableEXT = 1
	VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT VkValidationFeatureEnableEXT = 2
	VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT VkValidationFeatureEnableEXT = 3
	VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT VkValidationFeatureEnableEXT = 4
)

type VkVendorId VkEnum
const (
	/*
	VK_VENDOR_ID_KHRONOS Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	Khronos vendor ID
	*/
	VK_VENDOR_ID_KHRONOS VkVendorId = 0x10000

	/*
	VK_VENDOR_ID_VIV Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	Vivante vendor ID
	*/
	VK_VENDOR_ID_VIV VkVendorId = 0x10001

	/*
	VK_VENDOR_ID_VSI Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	VeriSilicon vendor ID
	*/
	VK_VENDOR_ID_VSI VkVendorId = 0x10002

	/*
	VK_VENDOR_ID_KAZAN Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	Kazan Software Renderer
	*/
	VK_VENDOR_ID_KAZAN VkVendorId = 0x10003

	/*
	VK_VENDOR_ID_CODEPLAY Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	Codeplay Software Ltd. vendor ID
	*/
	VK_VENDOR_ID_CODEPLAY VkVendorId = 0x10004

	/*
	VK_VENDOR_ID_MESA Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	Mesa vendor ID
	*/
	VK_VENDOR_ID_MESA VkVendorId = 0x10005

	/*
	VK_VENDOR_ID_POCL Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	PoCL vendor ID
	*/
	VK_VENDOR_ID_POCL VkVendorId = 0x10006

	/*
	VK_VENDOR_ID_MOBILEYE Vendor IDs are now represented as enums instead of the old
	                 <vendorids> tag, allowing them to be included in the
	                 API headers.
	
	Mobileye vendor ID
	*/
	VK_VENDOR_ID_MOBILEYE VkVendorId = 0x10007
)

type VkVertexInputRate VkEnum
const (
	VK_VERTEX_INPUT_RATE_VERTEX VkVertexInputRate = 0
	VK_VERTEX_INPUT_RATE_INSTANCE VkVertexInputRate = 1
)

type VkVideoEncodeAV1PredictionModeKHR VkEnum
const (
	VK_VIDEO_ENCODE_AV1_PREDICTION_MODE_INTRA_ONLY_KHR VkVideoEncodeAV1PredictionModeKHR = 0
	VK_VIDEO_ENCODE_AV1_PREDICTION_MODE_SINGLE_REFERENCE_KHR VkVideoEncodeAV1PredictionModeKHR = 1
	VK_VIDEO_ENCODE_AV1_PREDICTION_MODE_UNIDIRECTIONAL_COMPOUND_KHR VkVideoEncodeAV1PredictionModeKHR = 2
	VK_VIDEO_ENCODE_AV1_PREDICTION_MODE_BIDIRECTIONAL_COMPOUND_KHR VkVideoEncodeAV1PredictionModeKHR = 3
)

type VkVideoEncodeAV1RateControlGroupKHR VkEnum
const (
	VK_VIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_INTRA_KHR VkVideoEncodeAV1RateControlGroupKHR = 0
	VK_VIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_PREDICTIVE_KHR VkVideoEncodeAV1RateControlGroupKHR = 1
	VK_VIDEO_ENCODE_AV1_RATE_CONTROL_GROUP_BIPREDICTIVE_KHR VkVideoEncodeAV1RateControlGroupKHR = 2
)

type VkVideoEncodeTuningModeKHR VkEnum
const (
	VK_VIDEO_ENCODE_TUNING_MODE_DEFAULT_KHR VkVideoEncodeTuningModeKHR = 0
	VK_VIDEO_ENCODE_TUNING_MODE_HIGH_QUALITY_KHR VkVideoEncodeTuningModeKHR = 1
	VK_VIDEO_ENCODE_TUNING_MODE_LOW_LATENCY_KHR VkVideoEncodeTuningModeKHR = 2
	VK_VIDEO_ENCODE_TUNING_MODE_ULTRA_LOW_LATENCY_KHR VkVideoEncodeTuningModeKHR = 3
	VK_VIDEO_ENCODE_TUNING_MODE_LOSSLESS_KHR VkVideoEncodeTuningModeKHR = 4
)

type VkViewportCoordinateSwizzleNV VkEnum
const (
	VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV VkViewportCoordinateSwizzleNV = 0
	VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV VkViewportCoordinateSwizzleNV = 1
	VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV VkViewportCoordinateSwizzleNV = 2
	VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV VkViewportCoordinateSwizzleNV = 3
	VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV VkViewportCoordinateSwizzleNV = 4
	VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV VkViewportCoordinateSwizzleNV = 5
	VK_VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV VkViewportCoordinateSwizzleNV = 6
	VK_VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV VkViewportCoordinateSwizzleNV = 7
)

