// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-22 21:41:53 CEST

package bindings

/*
VkBool32 is generated from the Khronos Vulkan registry.

[Context]
Vulkan boolean type

[Description]
VK_TRUE represents a boolean True (unsigned integer 1) value, and
VK_FALSE a boolean False (unsigned integer 0) value.

All values returned from a Vulkan implementation in a VkBool32 will
be either VK_TRUE or VK_FALSE.

Applications must not pass any other values than VK_TRUE or
VK_FALSE into a Vulkan implementation where a VkBool32 is
expected.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkBool32.html
*/
type VkBool32 = uint32

/*
VkDeviceAddress is generated from the Khronos Vulkan registry.

[Context]
Vulkan device address type

[Valid Usage]

- A valid VkDeviceAddress must be equal to the sum of an address retrieved from a VkBuffer via vkGetBufferDeviceAddress, and any offset in the range [0, size), where size is the value of VkBufferCreateInfo::size used to create that VkBuffer

- If a VkDeviceAddress was retrieved from a non-sparse buffer, that buffer must be bound completely and contiguously to a single VkDeviceMemory object

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceAddress.html
*/
type VkDeviceAddress = uint64

/*
VkDeviceSize is generated from the Khronos Vulkan registry.

[Context]
Vulkan device memory size and offsets

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceSize.html
*/
type VkDeviceSize = uint64

/*
VkFlags is generated from the Khronos Vulkan registry.

[Context]
Vulkan bitmasks

[Description]
Bitmasks are passed to many commands and structures to compactly represent
options, but VkFlags is not used directly in the API.
Instead, a Vk*Flags type which is an alias of VkFlags, and
whose name matches the corresponding Vk*FlagBits that are valid for
that type, is used.

Any Vk*Flags member or parameter used in the API as an input must be
a valid combination of bit flags.
A valid combination is either zero or the bitwise OR of valid bit flags.

An individual bit flag is valid for a Vk*Flags type if it would be a
valid enumerant when used with the
equivalent Vk*FlagBits type, where the bits type is obtained by taking
the flag type and replacing the trailing Flags with FlagBits.
For example, a flag value of type VkColorComponentFlags must contain
only bit flags defined by VkColorComponentFlagBits.

Any Vk*Flags member or parameter returned from a query command or
otherwise output from Vulkan to the application may contain bit flags
undefined in its corresponding Vk*FlagBits type.
An application cannot rely on the state of these unspecified bits.

Only the low-order 31 bits (bit positions zero through 30) are available for
use as flag bits.

This restriction is due to poorly defined behavior by C compilers given a C
enumerant value of 0x80000000.
In some cases adding this enumerant value may increase the size of the
underlying Vk*FlagBits type, breaking the ABI.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkFlags.html
*/
type VkFlags = uint32

/*
VkFlags64 is generated from the Khronos Vulkan registry.

[Context]
Vulkan 64-bit bitmasks

[Description]
When the 31 bits available in VkFlags are insufficient, the
VkFlags64 type can be passed to commands and structures to
represent up to 64 options.
VkFlags64 is not used directly in the API.
Instead, a Vk*Flags2 type which is an alias of VkFlags64, and
whose name matches the corresponding Vk*FlagBits2 that are valid for
that type, is used.

Any Vk*Flags2 member or parameter used in the API as an input must be
a valid combination of bit flags.
A valid combination is either zero or the bitwise OR of valid bit flags.

An individual bit flag is valid for a Vk*Flags2 type if it would be a
valid enumerant when used with the
equivalent Vk*FlagBits2 type, where the bits type is obtained by
taking the flag type and replacing the trailing Flags2 with
FlagBits2.
For example, a flag value of type VkAccessFlags2KHR must contain only
bit flags defined by VkAccessFlagBits2KHR.

Any Vk*Flags2 member or parameter returned from a query command or
otherwise output from Vulkan to the application may contain bit flags
undefined in its corresponding Vk*FlagBits2 type.
An application cannot rely on the state of these unspecified bits.

Both the Vk*FlagBits2 type, and the individual bits defined for that
type, are defined as uint64_t integers in the C API.
This is in contrast to the 32-bit types, where the Vk*FlagBits type is
defined as a C enum and the individual bits as enumerants belonging to
that enum.
As a result, there is less compile time type checking possible for the
64-bit types.
This is unavoidable since there is no sufficiently portable way to define a
64-bit enum type in C99.

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkFlags64.html
*/
type VkFlags64 = uint64

/*
VkSampleMask is generated from the Khronos Vulkan registry.

[Context]
Mask of sample coverage information

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSampleMask.html
*/
type VkSampleMask = uint32
