// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-22 22:16:08 CEST

package bindings

/*
[Context]
Vulkan hardcoded constants - not an enumerated type, part of the header boilerplate

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/API Constants.html
*/
const (
	/*
		VK_ATTACHMENT_UNUSED is generated from the Khronos Vulkan registry.

		[Context]
		Unused attachment sentinel

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_ATTACHMENT_UNUSED.html
	*/
	VK_ATTACHMENT_UNUSED = ^uint32(0)

	/*
		VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_ALIGNMENT_AMDX is generated from the Khronos Vulkan registry.

		[Context]
		Alignment requirement for DGF1 compressed data

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_ALIGNMENT_AMDX.html
	*/
	VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_ALIGNMENT_AMDX = 128

	/*
		VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_STRIDE_AMDX is generated from the Khronos Vulkan registry.

		[Context]
		Alignment requirement for DGF1 compressed data

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_STRIDE_AMDX.html
	*/
	VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_STRIDE_AMDX = 128

	/*
		VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV is generated from the Khronos Vulkan registry.

		[Context]
		High occupancy priority constant

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV.html
	*/
	VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV float32 = 0.75

	/*
		VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV is generated from the Khronos Vulkan registry.

		[Context]
		Low occupancy priority constant

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV.html
	*/
	VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV float32 = 0.25

	/*
		VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV is generated from the Khronos Vulkan registry.

		[Context]
		Normal occupancy priority constant

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV.html
	*/
	VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV float32 = 0.50

	/*
		VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM is generated from the Khronos Vulkan registry.

		[Context]
		Length of a data graph toolchain version string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM.html
	*/
	VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM = 3

	/*
		VK_FALSE is generated from the Khronos Vulkan registry.

		[Context]
		Boolean false value

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_FALSE.html
	*/
	VK_FALSE = 0

	/*
		VK_LOD_CLAMP_NONE is generated from the Khronos Vulkan registry.

		[Context]
		Maximum LOD unclamped access sentinel

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_LOD_CLAMP_NONE.html
	*/
	VK_LOD_CLAMP_NONE float32 = 1000.0

	/*
		VK_LUID_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Length of a locally unique device identifier

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_LUID_SIZE.html
	*/
	VK_LUID_SIZE = 8

	/*
		VK_MAX_DATA_GRAPH_TOSA_NAME_SIZE_ARM is generated from the Khronos Vulkan registry.

		[Context]
		Length of a data graph TOSA profile or extension name string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_DATA_GRAPH_TOSA_NAME_SIZE_ARM.html
	*/
	VK_MAX_DATA_GRAPH_TOSA_NAME_SIZE_ARM = 128

	/*
		VK_MAX_DESCRIPTION_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Length of a driver name string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_DESCRIPTION_SIZE.html
	*/
	VK_MAX_DESCRIPTION_SIZE = 256

	/*
		VK_MAX_DEVICE_GROUP_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Length of a physical device handle array

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_DEVICE_GROUP_SIZE.html
	*/
	VK_MAX_DEVICE_GROUP_SIZE = 32

	/*
		VK_MAX_DRIVER_INFO_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Length of a physical device driver information string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_DRIVER_INFO_SIZE.html
	*/
	VK_MAX_DRIVER_INFO_SIZE = 256

	/*
		VK_MAX_DRIVER_NAME_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Maximum length of a physical device driver name string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_DRIVER_NAME_SIZE.html
	*/
	VK_MAX_DRIVER_NAME_SIZE = 256

	/*
		VK_MAX_EXTENSION_NAME_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Maximum length of a layer of extension name string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_EXTENSION_NAME_SIZE.html
	*/
	VK_MAX_EXTENSION_NAME_SIZE = 256

	/*
		VK_MAX_GLOBAL_PRIORITY_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Length of an array of global queue priorities

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_GLOBAL_PRIORITY_SIZE.html
	*/
	VK_MAX_GLOBAL_PRIORITY_SIZE = 16

	/*
		VK_MAX_MEMORY_HEAPS is generated from the Khronos Vulkan registry.

		[Context]
		Length of an array of memory heaps

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_MEMORY_HEAPS.html
	*/
	VK_MAX_MEMORY_HEAPS = 16

	/*
		VK_MAX_MEMORY_TYPES is generated from the Khronos Vulkan registry.

		[Context]
		Length of an array of memory types

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_MEMORY_TYPES.html
	*/
	VK_MAX_MEMORY_TYPES = 32

	/*
		VK_MAX_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_SET_NAME_SIZE_ARM is generated from the Khronos Vulkan registry.

		[Context]
		Length of a data graph operation name string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_SET_NAME_SIZE_ARM.html
	*/
	VK_MAX_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_SET_NAME_SIZE_ARM = 128

	/*
		VK_MAX_PHYSICAL_DEVICE_NAME_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Length of a physical device name string

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_PHYSICAL_DEVICE_NAME_SIZE.html
	*/
	VK_MAX_PHYSICAL_DEVICE_NAME_SIZE = 256

	/*
		VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR is generated from the Khronos Vulkan registry.

		[Context]
		Maximum length of binary key

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR.html
	*/
	VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR = 32

	/*
		VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT is generated from the Khronos Vulkan registry.

		[Context]
		Maximum length of a shader module identifier

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT.html
	*/
	VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT = 32

	/*
		VK_MAX_VIDEO_AV1_REFERENCES_PER_FRAME_KHR is generated from the Khronos Vulkan registry.

		[Context]
		Length of an array of supported queue priorities

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_VIDEO_AV1_REFERENCES_PER_FRAME_KHR.html
	*/
	VK_MAX_VIDEO_AV1_REFERENCES_PER_FRAME_KHR = 7

	/*
		VK_MAX_VIDEO_VP9_REFERENCES_PER_FRAME_KHR is generated from the Khronos Vulkan registry.

		[Context]
		Length of an array of supported queue priorities

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_MAX_VIDEO_VP9_REFERENCES_PER_FRAME_KHR.html
	*/
	VK_MAX_VIDEO_VP9_REFERENCES_PER_FRAME_KHR = 3

	/*
		VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV is generated from the Khronos Vulkan registry.

		[Context]
		Sentinel for global acceleration structure partitions

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV.html
	*/
	VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV = ^uint32(0)

	/*
		VK_QUEUE_FAMILY_EXTERNAL is generated from the Khronos Vulkan registry.

		[Context]
		External queue family index sentinel

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_QUEUE_FAMILY_EXTERNAL.html
	*/
	VK_QUEUE_FAMILY_EXTERNAL = ^uint32(1)

	/*
		VK_QUEUE_FAMILY_FOREIGN_EXT is generated from the Khronos Vulkan registry.

		[Context]
		Foreign queue family index sentinel

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_QUEUE_FAMILY_FOREIGN_EXT.html
	*/
	VK_QUEUE_FAMILY_FOREIGN_EXT = ^uint32(2)

	/*
		VK_QUEUE_FAMILY_IGNORED is generated from the Khronos Vulkan registry.

		[Context]
		Ignored queue family index sentinel

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_QUEUE_FAMILY_IGNORED.html
	*/
	VK_QUEUE_FAMILY_IGNORED = ^uint32(0)

	/*
		VK_REMAINING_3D_SLICES_EXT is generated from the Khronos Vulkan registry.

		[Context]
		Sentinel for all remaining 3D slices

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_REMAINING_3D_SLICES_EXT.html
	*/
	VK_REMAINING_3D_SLICES_EXT = ^uint32(0)

	/*
		VK_REMAINING_ARRAY_LAYERS is generated from the Khronos Vulkan registry.

		[Context]
		Sentinel for all remaining array layers

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_REMAINING_ARRAY_LAYERS.html
	*/
	VK_REMAINING_ARRAY_LAYERS = ^uint32(0)

	/*
		VK_REMAINING_MIP_LEVELS is generated from the Khronos Vulkan registry.

		[Context]
		Sentinel for all remaining mipmap levels

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_REMAINING_MIP_LEVELS.html
	*/
	VK_REMAINING_MIP_LEVELS = ^uint32(0)

	/*
		VK_SHADER_INDEX_UNUSED_AMDX is generated from the Khronos Vulkan registry.

		[Context]
		Sentinel for an unused shader index

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_SHADER_INDEX_UNUSED_AMDX.html
	*/
	VK_SHADER_INDEX_UNUSED_AMDX = ^uint32(0)

	/*
		VK_SHADER_UNUSED_KHR is generated from the Khronos Vulkan registry.

		[Context]
		Sentinel for an unused shader index

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_SHADER_UNUSED_KHR.html
	*/
	VK_SHADER_UNUSED_KHR = ^uint32(0)

	/*
		VK_SUBPASS_EXTERNAL is generated from the Khronos Vulkan registry.

		[Context]
		Subpass index sentinel expanding synchronization scope outside a subpass

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_SUBPASS_EXTERNAL.html
	*/
	VK_SUBPASS_EXTERNAL = ^uint32(0)

	/*
		VK_TRUE is generated from the Khronos Vulkan registry.

		[Context]
		Boolean true value

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_TRUE.html
	*/
	VK_TRUE = 1

	/*
		VK_UUID_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Length of a universally unique device or driver build identifier

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_UUID_SIZE.html
	*/
	VK_UUID_SIZE = 16

	/*
		VK_WHOLE_SIZE is generated from the Khronos Vulkan registry.

		[Context]
		Sentinel value to use entire remaining array length

		[Reference]
		https://registry.khronos.org/vulkan/specs/latest/man/html/VK_WHOLE_SIZE.html
	*/
	VK_WHOLE_SIZE = ^uint64(0)
)
