// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-22 21:35:07 CEST

package bindings

/*
VkBool32 is generated from the Khronos Vulkan registry.

[Context]
Vulkan boolean type

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkBool32.html
*/
type VkBool32 = uint32

/*
VkDeviceAddress is generated from the Khronos Vulkan registry.

[Context]
Vulkan device address type

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceAddress.html
*/
type VkDeviceAddress = uint64

/*
VkDeviceSize is generated from the Khronos Vulkan registry.

[Context]
Vulkan device memory size and offsets

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceSize.html
*/
type VkDeviceSize = uint64

/*
VkFlags is generated from the Khronos Vulkan registry.

[Context]
Vulkan bitmasks

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkFlags.html
*/
type VkFlags = uint32

/*
VkFlags64 is generated from the Khronos Vulkan registry.

[Context]
Vulkan 64-bit bitmasks

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkFlags64.html
*/
type VkFlags64 = uint64

/*
VkSampleMask is generated from the Khronos Vulkan registry.

[Context]
Mask of sample coverage information

[Reference]
https://registry.khronos.org/vulkan/specs/latest/man/html/VkSampleMask.html
*/
type VkSampleMask = uint32
