// This file was auto-generated by 'gpuarch Vulkan bindings generator' at 2026-05-22 20:42:46 CEST

package bindings

/*
VkAccelerationStructureKHR is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR.
*/
type VkAccelerationStructureKHR uint64

/*
VkAccelerationStructureNV is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV.
*/
type VkAccelerationStructureNV uint64

/*
VkBuffer is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_BUFFER.
*/
type VkBuffer uint64

/*
VkBufferCollectionFUCHSIA is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_BUFFER_COLLECTION_FUCHSIA.
*/
type VkBufferCollectionFUCHSIA uint64

/*
VkBufferView is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_BUFFER_VIEW.
*/
type VkBufferView uint64

/*
VkCommandBuffer is a dispatchable Vulkan handle.

Parent object type is VkCommandPool.

Object type token is VK_OBJECT_TYPE_COMMAND_BUFFER.
*/
type VkCommandBuffer uintptr

/*
VkCommandPool is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_COMMAND_POOL.
*/
type VkCommandPool uint64

/*
VkCuFunctionNVX is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_CU_FUNCTION_NVX.
*/
type VkCuFunctionNVX uint64

/*
VkCuModuleNVX is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_CU_MODULE_NVX.
*/
type VkCuModuleNVX uint64

/*
VkCudaFunctionNV is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_CUDA_FUNCTION_NV.
*/
type VkCudaFunctionNV uint64

/*
VkCudaModuleNV is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_CUDA_MODULE_NV.
*/
type VkCudaModuleNV uint64

/*
VkDataGraphPipelineSessionARM is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_DATA_GRAPH_PIPELINE_SESSION_ARM.
*/
type VkDataGraphPipelineSessionARM uint64

/*
VkDebugReportCallbackEXT is a non-dispatchable Vulkan handle.

Parent object type is VkInstance.

Object type token is VK_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT.
*/
type VkDebugReportCallbackEXT uint64

/*
VkDebugUtilsMessengerEXT is a non-dispatchable Vulkan handle.

Parent object type is VkInstance.

Object type token is VK_OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT.
*/
type VkDebugUtilsMessengerEXT uint64

/*
VkDeferredOperationKHR is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_DEFERRED_OPERATION_KHR.
*/
type VkDeferredOperationKHR uint64

/*
VkDescriptorPool is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_DESCRIPTOR_POOL.
*/
type VkDescriptorPool uint64

/*
VkDescriptorSet is a non-dispatchable Vulkan handle.

Parent object type is VkDescriptorPool.

Object type token is VK_OBJECT_TYPE_DESCRIPTOR_SET.
*/
type VkDescriptorSet uint64

/*
VkDescriptorSetLayout is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT.
*/
type VkDescriptorSetLayout uint64

/*
VkDescriptorUpdateTemplate is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE.
*/
type VkDescriptorUpdateTemplate uint64

/*
VkDevice is a dispatchable Vulkan handle.

Parent object type is VkPhysicalDevice.

Object type token is VK_OBJECT_TYPE_DEVICE.
*/
type VkDevice uintptr

/*
VkDeviceMemory is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_DEVICE_MEMORY.
*/
type VkDeviceMemory uint64

/*
VkDisplayKHR is a non-dispatchable Vulkan handle.

Parent object type is VkPhysicalDevice.

Object type token is VK_OBJECT_TYPE_DISPLAY_KHR.
*/
type VkDisplayKHR uint64

/*
VkDisplayModeKHR is a non-dispatchable Vulkan handle.

Parent object type is VkDisplayKHR.

Object type token is VK_OBJECT_TYPE_DISPLAY_MODE_KHR.
*/
type VkDisplayModeKHR uint64

/*
VkEvent is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_EVENT.
*/
type VkEvent uint64

/*
VkExternalComputeQueueNV is a dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_EXTERNAL_COMPUTE_QUEUE_NV.
*/
type VkExternalComputeQueueNV uintptr

/*
VkFence is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_FENCE.
*/
type VkFence uint64

/*
VkFramebuffer is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_FRAMEBUFFER.
*/
type VkFramebuffer uint64

/*
VkGpaSessionAMD is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_GPA_SESSION_AMD.
*/
type VkGpaSessionAMD uint64

/*
VkImage is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_IMAGE.
*/
type VkImage uint64

/*
VkImageView is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_IMAGE_VIEW.
*/
type VkImageView uint64

/*
VkIndirectCommandsLayoutEXT is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_EXT.
*/
type VkIndirectCommandsLayoutEXT uint64

/*
VkIndirectCommandsLayoutNV is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NV.
*/
type VkIndirectCommandsLayoutNV uint64

/*
VkIndirectExecutionSetEXT is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_INDIRECT_EXECUTION_SET_EXT.
*/
type VkIndirectExecutionSetEXT uint64

/*
VkInstance is a dispatchable Vulkan handle.

Object type token is VK_OBJECT_TYPE_INSTANCE.
*/
type VkInstance uintptr

/*
VkMicromapEXT is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_MICROMAP_EXT.
*/
type VkMicromapEXT uint64

/*
VkOpticalFlowSessionNV is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_OPTICAL_FLOW_SESSION_NV.
*/
type VkOpticalFlowSessionNV uint64

/*
VkPerformanceConfigurationINTEL is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_PERFORMANCE_CONFIGURATION_INTEL.
*/
type VkPerformanceConfigurationINTEL uint64

/*
VkPhysicalDevice is a dispatchable Vulkan handle.

Parent object type is VkInstance.

Object type token is VK_OBJECT_TYPE_PHYSICAL_DEVICE.
*/
type VkPhysicalDevice uintptr

/*
VkPipeline is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_PIPELINE.
*/
type VkPipeline uint64

/*
VkPipelineBinaryKHR is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_PIPELINE_BINARY_KHR.
*/
type VkPipelineBinaryKHR uint64

/*
VkPipelineCache is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_PIPELINE_CACHE.
*/
type VkPipelineCache uint64

/*
VkPipelineLayout is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_PIPELINE_LAYOUT.
*/
type VkPipelineLayout uint64

/*
VkPrivateDataSlot is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_PRIVATE_DATA_SLOT.
*/
type VkPrivateDataSlot uint64

/*
VkQueryPool is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_QUERY_POOL.
*/
type VkQueryPool uint64

/*
VkQueue is a dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_QUEUE.
*/
type VkQueue uintptr

/*
VkRenderPass is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_RENDER_PASS.
*/
type VkRenderPass uint64

/*
VkSampler is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SAMPLER.
*/
type VkSampler uint64

/*
VkSamplerYcbcrConversion is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION.
*/
type VkSamplerYcbcrConversion uint64

/*
VkSemaphore is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SEMAPHORE.
*/
type VkSemaphore uint64

/*
VkSemaphoreSciSyncPoolNV is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SEMAPHORE_SCI_SYNC_POOL_NV.
*/
type VkSemaphoreSciSyncPoolNV uint64

/*
VkShaderEXT is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SHADER_EXT.
*/
type VkShaderEXT uint64

/*
VkShaderInstrumentationARM is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SHADER_INSTRUMENTATION_ARM.
*/
type VkShaderInstrumentationARM uint64

/*
VkShaderModule is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SHADER_MODULE.
*/
type VkShaderModule uint64

/*
VkSurfaceKHR is a non-dispatchable Vulkan handle.

Parent object type is VkInstance.

Object type token is VK_OBJECT_TYPE_SURFACE_KHR.
*/
type VkSurfaceKHR uint64

/*
VkSwapchainKHR is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_SWAPCHAIN_KHR.
*/
type VkSwapchainKHR uint64

/*
VkTensorARM is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_TENSOR_ARM.
*/
type VkTensorARM uint64

/*
VkTensorViewARM is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_TENSOR_VIEW_ARM.
*/
type VkTensorViewARM uint64

/*
VkValidationCacheEXT is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_VALIDATION_CACHE_EXT.
*/
type VkValidationCacheEXT uint64

/*
VkVideoSessionKHR is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_VIDEO_SESSION_KHR.
*/
type VkVideoSessionKHR uint64

/*
VkVideoSessionParametersKHR is a non-dispatchable Vulkan handle.

Parent object type is VkDevice.

Object type token is VK_OBJECT_TYPE_VIDEO_SESSION_PARAMETERS_KHR.
*/
type VkVideoSessionParametersKHR uint64

/*
VkSamplerYcbcrConversionKHR is a non-dispatchable Vulkan handle.
*/
type VkSamplerYcbcrConversionKHR = VkSamplerYcbcrConversion

/*
VkDescriptorUpdateTemplateKHR is a non-dispatchable Vulkan handle.
*/
type VkDescriptorUpdateTemplateKHR = VkDescriptorUpdateTemplate

/*
VkPrivateDataSlotEXT is a non-dispatchable Vulkan handle.
*/
type VkPrivateDataSlotEXT = VkPrivateDataSlot
